/*
 * Hindi (Devanagari) names for every food in fooddb.js, keyed by English name.
 * Used for Hindi and Marathi charts directly, and transliterated for other
 * Indian scripts (see i18n.js). Also makes the food search work in Hindi.
 */
(function (root) {
  const HI = {
    'Warm lemon water': 'गुनगुना नींबू पानी',
    'Jeera (cumin) water': 'जीरा पानी',
    'Methi (fenugreek) seed water': 'मेथी दाना पानी',
    'Ajwain (carom) water': 'अजवाइन पानी',
    'Dhaniya (coriander seed) water': 'धनिया पानी',
    'Saunf (fennel) water': 'सौंफ पानी',
    'Dalchini (cinnamon) water': 'दालचीनी पानी',
    'Amla juice in warm water': 'गुनगुने पानी में आंवला रस',
    'Aloe vera juice in water': 'पानी में एलोवेरा रस',
    'Tulsi–ginger herbal tea': 'तुलसी–अदरक हर्बल चाय',
    'Green tea (no sugar)': 'ग्रीन टी (बिना चीनी)',
    'Wheatgrass juice': 'व्हीटग्रास जूस',
    'Lemon–honey water': 'नींबू–शहद पानी',
    'Soaked almonds': 'भीगे बादाम',
    'Walnut halves': 'अखरोट',
    'Soaked kishmish (raisins)': 'भीगी किशमिश',
    'Soaked chia seeds': 'भीगे चिया बीज',
    'Roasted flaxseed': 'भुनी अलसी',
    'Pumpkin seeds': 'कद्दू के बीज',
    'Sunflower seeds': 'सूरजमुखी के बीज',
    'Soaked methi seeds': 'भीगे मेथी दाने',
    'Haldi doodh (low-fat turmeric milk)': 'हल्दी दूध (कम वसा)',
    'Warm toned milk with elaichi': 'इलायची वाला गुनगुना टोंड दूध',
    'Warm skimmed milk': 'गुनगुना स्किम्ड दूध',
    'Unsweetened almond milk': 'बिना चीनी बादाम दूध',
    'Warm soy milk with cinnamon': 'दालचीनी वाला गुनगुना सोया दूध',
    'Chamomile tea': 'कैमोमाइल चाय',
    'Dalchini (cinnamon) tea': 'दालचीनी चाय',
    'Apple': 'सेब',
    'Pear': 'नाशपाती',
    'Guava': 'अमरूद',
    'Orange': 'संतरा',
    'Mosambi (sweet lime)': 'मौसमी',
    'Banana (small)': 'केला (छोटा)',
    'Papaya': 'पपीता',
    'Watermelon': 'तरबूज',
    'Muskmelon': 'खरबूजा',
    'Pomegranate seeds': 'अनार के दाने',
    'Pineapple': 'अनानास',
    'Mango slices': 'आम के टुकड़े',
    'Grapes': 'अंगूर',
    'Chikoo (sapota)': 'चीकू',
    'Kiwi': 'कीवी',
    'Strawberries': 'स्ट्रॉबेरी',
    'Blueberries': 'ब्लूबेरी',
    'Jamun': 'जामुन',
    'Plums': 'आलूबुखारा',
    'Peach': 'आड़ू',
    'Custard apple (sitaphal)': 'सीताफल',
    'Fresh figs': 'ताज़े अंजीर',
    'Litchi': 'लीची',
    'Cherries': 'चेरी',
    'Dragon fruit': 'ड्रैगन फ्रूट',
    'Mixed fruit bowl': 'मिक्स फल कटोरी',
    'Amla (Indian gooseberry)': 'आंवला',
    'Chaas (buttermilk)': 'छाछ',
    'Salted lassi': 'नमकीन लस्सी',
    'Nimbu pani (no sugar)': 'नींबू पानी (बिना चीनी)',
    'Tender coconut water': 'नारियल पानी',
    'Sattu drink': 'सत्तू शरबत',
    'Masala tea (less sugar)': 'मसाला चाय (कम चीनी)',
    'Black coffee': 'ब्लैक कॉफी',
    'Filter coffee (less sugar)': 'फ़िल्टर कॉफी (कम चीनी)',
    'Toned milk': 'टोंड दूध',
    'Soy milk': 'सोया दूध',
    'Jaljeera': 'जलजीरा',
    'Kokum sharbat (no sugar)': 'कोकम शरबत (बिना चीनी)',
    'Aam panna (less sugar)': 'आम पना (कम चीनी)',
    'Fresh vegetable juice': 'ताज़ा सब्ज़ी जूस',
    'Whey protein shake (in water)': 'व्हे प्रोटीन शेक (पानी में)',
    'Plant protein shake': 'प्लांट प्रोटीन शेक',
    'Banana–milk smoothie (no sugar)': 'केला–दूध स्मूदी (बिना चीनी)',
    'Spinach–apple green smoothie': 'पालक–सेब ग्रीन स्मूदी',
    'Roasted chana': 'भुने चने',
    'Roasted makhana (fox nuts)': 'भुने मखाने',
    'Moong sprouts chaat': 'मूंग स्प्राउट्स चाट',
    'Mixed sprouts salad': 'मिक्स स्प्राउट्स सलाद',
    'Kala chana chaat': 'काला चना चाट',
    'Roasted peanuts': 'भुनी मूंगफली',
    'Almonds': 'बादाम',
    'Mixed nuts': 'मिक्स मेवे',
    'Roasted pumpkin seeds': 'भुने कद्दू के बीज',
    'Trail mix (nuts & seeds)': 'ट्रेल मिक्स (मेवे और बीज)',
    'Roasted murmura chivda': 'भुना मुरमुरा चिवड़ा',
    'Sprouts bhel (no sev)': 'स्प्राउट्स भेल (बिना सेव)',
    'Multigrain khakhra': 'मल्टीग्रेन खाखरा',
    'Khaman dhokla': 'खमण ढोकला',
    'Moong dal dhokla': 'मूंग दाल ढोकला',
    'Idli': 'इडली',
    'Paneer tikka': 'पनीर टिक्का',
    'Paneer cubes with chaat masala': 'चाट मसाला पनीर',
    'Tofu tikka': 'टोफू टिक्का',
    'Soya chunks chaat': 'सोया चंक्स चाट',
    'Sweet corn chaat': 'स्वीट कॉर्न चाट',
    'Fruit chaat': 'फ्रूट चाट',
    'Vegetable sandwich (multigrain)': 'वेज सैंडविच (मल्टीग्रेन)',
    'Paneer sandwich (multigrain)': 'पनीर सैंडविच (मल्टीग्रेन)',
    'Egg sandwich (multigrain)': 'अंडा सैंडविच (मल्टीग्रेन)',
    'Chicken sandwich (multigrain)': 'चिकन सैंडविच (मल्टीग्रेन)',
    'Boiled eggs': 'उबले अंडे',
    'Boiled egg whites': 'उबले अंडे की सफेदी',
    'Egg chaat': 'अंडा चाट',
    'Chicken tikka (snack)': 'चिकन टिक्का (स्नैक)',
    'Fish tikka (snack)': 'फिश टिक्का (स्नैक)',
    'Grilled chicken strips': 'ग्रिल्ड चिकन स्ट्रिप्स',
    'Greek yogurt': 'ग्रीक योगर्ट',
    'Hung curd dip with veg sticks': 'हंग कर्ड डिप और सब्ज़ी स्टिक्स',
    'Hummus with veggie sticks': 'हम्मस और सब्ज़ी स्टिक्स',
    'Baked sweet potato chaat': 'बेक्ड शकरकंद चाट',
    'Vegetable poha (small)': 'वेज पोहा (छोटा)',
    'Protein bar': 'प्रोटीन बार',
    'Peanut chikki': 'मूंगफली चिक्की',
    'Dry fruit laddoo (no sugar)': 'ड्राई फ्रूट लड्डू (बिना चीनी)',
    'Sattu laddoo': 'सत्तू लड्डू',
    'Rice cakes': 'राइस केक',
    'Air-popped popcorn': 'बिना तेल पॉपकॉर्न',
    'Cucumber & carrot sticks': 'खीरा और गाजर स्टिक्स',
    'Sprouts tikki (baked)': 'स्प्राउट्स टिक्की (बेक्ड)',
    'Oats tikki (baked)': 'ओट्स टिक्की (बेक्ड)',
    'Moong dal chilla (small)': 'मूंग दाल चीला (छोटा)',
    'Besan chilla (small)': 'बेसन चीला (छोटा)',
    'Edamame (steamed)': 'एडामामे (उबला)',
    'Cottage cheese with pepper': 'काली मिर्च वाला कॉटेज चीज़',
    'Clear vegetable soup': 'क्लियर वेज सूप',
    'Tomato soup (no cream)': 'टमाटर सूप (बिना क्रीम)',
    'Moong dal soup': 'मूंग दाल सूप',
    'Lauki soup': 'लौकी सूप',
    'Palak soup': 'पालक सूप',
    'Sweet corn vegetable soup': 'स्वीट कॉर्न वेज सूप',
    'Mushroom soup (no cream)': 'मशरूम सूप (बिना क्रीम)',
    'Chicken clear soup': 'चिकन क्लियर सूप',
    'Rasam': 'रसम',
    'Veg manchow soup (less oil)': 'वेज मनचाउ सूप (कम तेल)',
    'Minestrone soup': 'मिनेस्ट्रोन सूप',
    'Lentil soup': 'दाल का सूप',
    'Miso soup': 'मिसो सूप',
    'Tom yum soup (veg)': 'टॉम यम सूप (वेज)',
    'Chicken tom yum': 'चिकन टॉम यम',
    'Pumpkin soup': 'कद्दू सूप',
    'Broccoli–almond soup': 'ब्रोकली–बादाम सूप',
    'Chicken sweet corn soup': 'चिकन स्वीट कॉर्न सूप',
    'Idli (breakfast)': 'इडली',
    'Rava idli': 'रवा इडली',
    'Ragi idli': 'रागी इडली',
    'Oats idli': 'ओट्स इडली',
    'Plain dosa (less oil)': 'सादा डोसा (कम तेल)',
    'Masala dosa (less oil)': 'मसाला डोसा (कम तेल)',
    'Ragi dosa': 'रागी डोसा',
    'Oats dosa': 'ओट्स डोसा',
    'Neer dosa': 'नीर डोसा',
    'Pesarattu (green moong dosa)': 'पेसरट्टू (हरी मूंग डोसा)',
    'Adai (mixed dal dosa)': 'अडई (मिक्स दाल डोसा)',
    'Onion–tomato uttapam': 'प्याज़–टमाटर उत्तपम',
    'Appam': 'अप्पम',
    'Idiyappam': 'इडियप्पम',
    'Puttu': 'पुट्टू',
    'Ven pongal': 'वेन पोंगल',
    'Rava upma': 'रवा उपमा',
    'Vegetable oats upma': 'वेज ओट्स उपमा',
    'Semiya (vermicelli) upma': 'सेवई उपमा',
    'Vegetable poha': 'वेज पोहा',
    'Sprouts poha': 'स्प्राउट्स पोहा',
    'Sabudana khichdi': 'साबूदाना खिचड़ी',
    'Multigrain thalipeeth': 'मल्टीग्रेन थालीपीठ',
    'Misal (no farsan)': 'मिसल (बिना फरसाण)',
    'Khaman dhokla (breakfast)': 'खमण ढोकला',
    'Methi thepla (breakfast)': 'मेथी थेपला',
    'Handvo': 'हांडवो',
    'Moong dal chilla': 'मूंग दाल चीला',
    'Besan chilla': 'बेसन चीला',
    'Oats chilla': 'ओट्स चीला',
    'Paneer-stuffed besan chilla': 'पनीर भरा बेसन चीला',
    'Aloo paratha (less ghee)': 'आलू पराठा (कम घी)',
    'Gobhi paratha': 'गोभी पराठा',
    'Paneer paratha': 'पनीर पराठा',
    'Methi paratha': 'मेथी पराठा',
    'Mooli paratha': 'मूली पराठा',
    'Missi roti (breakfast)': 'मिस्सी रोटी',
    'Savoury vegetable dalia': 'नमकीन वेज दलिया',
    'Dalia porridge with milk': 'दूध वाला दलिया',
    'Ragi porridge with milk': 'दूध वाला रागी दलिया',
    'Ghugni': 'घुगनी',
    'Sattu paratha': 'सत्तू पराठा',
    'Chuda–dahi (poha with curd)': 'चूड़ा–दही',
    'Baked litti': 'बेक्ड लिट्टी',
    'Masala omelette': 'मसाला ऑमलेट',
    'Egg bhurji': 'अंडा भुर्जी',
    'Egg white omelette': 'अंडे की सफेदी का ऑमलेट',
    'Anda paratha': 'अंडा पराठा',
    'Egg dosa': 'अंडा डोसा',
    'Chicken keema': 'चिकन कीमा',
    'Tofu bhurji': 'टोफू भुर्जी',
    'Paneer bhurji': 'पनीर भुर्जी',
    'Instant oats cup': 'इंस्टेंट ओट्स कप',
    'Instant poha cup': 'इंस्टेंट पोहा कप',
    'Instant upma cup': 'इंस्टेंट उपमा कप',
    'Sambar': 'सांभर',
    'Coconut chutney': 'नारियल चटनी',
    'Mint–coriander chutney': 'पुदीना–धनिया चटनी',
    'Tomato chutney': 'टमाटर चटनी',
    'Peanut chutney': 'मूंगफली चटनी',
    'Ginger chutney': 'अदरक चटनी',
    'Curd': 'दही',
    'Multigrain toast': 'मल्टीग्रेन टोस्ट',
    'Boiled egg': 'उबला अंडा',
    'Phulka': 'फुलका',
    'Chapati (light ghee)': 'चपाती (हल्का घी)',
    'Multigrain roti': 'मल्टीग्रेन रोटी',
    'Jowar roti': 'ज्वार रोटी',
    'Bajra roti': 'बाजरा रोटी',
    'Ragi roti': 'रागी रोटी',
    'Makki roti': 'मक्के की रोटी',
    'Besan missi roti': 'बेसन मिस्सी रोटी',
    'Methi thepla': 'मेथी थेपला',
    'Gujarati rotli': 'गुजराती रोटली',
    'Jowar bhakri': 'ज्वार भाकरी',
    'Tandoori roti': 'तंदूरी रोटी',
    'Naan': 'नान',
    'Plain paratha': 'सादा पराठा',
    'Steamed rice': 'उबले चावल',
    'Brown rice': 'ब्राउन राइस',
    'Jeera rice': 'जीरा राइस',
    'Kerala matta rice': 'केरल मट्टा चावल',
    'Foxtail millet rice': 'कंगनी (फॉक्सटेल मिलेट)',
    'Kodo millet rice': 'कोदो मिलेट',
    'Cooked quinoa': 'पका क्विनोआ',
    'Vegetable pulao': 'वेज पुलाव',
    'Lemon rice': 'लेमन राइस',
    'Curd rice': 'दही चावल',
    'Tamarind rice (puliyogare)': 'इमली चावल (पुलियोगरे)',
    'Moong dal khichdi': 'मूंग दाल खिचड़ी',
    'Vegetable dalia khichdi': 'वेज दलिया खिचड़ी',
    'Bajra–moong khichdi': 'बाजरा–मूंग खिचड़ी',
    'Oats–moong khichdi': 'ओट्स–मूंग खिचड़ी',
    'Vegetable quinoa khichdi': 'वेज क्विनोआ खिचड़ी',
    'Bisi bele bath': 'बिसी बेले भात',
    'Vegetable biryani': 'वेज बिरयानी',
    'Chicken biryani': 'चिकन बिरयानी',
    'Egg biryani': 'अंडा बिरयानी',
    'Soya pulao': 'सोया पुलाव',
    'Instant khichdi cup': 'इंस्टेंट खिचड़ी कप',
    'Dal tadka (toor)': 'दाल तड़का (अरहर)',
    'Moong dal': 'मूंग दाल',
    'Masoor dal': 'मसूर दाल',
    'Chana dal': 'चना दाल',
    'Panchmel (mixed) dal': 'पंचमेल दाल',
    'Dal palak': 'दाल पालक',
    'Chana dal with lauki': 'लौकी चना दाल',
    'Gujarati dal': 'गुजराती दाल',
    'Dal makhani': 'दाल मखनी',
    'Rajma': 'राजमा',
    'Chole': 'छोले',
    'Kala chana curry': 'काले चने की सब्ज़ी',
    'Lobia curry': 'लोबिया',
    'Kadhi (no pakoda)': 'कढ़ी (बिना पकौड़ा)',
    'Pithla': 'पिठला',
    'Moong usal': 'मूंग उसल',
    'Matki usal': 'मटकी उसल',
    'Kadala curry': 'कडला करी',
    'Cholar dal': 'छोलार दाल',
    'Dalma (dal with vegetables)': 'डालमा (सब्ज़ी वाली दाल)',
    'Moong sprouts curry': 'मूंग स्प्राउट्स करी',
    'Horse gram (kulthi) dal': 'कुलथी दाल',
    'Dhuli urad dal': 'धुली उड़द दाल',
    'Dal fry': 'दाल फ्राई',
    'Sai bhaji': 'साई भाजी',
    'Mysore rasam with dal': 'मैसूर रसम',
    'Kootu (dal & vegetable)': 'कूटू (दाल और सब्ज़ी)',
    'Palak paneer': 'पालक पनीर',
    'Matar paneer': 'मटर पनीर',
    'Kadai paneer': 'कड़ाही पनीर',
    'Paneer tikka masala (light)': 'पनीर टिक्का मसाला (हल्का)',
    'Grilled paneer': 'ग्रिल्ड पनीर',
    'Soya chunk curry': 'सोया चंक्स करी',
    'Soya keema with peas': 'मटर सोया कीमा',
    'Tofu curry': 'टोफू करी',
    'Mushroom matar': 'मशरूम मटर',
    'Egg curry (2 eggs)': 'अंडा करी (2 अंडे)',
    'Chicken curry (home-style)': 'चिकन करी (घर जैसी)',
    'Butter chicken (light)': 'बटर चिकन (हल्का)',
    'Chicken tikka': 'चिकन टिक्का',
    'Tandoori chicken (skinless)': 'तंदूरी चिकन (बिना छिलका)',
    'Chicken keema with peas': 'मटर चिकन कीमा',
    'Chettinad chicken': 'चेट्टिनाड चिकन',
    'Kerala chicken stew': 'केरल चिकन स्टू',
    'Fish curry': 'मछली करी',
    'Maacher jhol (Bengali fish curry)': 'माछेर झोल (बंगाली मछली करी)',
    'Fish tikka': 'फिश टिक्का',
    'Tawa fish': 'तवा मछली',
    'Goan fish curry': 'गोवा मछली करी',
    'Prawn masala': 'झींगा मसाला',
    'Mutton curry (lean)': 'मटन करी (कम चर्बी)',
    'Chicken & vegetable stew': 'चिकन और सब्ज़ी स्टू',
    'Bhindi masala': 'भिंडी मसाला',
    'Lauki sabzi': 'लौकी की सब्ज़ी',
    'Tinda sabzi': 'टिंडे की सब्ज़ी',
    'Turai sabzi': 'तोरई की सब्ज़ी',
    'Karela sabzi': 'करेले की सब्ज़ी',
    'Parwal sabzi': 'परवल की सब्ज़ी',
    'Patta gobhi (cabbage) sabzi': 'पत्ता गोभी की सब्ज़ी',
    'Cabbage poriyal': 'पत्ता गोभी पोरियल',
    'Beans poriyal': 'बीन्स पोरियल',
    'Beetroot poriyal': 'चुकंदर पोरियल',
    'Carrot–beans poriyal': 'गाजर–बीन्स पोरियल',
    'Cabbage thoran': 'पत्ता गोभी थोरन',
    'Beans thoran': 'बीन्स थोरन',
    'Avial': 'अवियल',
    'Aloo gobhi': 'आलू गोभी',
    'Gobhi matar': 'गोभी मटर',
    'Aloo matar': 'आलू मटर',
    'Jeera aloo': 'जीरा आलू',
    'Mixed vegetable sabzi': 'मिक्स वेज सब्ज़ी',
    'Palak bhaji': 'पालक भाजी',
    'Methi sabzi': 'मेथी की सब्ज़ी',
    'Sarson ka saag': 'सरसों का साग',
    'Baingan bharta': 'बैंगन भर्ता',
    'Bharwa baingan': 'भरवां बैंगन',
    'Kaddu (pumpkin) sabzi': 'कद्दू की सब्ज़ी',
    'Capsicum besan sabzi': 'शिमला मिर्च बेसन',
    'Mushroom sabzi': 'मशरूम की सब्ज़ी',
    'Kathal (jackfruit) sabzi': 'कटहल की सब्ज़ी',
    'Arbi sabzi': 'अरबी की सब्ज़ी',
    'Shukto': 'शुक्तो',
    'Chorchori (mixed veg)': 'चोरचोरी (मिक्स सब्ज़ी)',
    'Undhiyu (light)': 'उंधियू (हल्का)',
    'Tindora (kovakkai) sabzi': 'टिंडोरा की सब्ज़ी',
    'Gawar (cluster beans) sabzi': 'ग्वार फली की सब्ज़ी',
    'Drumstick curry': 'सहजन (ड्रमस्टिक) करी',
    'Raw banana poriyal': 'कच्चे केले का पोरियल',
    'Stir-fried vegetables (Indian)': 'स्टर-फ्राई सब्ज़ियां',
    'Ker sangri': 'केर सांगरी',
    'Vegetable kurma': 'वेज कुरमा',
    'Lauki kofta curry (baked kofta)': 'लौकी कोफ्ता करी (बेक्ड)',
    'Beans–carrot stir fry': 'बीन्स–गाजर स्टर फ्राई',
    'Cauliflower–peas dry sabzi': 'गोभी–मटर सूखी सब्ज़ी',
    'Cucumber raita': 'खीरा रायता',
    'Mint raita': 'पुदीना रायता',
    'Lauki raita': 'लौकी रायता',
    'Green salad': 'हरा सलाद',
    'Kachumber salad': 'कचूमर सलाद',
    'Beetroot–carrot salad': 'चुकंदर–गाजर सलाद',
    'Onion–cucumber salad': 'प्याज़–खीरा सलाद',
    'Roasted papad': 'भुना पापड़',
    'Overnight oats with milk & chia': 'दूध और चिया वाले ओवरनाइट ओट्स',
    'Oatmeal with fruit': 'फल वाला ओटमील',
    'Greek yogurt parfait': 'ग्रीक योगर्ट पार्फे',
    'Avocado toast': 'एवोकाडो टोस्ट',
    'Scrambled eggs on toast': 'टोस्ट पर स्क्रैम्बल्ड अंडे',
    'Vegetable omelette': 'वेज ऑमलेट',
    'Shakshuka': 'शक्शुका',
    'Tofu scramble': 'टोफू स्क्रैम्बल',
    'Peanut butter toast': 'पीनट बटर टोस्ट',
    'Smoothie bowl': 'स्मूदी बाउल',
    'Whole-wheat pancakes': 'गेहूं के पैनकेक',
    'Muesli with milk (no sugar)': 'दूध के साथ म्यूसली (बिना चीनी)',
    'Cottage cheese & fruit bowl': 'कॉटेज चीज़ और फल',
    'Breakfast burrito (beans & egg)': 'ब्रेकफास्ट बरिटो (बीन्स और अंडा)',
    'Huevos rancheros': 'ह्यूवोस रैंचेरोस',
    'Congee (rice porridge)': 'कॉन्जी (चावल दलिया)',
    'Chia pudding (almond milk)': 'चिया पुडिंग (बादाम दूध)',
    'Egg muffins': 'एग मफिन',
    'Ful medames': 'फूल मेदामेस',
    'Labneh, veggies & pita': 'लबनेह, सब्ज़ियां और पीटा',
    'Quinoa porridge': 'क्विनोआ दलिया',
    'Tamagoyaki & miso soup': 'तामागोयाकी और मिसो सूप',
    'Grilled chicken breast': 'ग्रिल्ड चिकन ब्रेस्ट',
    'Lemon herb chicken': 'लेमन हर्ब चिकन',
    'Chicken shawarma (no mayo)': 'चिकन शावरमा (बिना मेयो)',
    'Chicken teriyaki': 'चिकन तेरियाकी',
    'Thai basil chicken': 'थाई बेसिल चिकन',
    'Kung pao chicken (less oil)': 'कुंग पाओ चिकन (कम तेल)',
    'Chicken fajita strips': 'चिकन फाहिता',
    'Baked herb fish': 'बेक्ड हर्ब मछली',
    'Grilled salmon': 'ग्रिल्ड सैल्मन',
    'Steamed fish with ginger & soy': 'अदरक–सोया स्टीम्ड मछली',
    'Garlic prawns': 'लहसुन झींगा',
    'Tuna salad (no mayo)': 'टूना सलाद (बिना मेयो)',
    'Vegetable frittata': 'वेज फ्रिटाटा',
    'Grilled tofu': 'ग्रिल्ड टोफू',
    'Mapo tofu (light)': 'मापो टोफू (हल्का)',
    'Tempeh stir-fry': 'टेम्पे स्टर-फ्राई',
    'Baked falafel': 'बेक्ड फलाफल',
    'Black bean chili': 'ब्लैक बीन चिली',
    'Refried beans (no lard)': 'रिफ्राइड बीन्स',
    'Lentil stew': 'दाल स्टू',
    'Chickpea stew': 'छोले स्टू',
    'Grilled halloumi': 'ग्रिल्ड हालूमी',
    'Chicken souvlaki': 'चिकन सुवलाकी',
    'Paneer steak': 'पनीर स्टेक',
    'Hummus': 'हम्मस',
    'Whole-wheat pasta': 'गेहूं का पास्ता',
    'Whole-wheat couscous': 'गेहूं का कूसकूस',
    'Bulgur wheat': 'बुलगर गेहूं (दलिया)',
    'Whole-wheat pita': 'गेहूं की पीटा',
    'Whole-wheat tortilla wrap': 'गेहूं का टॉर्टिला रैप',
    'Corn tortillas': 'मक्का टॉर्टिला',
    'Soba noodles': 'सोबा नूडल्स',
    'Rice noodles': 'राइस नूडल्स',
    'Jasmine rice': 'जैस्मिन राइस',
    'Baked potato': 'बेक्ड आलू',
    'Baked sweet potato': 'बेक्ड शकरकंद',
    'Sourdough bread': 'सावरडो ब्रेड',
    'Multigrain bread': 'मल्टीग्रेन ब्रेड',
    'Mexican rice': 'मैक्सिकन राइस',
    'Pearl barley': 'जौ',
    'Polenta': 'पोलेंटा',
    'Cauliflower rice': 'गोभी राइस',
    'Zucchini noodles': 'ज़ुकीनी नूडल्स',
    'Roasted vegetables': 'भुनी सब्ज़ियां',
    'Steamed broccoli': 'उबली ब्रोकली',
    'Sautéed spinach': 'सॉते पालक',
    'Greek salad (light feta)': 'ग्रीक सलाद',
    'Garden salad with vinaigrette': 'गार्डन सलाद',
    'Tabbouleh': 'तबूले',
    'Fattoush (baked pita)': 'फत्तूश',
    'Stir-fried bok choy': 'स्टर-फ्राई बोक चॉय',
    'Asian stir-fry vegetables': 'एशियन स्टर-फ्राई सब्ज़ियां',
    'Kimchi': 'किमची',
    'Cucumber sesame salad': 'खीरा–तिल सलाद',
    'Pico de gallo': 'पिको दे गायो',
    'Guacamole': 'ग्वाकामोले',
    'Grilled zucchini & peppers': 'ग्रिल्ड ज़ुकीनी और शिमला मिर्च',
    'Ratatouille': 'रैटाटूई',
    'Light coleslaw': 'हल्का कोलस्लॉ',
    'Green beans with almonds': 'बादाम वाली बीन्स',
    'Caprese salad (light)': 'कैप्रेसे सलाद',
    'Baba ganoush': 'बाबा गनूश',
    'Chicken burrito bowl': 'चिकन बरिटो बाउल',
    'Bean burrito bowl': 'बीन बरिटो बाउल',
    'Chicken shawarma bowl': 'चिकन शावरमा बाउल',
    'Falafel wrap': 'फलाफल रैप',
    'Mediterranean chickpea salad': 'मेडिटेरेनियन छोले सलाद',
    'Greek chicken salad': 'ग्रीक चिकन सलाद',
    'Grilled chicken Caesar (light)': 'ग्रिल्ड चिकन सीज़र सलाद',
    'Tuna Niçoise salad': 'टूना नीसवाज़ सलाद',
    'Salmon quinoa bowl': 'सैल्मन क्विनोआ बाउल',
    'Tuna poke bowl': 'टूना पोके बाउल',
    'Tofu poke bowl': 'टोफू पोके बाउल',
    'Vegetable sushi rolls': 'वेज सुशी रोल',
    'Salmon sushi rolls': 'सैल्मन सुशी रोल',
    'Chicken pho': 'चिकन फो',
    'Vegetable ramen (light)': 'वेज रामेन',
    'Pad thai (light)': 'पैड थाई',
    'Thai green curry (chicken) & rice': 'थाई ग्रीन करी (चिकन) और चावल',
    'Thai green curry (tofu) & rice': 'थाई ग्रीन करी (टोफू) और चावल',
    'Chicken stir-fry with brown rice': 'चिकन स्टर-फ्राई और ब्राउन राइस',
    'Egg fried rice (less oil)': 'एग फ्राइड राइस (कम तेल)',
    'Veg hakka noodles (less oil)': 'वेज हक्का नूडल्स (कम तेल)',
    'Bibimbap': 'बिबिमबाप',
    'Japanese chicken curry & rice': 'जापानी चिकन करी और चावल',
    'Whole-wheat pasta primavera': 'पास्ता प्रिमावेरा',
    'Whole-wheat pasta arrabbiata': 'पास्ता अराबियाटा',
    'Chicken tomato pasta (whole-wheat)': 'चिकन टमाटर पास्ता',
    'Grilled fish with mash & greens': 'ग्रिल्ड मछली, मैश और साग',
    'Chicken stew with bread': 'चिकन स्टू और ब्रेड',
    'Lentil shepherd\'s pie': 'दाल शेफर्ड्स पाई',
    'Stuffed bell peppers (quinoa & paneer)': 'भरवां शिमला मिर्च (क्विनोआ और पनीर)',
    'Chicken tacos (corn)': 'चिकन टाको',
    'Bean enchiladas (light)': 'बीन एनचिलाडा',
    'Vegetable quesadilla (whole-wheat)': 'वेज क्वेसाडिया',
    'Moroccan chickpea tagine & couscous': 'मोरक्कन छोले ताजीन और कूसकूस',
    'Mujadara (lentils & rice)': 'मुजद्दरा (दाल और चावल)',
    'Chicken souvlaki plate': 'चिकन सुवलाकी प्लेट',
    'Buddha bowl': 'बुद्धा बाउल',
    'Grilled chicken wrap': 'ग्रिल्ड चिकन रैप',
    'Paneer kathi roll (whole-wheat)': 'पनीर काठी रोल',
    'Egg roll (whole-wheat, less oil)': 'अंडा रोल (कम तेल)',
    'Veg thali (railway / dhaba)': 'वेज थाली (रेलवे / ढाबा)',
    'Dal, 2 tandoori roti & salad (dhaba)': 'दाल, 2 तंदूरी रोटी और सलाद (ढाबा)',
    'Rajma chawal (dhaba)': 'राजमा चावल (ढाबा)',
    'Idli–sambar plate (station)': 'इडली–सांभर प्लेट (स्टेशन)',
    'Grilled sandwich (airport)': 'ग्रिल्ड सैंडविच (एयरपोर्ट)',
    'Hotel salad bar plate with grilled chicken': 'होटल सलाद प्लेट और ग्रिल्ड चिकन',
    'Hotel salad bar plate with paneer': 'होटल सलाद प्लेट और पनीर',
    'Non-veg thali (railway / dhaba)': 'नॉन-वेज थाली (रेलवे / ढाबा)',
    'Jeera–ajwain–saunf water': 'जीरा–अजवाइन–सौंफ पानी',
    'Kadha (herbal decoction)': 'काढ़ा',
    'Lemongrass tea': 'लेमनग्रास चाय',
    'Soaked peanuts': 'भीगी मूंगफली',
    'Soaked munakka': 'भीगे मुनक्के',
    'Ripe jackfruit': 'पका कटहल',
    'Bael fruit': 'बेल फल',
    'Star fruit (kamrakh)': 'कमरख',
    'Mulberries (shahtoot)': 'शहतूत',
    'Fresh apricots': 'ताज़ी खुबानी',
    'Kinnow (tangerine)': 'किन्नू',
    'Fresh coconut pieces': 'ताज़ा नारियल',
    'Dates (khajur)': 'खजूर',
    'Dried figs (anjeer)': 'सूखे अंजीर',
    'Prunes': 'सूखा आलूबुखारा',
    'Raspberries': 'रास्पबेरी',
    'Green apple': 'हरा सेब',
    'Avocado (half)': 'एवोकाडो (आधा)',
    'Mint chaas': 'पुदीना छाछ',
    'Sol kadhi': 'सोल कढ़ी',
    'Neer mor (spiced buttermilk)': 'नीर मोर (मसाला छाछ)',
    'Ragi malt (no sugar)': 'रागी माल्ट (बिना चीनी)',
    'Badam milk (no sugar)': 'बादाम दूध (बिना चीनी)',
    'Sweet lassi (less sugar)': 'मीठी लस्सी (कम चीनी)',
    'Cold coffee (no sugar)': 'कोल्ड कॉफी (बिना चीनी)',
    'Beetroot–carrot juice': 'चुकंदर–गाजर जूस',
    'Lauki (bottle gourd) juice': 'लौकी जूस',
    'Oat milk': 'ओट मिल्क',
    'Chana jor garam': 'चना जोर गरम',
    'Roasted soybeans': 'भुनी सोयाबीन',
    'Baked ragi chips': 'बेक्ड रागी चिप्स',
    'Jowar puffs': 'ज्वार पफ्स',
    'Roasted moong dal namkeen': 'भुनी मूंग दाल नमकीन',
    'Steamed corn on the cob': 'उबला भुट्टा',
    'Boiled chana salad': 'उबले चने का सलाद',
    'Kothimbir vadi (steamed)': 'कोथिंबीर वड़ी (स्टीम्ड)',
    'Patra (steamed)': 'पात्रा (स्टीम्ड)',
    'Khandvi': 'खांडवी',
    'Chana sundal': 'चना सुंडल',
    'Kuzhi paniyaram (less oil)': 'कुझी पनियारम (कम तेल)',
    'Jhal muri (less oil)': 'झाल मुड़ी (कम तेल)',
    'Date & nut energy bar': 'खजूर–मेवा एनर्जी बार',
    'Greek yogurt with berries': 'बेरी वाला ग्रीक योगर्ट',
    'Chicken salad cup': 'चिकन सलाद कप',
    'Tuna cucumber bites': 'टूना–खीरा बाइट्स',
    'Veg rice-paper rolls': 'वेज राइस-पेपर रोल',
    'Chicken satay (grilled)': 'चिकन साटे (ग्रिल्ड)',
    'Salsa with baked tortilla chips': 'साल्सा और बेक्ड टॉर्टिला चिप्स',
    'Bean dip with veg sticks': 'बीन डिप और सब्ज़ी स्टिक्स',
    'Small vegetable upma': 'वेज उपमा (छोटा)',
    'Dal shorba': 'दाल शोरबा',
    'Mulligatawny soup': 'मुलिगटॉनी सूप',
    'Carrot–ginger soup': 'गाजर–अदरक सूप',
    'Beetroot soup': 'चुकंदर सूप',
    'Cabbage soup': 'पत्ता गोभी सूप',
    'Chicken & vegetable soup': 'चिकन और सब्ज़ी सूप',
    'Egg drop soup': 'एग ड्रॉप सूप',
    'Hot & sour soup (veg)': 'हॉट एंड सॉर सूप (वेज)',
    'Gazpacho': 'गैज़पाचो',
    'Rava dosa (less oil)': 'रवा डोसा (कम तेल)',
    'Set dosa': 'सेट डोसा',
    'Akki roti': 'अक्की रोटी',
    'Jowar upma': 'ज्वार उपमा',
    'Palak paratha': 'पालक पराठा',
    'Dal paratha': 'दाल पराठा',
    'Methi muthia (steamed)': 'मेथी मुठिया (स्टीम्ड)',
    'Kanchipuram idli': 'कांचीपुरम इडली',
    'Masala egg toast': 'मसाला अंडा टोस्ट',
    'Keema paratha (lean)': 'कीमा पराठा',
    'Akuri (Parsi scrambled eggs)': 'अकूरी (पारसी अंडा भुर्जी)',
    'Aval upma (Kerala poha)': 'अवल उपमा (केरल पोहा)',
    'Oats porridge with milk': 'दूध वाला ओट्स दलिया',
    'Quinoa upma': 'क्विनोआ उपमा',
    'Foxtail millet pongal': 'कंगनी पोंगल',
    'Protein pancakes': 'प्रोटीन पैनकेक',
    'Berry yogurt smoothie': 'बेरी योगर्ट स्मूदी',
    'Whole-wheat French toast (light)': 'फ्रेंच टोस्ट (हल्का)',
    'Baked chilaquiles': 'बेक्ड चिलाकिलेस',
    'Menemen (Turkish eggs)': 'मेनेमेन (तुर्की अंडे)',
    'Hummus & veggie toast': 'हम्मस और सब्ज़ी टोस्ट',
    'Hotel breakfast plate (eggs, toast, fruit)': 'होटल नाश्ता प्लेट (अंडे, टोस्ट, फल)',
    'Ragi mudde': 'रागी मुद्दे',
    'Barnyard (sama) millet rice': 'सामा के चावल',
    'Little millet rice': 'कुटकी (लिटिल मिलेट)',
    'Red rice': 'लाल चावल',
    'Coconut rice': 'नारियल चावल',
    'Tomato rice': 'टमाटर चावल',
    'Matar pulao': 'मटर पुलाव',
    'Mutton biryani': 'मटन बिरयानी',
    'Fish biryani': 'मछली बिरयानी',
    'Prawn pulao': 'झींगा पुलाव',
    'Brown rice khichdi': 'ब्राउन राइस खिचड़ी',
    'Gujarati masala khichdi': 'गुजराती मसाला खिचड़ी',
    'Lemon quinoa': 'लेमन क्विनोआ',
    'Nachni (ragi) bhakri': 'नाचनी भाकरी',
    'Dal dhokli': 'दाल ढोकली',
    'Rumali roti': 'रूमाली रोटी',
    'Palak roti': 'पालक रोटी',
    'Methi roti': 'मेथी रोटी',
    'Oats roti': 'ओट्स रोटी',
    'Luchi': 'लूची',
    'Toor dal (plain)': 'अरहर दाल (सादी)',
    'Andhra pappu': 'आंध्र पप्पू',
    'Tomato pappu': 'टमाटर पप्पू',
    'Mor kuzhambu': 'मोर कुझम्बु',
    'Vatha kuzhambu': 'वथा कुझम्बु',
    'Moth dal': 'मोठ दाल',
    'Varan (Maharashtrian dal)': 'वरण',
    'Aamti': 'आमटी',
    'Sabut masoor dal': 'साबुत मसूर दाल',
    'Dry chana masala': 'सूखा चना मसाला',
    'Mixed sprouts curry': 'मिक्स स्प्राउट्स करी',
    'Paneer do pyaza': 'पनीर दो प्याज़ा',
    'Shahi paneer (light)': 'शाही पनीर (हल्का)',
    'Tofu tikka masala': 'टोफू टिक्का मसाला',
    'Grilled soya chaap': 'ग्रिल्ड सोया चाप',
    'Egg white bhurji': 'अंडे की सफेदी भुर्जी',
    'Chicken saagwala': 'चिकन साग',
    'Chicken do pyaza': 'चिकन दो प्याज़ा',
    'Air-fried chicken 65': 'एयर-फ्राइड चिकन 65',
    'Kadai chicken': 'कड़ाही चिकन',
    'Pepper chicken (dry)': 'पेपर चिकन (सूखा)',
    'Andhra chicken curry': 'आंध्र चिकन करी',
    'Chicken seekh kebab (grilled)': 'चिकन सीख कबाब',
    'Mutton keema (lean)': 'मटन कीमा',
    'Rogan josh (lean)': 'रोगन जोश',
    'Meen moilee': 'मीन मोइली',
    'Air-fried Amritsari fish': 'एयर-फ्राइड अमृतसरी मछली',
    'Doi maach': 'दोई माछ',
    'Kerala prawn curry': 'केरल झींगा करी',
    'Chicken tikka masala (light)': 'चिकन टिक्का मसाला (हल्का)',
    'Aloo baingan': 'आलू बैंगन',
    'Aloo methi': 'आलू मेथी',
    'Gatte ki sabzi (steamed gatte)': 'गट्टे की सब्ज़ी',
    'Snake gourd kootu': 'चिचिंडा कूटू',
    'Ash gourd curry': 'पेठा करी',
    'Vendakkai poriyal': 'भिंडी पोरियल',
    'Gutti vankaya (light)': 'गुट्टी वंकाया (भरवां बैंगन)',
    'Mushroom pepper fry': 'मशरूम पेपर फ्राई',
    'Baby corn capsicum': 'बेबी कॉर्न शिमला मिर्च',
    'Broccoli stir-fry (Indian)': 'ब्रोकली स्टर-फ्राई',
    'French beans foogath': 'फ्रेंच बीन्स फुगाथ',
    'Lau ghonto': 'लौ घोंटो (लौकी)',
    'Air-fried begun bhaja': 'एयर-फ्राइड बेगुन भाजा',
    'Aloo posto (light)': 'आलू पोस्तो',
    'Dum aloo (light)': 'दम आलू (हल्का)',
    'Chawli leaves bhaji': 'चवली पत्ते की भाजी',
    'Bathua sabzi': 'बथुए की सब्ज़ी',
    'Suran (yam) sabzi': 'सूरन (जिमीकंद) की सब्ज़ी',
    'Raw papaya sabzi': 'कच्चे पपीते की सब्ज़ी',
    'Pineapple raita': 'अनानास रायता',
    'Beetroot raita': 'चुकंदर रायता',
    'Carrot–cabbage salad': 'गाजर–पत्ता गोभी सलाद',
    'Koshimbir': 'कोशिंबीर',
    'Sprouts kosambari': 'स्प्राउट्स कोसंबरी',
    'Low-fat curd': 'कम वसा दही',
    'Grilled prawns': 'ग्रिल्ड झींगा',
    'Chickpea patties': 'छोले की टिक्की',
    'Tofu teriyaki': 'टोफू तेरियाकी',
    'Moroccan spiced chicken': 'मोरक्कन मसाला चिकन',
    'Lentil patties': 'दाल की टिक्की',
    'Brown rice noodles': 'ब्राउन राइस नूडल्स',
    'Wild rice': 'वाइल्ड राइस',
    'Farro': 'फ़ारो',
    'Herb roasted potatoes': 'हर्ब भुने आलू',
    'Whole-wheat garlic bread (light)': 'गार्लिक ब्रेड (हल्की)',
    'Roasted cauliflower': 'भुनी गोभी',
    'Roasted beetroot salad': 'भुना चुकंदर सलाद',
    'Kale salad': 'केल सलाद',
    'Mushroom stir-fry': 'मशरूम स्टर-फ्राई',
    'Sautéed green beans': 'सॉते हरी बीन्स',
    'Quinoa salad': 'क्विनोआ सलाद',
    'Corn & bean salad': 'कॉर्न और बीन सलाद',
    'Tzatziki': 'त्ज़ात्ज़िकी',
    'Light vegetable lasagna': 'वेज लज़ानिया (हल्की)',
    'Chicken fried rice (less oil)': 'चिकन फ्राइड राइस (कम तेल)',
    'Teriyaki salmon bowl': 'तेरियाकी सैल्मन बाउल',
    'Korean tofu stew': 'कोरियन टोफू स्टू',
    'Vietnamese chicken salad': 'वियतनामी चिकन सलाद',
    'Green papaya salad (som tam)': 'कच्चे पपीते का सलाद (सोम टैम)',
    'Pasta e fagioli': 'पास्ता ए फाजोली',
    'Chicken quinoa salad': 'चिकन क्विनोआ सलाद',
    'Mexican quinoa bowl': 'मैक्सिकन क्विनोआ बाउल',
    'Hummus chicken wrap': 'हम्मस चिकन रैप',
    'Thai red curry (tofu, light) & rice': 'थाई रेड करी (टोफू) और चावल',
    'Light mushroom risotto': 'मशरूम रिसोट्टो (हल्का)',
    'Grilled chicken with sweet potato': 'ग्रिल्ड चिकन और शकरकंद',
    'Baked fish tacos': 'बेक्ड फिश टाको',
    'Lentil bolognese pasta': 'दाल बोलोनीज़ पास्ता',
    'Thepla & curd (packed)': 'थेपला और दही (पैक)',
    'Airport salad bowl': 'एयरपोर्ट सलाद बाउल',
    'Veg sub (6-inch, whole-wheat)': 'वेज सब (6 इंच)',
    'Chicken sub (6-inch, whole-wheat)': 'चिकन सब (6 इंच)',
    'Dhaba paneer & roti': 'ढाबा पनीर और रोटी',
    'Dhaba chicken & roti': 'ढाबा चिकन और रोटी',
    'Khichdi & curd (dhaba)': 'खिचड़ी और दही (ढाबा)',
  };

  if (typeof module !== 'undefined' && module.exports) module.exports = HI;
  else root.FOOD_HI = HI;
})(typeof window !== 'undefined' ? window : globalThis);
