/*
 * Meal library for the diet chart generator.
 *
 * Each meal option is a complete, ready-to-serve plate for one meal slot.
 * Nutrition values are approximate, per base serving (as listed in `items`),
 * and are scaled up or down by the planner to hit each slot's calorie target.
 *
 * Fields
 *   slot       early | breakfast | midmorning | lunch | evening | dinner | bedtime
 *   diet       vegan | veg | egg | nonveg   (the least restrictive diet that allows it)
 *   cuisine    in (Indian) | gl (global)
 *   n          [kcal, protein g, carbs g, fat g]
 *   items      [name, quantity, unit, fixed?]  fixed items are not scaled
 *   allergens  gluten, dairy, nuts, soy, egg, fish
 *   flags      hgi   high glycaemic load (avoided for diabetes, PCOS, fatty liver)
 *              hna   high sodium (avoided for high BP, kidney disease)
 *              hk    high potassium (avoided for kidney disease)
 *              fried / hsf  fried or high in saturated fat (avoided for heart, fatty liver)
 */
(function (root) {
  function M(slot, diet, cuisine, name, n, items, allergens, flags) {
    return {
      slot, diet, cuisine, name,
      kcal: n[0], p: n[1], c: n[2], f: n[3],
      items,
      allergens: allergens ? allergens.split(' ') : [],
      flags: flags ? flags.split(' ') : [],
    };
  }

  const MEALS = [
    // ── Early morning ───────────────────────────────────────────────
    M('early', 'vegan', 'in', 'Lemon water & soaked almonds', [45, 1.5, 2, 3.5],
      [['Warm lemon water', 1, 'glass', true], ['Soaked almonds', 5, 'pc', true]], 'nuts'),
    M('early', 'vegan', 'in', 'Methi water & walnuts', [60, 1.5, 2, 5],
      [['Soaked methi (fenugreek) seed water', 1, 'glass', true], ['Walnut halves', 2, 'pc', true]], 'nuts'),
    M('early', 'vegan', 'in', 'Jeera water & pumpkin seeds', [40, 2, 2, 3],
      [['Warm jeera (cumin) water', 1, 'glass', true], ['Pumpkin seeds', 1, 'tsp', true]]),
    M('early', 'vegan', 'in', 'Ajwain water & flaxseed', [40, 1.5, 2, 3],
      [['Warm ajwain (carom) water', 1, 'glass', true], ['Roasted flaxseed', 1, 'tsp', true]]),
    M('early', 'vegan', 'in', 'Dhaniya water & almonds', [45, 1.5, 2, 3.5],
      [['Soaked dhaniya (coriander seed) water', 1, 'glass', true], ['Soaked almonds', 5, 'pc', true]], 'nuts'),
    M('early', 'vegan', 'in', 'Tulsi–ginger tea', [30, 1, 3, 1.5],
      [['Tulsi–ginger herbal tea (no sugar)', 1, 'cup', true], ['Sunflower seeds', 1, 'tsp', true]]),
    M('early', 'vegan', 'in', 'Amla juice & walnuts', [55, 1.5, 4, 4],
      [['Amla juice diluted in warm water', 1, 'glass', true], ['Walnut halves', 2, 'pc', true]], 'nuts'),
    M('early', 'vegan', 'gl', 'Green tea & chia', [35, 1, 2, 2],
      [['Green tea (no sugar)', 1, 'cup', true], ['Soaked chia seeds', 1, 'tsp', true]]),
    M('early', 'vegan', 'in', 'Soaked raisins water', [60, 0.5, 15, 0],
      [['Water of soaked kishmish (raisins)', 1, 'glass', true], ['Soaked kishmish', 6, 'pc', true]], '', 'hgi hk'),

    // ── Breakfast ───────────────────────────────────────────────────
    M('breakfast', 'vegan', 'in', 'Vegetable poha', [300, 7, 50, 8],
      [['Vegetable poha', 1.5, 'cup'], ['Roasted peanuts', 1, 'tbsp'], ['Lemon wedge', 1, 'pc', true]], 'nuts'),
    M('breakfast', 'vegan', 'in', 'Moong dal chilla', [280, 16, 36, 8],
      [['Moong dal chilla', 2, 'pc'], ['Mint–coriander chutney', 2, 'tbsp', true]]),
    M('breakfast', 'vegan', 'in', 'Vegetable upma', [290, 8, 45, 9],
      [['Vegetable rava upma', 1.5, 'cup'], ['Coconut chutney', 1, 'tbsp', true]], 'gluten'),
    M('breakfast', 'vegan', 'in', 'Idli sambar', [330, 11, 58, 6],
      [['Idli', 3, 'pc'], ['Sambar', 1, 'katori'], ['Coconut chutney', 2, 'tbsp', true]], '', 'hgi'),
    M('breakfast', 'vegan', 'in', 'Plain dosa & sambar', [340, 9, 56, 9],
      [['Plain dosa (less oil)', 2, 'pc'], ['Sambar', 1, 'katori'], ['Tomato chutney', 2, 'tbsp', true]], '', 'hgi'),
    M('breakfast', 'vegan', 'in', 'Masala dosa', [380, 9, 60, 12],
      [['Masala dosa (less oil)', 1, 'pc'], ['Sambar', 1, 'katori'], ['Coconut chutney', 2, 'tbsp', true]], '', 'hgi hk'),
    M('breakfast', 'vegan', 'in', 'Vegetable uttapam', [320, 10, 52, 8],
      [['Onion–tomato uttapam', 2, 'pc'], ['Sambar', 1, 'katori']], '', 'hgi'),
    M('breakfast', 'vegan', 'in', 'Pesarattu', [300, 16, 42, 7],
      [['Pesarattu (green moong dosa)', 2, 'pc'], ['Ginger chutney', 2, 'tbsp', true]]),
    M('breakfast', 'vegan', 'in', 'Ragi dosa with sambar', [300, 9, 52, 6],
      [['Ragi dosa', 2, 'pc'], ['Sambar', 1, 'katori']]),
    M('breakfast', 'vegan', 'in', 'Appam with vegetable stew', [340, 7, 56, 10],
      [['Appam', 2, 'pc'], ['Kerala vegetable stew', 1, 'katori']], '', 'hgi'),
    M('breakfast', 'vegan', 'in', 'Puttu & kadala curry', [360, 13, 60, 8],
      [['Rice puttu', 1, 'cup'], ['Kadala (black chana) curry', 1, 'katori']], '', 'hgi'),
    M('breakfast', 'veg', 'in', 'Rava idli', [300, 10, 46, 8],
      [['Rava idli', 3, 'pc'], ['Coconut chutney', 2, 'tbsp', true]], 'gluten dairy'),
    M('breakfast', 'veg', 'in', 'Besan chilla with curd', [300, 15, 30, 12],
      [['Besan (gram flour) chilla', 2, 'pc'], ['Curd', 0.5, 'katori']], 'dairy'),
    M('breakfast', 'vegan', 'in', 'Oats chilla', [270, 11, 38, 8],
      [['Oats & vegetable chilla', 2, 'pc'], ['Mint chutney', 2, 'tbsp', true]]),
    M('breakfast', 'vegan', 'in', 'Masala oats', [260, 9, 40, 7],
      [['Vegetable masala oats', 1.5, 'cup']]),
    M('breakfast', 'veg', 'in', 'Paneer paratha with curd', [380, 17, 42, 16],
      [['Paneer-stuffed multigrain paratha', 1, 'pc'], ['Curd', 0.5, 'katori']], 'gluten dairy'),
    M('breakfast', 'veg', 'in', 'Aloo paratha with curd', [400, 10, 56, 15],
      [['Aloo paratha (less ghee)', 1, 'pc'], ['Curd', 0.5, 'katori']], 'gluten dairy', 'hgi hk'),
    M('breakfast', 'veg', 'in', 'Gobhi paratha with curd', [350, 11, 46, 13],
      [['Gobhi-stuffed multigrain paratha', 1, 'pc'], ['Curd', 0.5, 'katori']], 'gluten dairy'),
    M('breakfast', 'veg', 'in', 'Methi thepla with curd', [320, 11, 42, 12],
      [['Methi thepla', 2, 'pc'], ['Curd', 0.5, 'katori']], 'gluten dairy'),
    M('breakfast', 'vegan', 'in', 'Khaman dhokla', [280, 12, 42, 7],
      [['Steamed khaman dhokla', 4, 'pc'], ['Green chutney', 2, 'tbsp', true]], '', 'hna'),
    M('breakfast', 'veg', 'in', 'Thalipeeth with curd', [320, 12, 44, 10],
      [['Multigrain thalipeeth', 2, 'pc'], ['Curd', 0.5, 'katori']], 'gluten dairy'),
    M('breakfast', 'vegan', 'in', 'Sprouts usal & toast', [310, 16, 46, 7],
      [['Sprouts usal (misal, no farsan)', 1, 'katori'], ['Multigrain bread', 1, 'slice']], 'gluten'),
    M('breakfast', 'veg', 'in', 'Sabudana khichdi', [350, 5, 60, 10],
      [['Sabudana khichdi', 1, 'cup'], ['Curd', 0.5, 'katori']], 'nuts dairy', 'hgi hk'),
    M('breakfast', 'veg', 'in', 'Dalia porridge', [300, 11, 48, 7],
      [['Broken-wheat dalia cooked in milk', 1.5, 'cup'], ['Chopped nuts', 1, 'tsp', true]], 'gluten dairy nuts'),
    M('breakfast', 'vegan', 'in', 'Namkeen vegetable dalia', [280, 9, 48, 6],
      [['Vegetable dalia (savoury)', 1.5, 'cup']], 'gluten'),
    M('breakfast', 'veg', 'in', 'Ragi porridge', [260, 10, 40, 7],
      [['Ragi porridge with milk (no sugar)', 1, 'bowl'], ['Almonds', 5, 'pc', true]], 'dairy nuts'),
    M('breakfast', 'vegan', 'in', 'Sprouts chaat & toast', [280, 15, 44, 4],
      [['Moong sprouts chaat', 1.5, 'cup'], ['Multigrain toast', 1, 'slice']], 'gluten'),
    M('breakfast', 'veg', 'in', 'Paneer bhurji & toast', [360, 20, 30, 18],
      [['Paneer bhurji', 1, 'katori'], ['Multigrain toast', 2, 'slice']], 'dairy gluten'),
    M('breakfast', 'veg', 'in', 'Vegetable sandwich & milk', [330, 14, 46, 10],
      [['Grilled vegetable sandwich (multigrain)', 1, 'pc'], ['Toned milk (no sugar)', 1, 'glass']], 'gluten dairy'),
    M('breakfast', 'egg', 'in', 'Masala omelette & toast', [360, 20, 30, 17],
      [['Masala omelette (2 eggs)', 1, 'pc'], ['Multigrain toast', 2, 'slice']], 'egg gluten'),
    M('breakfast', 'egg', 'in', 'Egg bhurji & phulka', [300, 16, 18, 17],
      [['Egg bhurji (2 eggs)', 1, 'katori'], ['Phulka', 1, 'pc']], 'egg gluten'),
    M('breakfast', 'egg', 'in', 'Boiled eggs & toast', [300, 17, 28, 12],
      [['Boiled eggs', 2, 'pc'], ['Multigrain toast', 2, 'slice'], ['Tomato–cucumber slices', 1, 'cup', true]], 'egg gluten'),
    M('breakfast', 'egg', 'in', 'Egg dosa', [340, 16, 42, 12],
      [['Egg dosa (1 egg each)', 2, 'pc'], ['Tomato chutney', 2, 'tbsp', true]], 'egg', 'hgi'),
    M('breakfast', 'nonveg', 'in', 'Chicken keema & phulka', [360, 28, 30, 13],
      [['Chicken keema (lean)', 1, 'katori'], ['Phulka', 2, 'pc']], 'gluten'),
    M('breakfast', 'nonveg', 'gl', 'Chicken sandwich', [340, 26, 34, 10],
      [['Grilled chicken & vegetable sandwich (multigrain)', 1, 'pc']], 'gluten'),
    M('breakfast', 'veg', 'gl', 'Overnight oats', [320, 13, 46, 9],
      [['Overnight oats with milk & chia', 1, 'cup'], ['Berries or chopped fruit', 0.5, 'cup']], 'dairy'),
    M('breakfast', 'veg', 'gl', 'Greek yogurt parfait', [280, 18, 34, 8],
      [['Greek yogurt', 150, 'g'], ['Chopped fruit', 0.5, 'cup'], ['Mixed seeds', 1, 'tbsp']], 'dairy'),
    M('breakfast', 'vegan', 'gl', 'Peanut butter banana toast', [340, 12, 46, 13],
      [['Whole-wheat toast', 2, 'slice'], ['Peanut butter', 1, 'tbsp'], ['Banana', 0.5, 'pc']], 'gluten nuts', 'hk'),
    M('breakfast', 'vegan', 'gl', 'Tofu scramble & toast', [300, 20, 22, 14],
      [['Tofu scramble with vegetables', 1, 'cup'], ['Multigrain toast', 1, 'slice']], 'soy gluten'),
    M('breakfast', 'egg', 'gl', 'Avocado toast with egg', [350, 15, 32, 18],
      [['Multigrain toast', 2, 'slice'], ['Mashed avocado', 0.5, 'pc'], ['Boiled egg', 1, 'pc']], 'egg gluten', 'hk'),

    // ── Mid-morning ─────────────────────────────────────────────────
    M('midmorning', 'vegan', 'in', 'Seasonal fruit', [90, 1, 22, 0],
      [['Seasonal fruit (apple / pear / orange)', 1, 'bowl']]),
    M('midmorning', 'vegan', 'in', 'Guava', [70, 2.5, 14, 1],
      [['Guava', 1, 'pc']]),
    M('midmorning', 'vegan', 'in', 'Orange / mosambi', [70, 1.5, 16, 0],
      [['Orange or mosambi', 1, 'pc']], '', 'hk'),
    M('midmorning', 'vegan', 'in', 'Pomegranate', [80, 1.5, 18, 1],
      [['Pomegranate seeds', 0.5, 'cup']]),
    M('midmorning', 'vegan', 'in', 'Watermelon', [60, 1, 15, 0],
      [['Watermelon', 1.5, 'cup']], '', 'hgi'),
    M('midmorning', 'vegan', 'in', 'Banana', [100, 1, 25, 0],
      [['Banana (small)', 1, 'pc']], '', 'hgi hk'),
    M('midmorning', 'vegan', 'in', 'Papaya & pumpkin seeds', [110, 4, 16, 4],
      [['Papaya', 1, 'bowl'], ['Pumpkin seeds', 1, 'tbsp']]),
    M('midmorning', 'veg', 'in', 'Chaas & roasted chana', [110, 6, 12, 3],
      [['Chaas (buttermilk)', 1, 'glass'], ['Roasted chana', 2, 'tbsp']], 'dairy'),
    M('midmorning', 'veg', 'in', 'Salted lassi', [110, 6, 9, 5],
      [['Salted lassi (no sugar)', 1, 'glass']], 'dairy'),
    M('midmorning', 'vegan', 'in', 'Coconut water & almonds', [80, 2, 9, 4],
      [['Tender coconut water', 1, 'glass'], ['Almonds', 5, 'pc']], 'nuts', 'hk'),
    M('midmorning', 'vegan', 'in', 'Nimbu pani & almonds', [60, 2, 4, 4],
      [['Nimbu pani (no sugar)', 1, 'glass', true], ['Almonds', 5, 'pc']], 'nuts'),
    M('midmorning', 'vegan', 'in', 'Sattu drink', [120, 7, 20, 2],
      [['Sattu drink with lemon & jeera', 1, 'glass']]),
    M('midmorning', 'vegan', 'in', 'Roasted makhana', [100, 3, 18, 1],
      [['Roasted makhana (fox nuts)', 1, 'cup']]),
    M('midmorning', 'vegan', 'in', 'Moong sprouts', [80, 6, 13, 0.5],
      [['Steamed moong sprouts with lemon', 0.5, 'cup']]),
    M('midmorning', 'vegan', 'in', 'Cucumber–carrot salad', [50, 1.5, 10, 0.5],
      [['Cucumber & carrot salad with lemon', 1, 'bowl']]),
    M('midmorning', 'veg', 'in', 'Paneer cubes', [140, 9, 3, 10],
      [['Paneer cubes with chaat masala', 50, 'g']], 'dairy', 'hsf'),
    M('midmorning', 'vegan', 'gl', 'Apple with peanut butter', [190, 4, 26, 8],
      [['Apple', 1, 'pc'], ['Peanut butter', 1, 'tbsp']], 'nuts'),
    M('midmorning', 'veg', 'gl', 'Greek yogurt cup', [100, 10, 6, 3],
      [['Plain Greek yogurt', 100, 'g']], 'dairy'),
    M('midmorning', 'egg', 'gl', 'Boiled egg & cucumber', [85, 6.5, 3, 5],
      [['Boiled egg', 1, 'pc'], ['Cucumber slices', 1, 'cup', true]], 'egg'),

    // ── Lunch ───────────────────────────────────────────────────────
    M('lunch', 'veg', 'in', 'Dal, sabzi & phulka thali', [520, 20, 75, 14],
      [['Phulka', 2, 'pc'], ['Dal', 1, 'katori'], ['Mixed vegetable sabzi', 1, 'katori'], ['Curd', 0.5, 'katori'], ['Green salad', 1, 'bowl', true]], 'gluten dairy'),
    M('lunch', 'veg', 'in', 'Gujarati thali', [530, 18, 82, 13],
      [['Rotli', 2, 'pc'], ['Gujarati dal', 1, 'katori'], ['Seasonal shaak', 1, 'katori'], ['Steamed rice', 0.5, 'cup'], ['Chaas (buttermilk)', 1, 'glass']], 'gluten dairy'),
    M('lunch', 'vegan', 'in', 'Rajma with brown rice', [480, 17, 82, 8],
      [['Brown rice', 1, 'cup'], ['Rajma', 1, 'katori'], ['Green salad', 1, 'bowl', true]]),
    M('lunch', 'vegan', 'in', 'Rajma chawal', [500, 16, 88, 8],
      [['Steamed rice', 1, 'cup'], ['Rajma', 1, 'katori'], ['Onion–cucumber salad', 1, 'bowl', true]], '', 'hgi'),
    M('lunch', 'veg', 'in', 'Chana masala with jowar roti', [510, 19, 78, 12],
      [['Jowar roti', 2, 'pc'], ['Chana masala', 1, 'katori'], ['Cucumber raita', 0.5, 'katori']], 'dairy'),
    M('lunch', 'vegan', 'in', 'Chole & phulka', [500, 18, 76, 13],
      [['Chole', 1, 'katori'], ['Phulka', 2, 'pc'], ['Onion–cucumber salad', 1, 'bowl', true]], 'gluten'),
    M('lunch', 'veg', 'in', 'Kadhi chawal', [480, 14, 78, 12],
      [['Kadhi (no pakoda)', 1, 'katori'], ['Steamed rice', 1, 'cup'], ['Mixed vegetable sabzi', 0.5, 'katori']], 'dairy', 'hgi'),
    M('lunch', 'veg', 'in', 'Bhindi, dal & phulka', [490, 18, 70, 14],
      [['Bhindi sabzi', 1, 'katori'], ['Dal', 1, 'katori'], ['Phulka', 2, 'pc'], ['Curd', 0.5, 'katori']], 'gluten dairy'),
    M('lunch', 'vegan', 'in', 'Aloo gobhi, dal & phulka', [500, 16, 78, 13],
      [['Aloo gobhi', 1, 'katori'], ['Dal', 1, 'katori'], ['Phulka', 2, 'pc']], 'gluten', 'hk'),
    M('lunch', 'vegan', 'in', 'Baingan bharta & bajra roti', [480, 16, 72, 14],
      [['Baingan bharta', 1, 'katori'], ['Bajra roti', 2, 'pc'], ['Moong dal', 1, 'katori']]),
    M('lunch', 'veg', 'in', 'Mixed veg & missi roti', [490, 19, 68, 15],
      [['Mixed vegetable curry', 1, 'katori'], ['Besan missi roti', 2, 'pc'], ['Raita', 0.5, 'katori']], 'gluten dairy'),
    M('lunch', 'veg', 'in', 'Sarson ka saag & makki roti', [520, 16, 70, 18],
      [['Sarson ka saag (less ghee)', 1, 'katori'], ['Makki roti', 2, 'pc'], ['Chaas (buttermilk)', 1, 'glass']], 'dairy', 'hk'),
    M('lunch', 'vegan', 'in', 'Chana dal & lauki with phulka', [470, 18, 70, 11],
      [['Chana dal with lauki', 1, 'katori'], ['Phulka', 2, 'pc'], ['Green salad', 1, 'bowl', true]], 'gluten'),
    M('lunch', 'vegan', 'in', 'Lobia curry & brown rice', [470, 18, 78, 8],
      [['Lobia (black-eyed peas) curry', 1, 'katori'], ['Brown rice', 1, 'cup'], ['Green salad', 1, 'bowl', true]]),
    M('lunch', 'veg', 'in', 'Veg pulao with dal & raita', [500, 17, 80, 12],
      [['Vegetable pulao', 1, 'cup'], ['Dal', 1, 'katori'], ['Raita', 0.5, 'katori']], 'dairy', 'hgi'),
    M('lunch', 'veg', 'in', 'Quinoa khichdi', [450, 17, 66, 12],
      [['Vegetable quinoa khichdi', 1.5, 'cup'], ['Curd', 0.5, 'katori']], 'dairy'),
    M('lunch', 'vegan', 'in', 'Moong dal khichdi', [440, 16, 70, 9],
      [['Moong dal khichdi', 1.5, 'cup'], ['Green salad', 1, 'bowl', true]]),
    M('lunch', 'veg', 'in', 'Palak paneer & phulka', [540, 24, 48, 27],
      [['Palak paneer', 1, 'katori'], ['Phulka', 2, 'pc'], ['Green salad', 1, 'bowl', true]], 'dairy gluten', 'hsf'),
    M('lunch', 'veg', 'in', 'Paneer bhurji & phulka', [520, 24, 46, 26],
      [['Paneer bhurji', 1, 'katori'], ['Phulka', 2, 'pc'], ['Green salad', 1, 'bowl', true]], 'dairy gluten', 'hsf'),
    M('lunch', 'veg', 'in', 'Sambar rice & poriyal', [490, 15, 82, 10],
      [['Steamed rice', 1, 'cup'], ['Sambar', 1, 'katori'], ['Beans poriyal', 1, 'katori'], ['Chaas (buttermilk)', 1, 'glass']], 'dairy', 'hgi'),
    M('lunch', 'veg', 'in', 'Rasam rice & curd', [470, 14, 80, 10],
      [['Steamed rice', 1, 'cup'], ['Rasam', 1, 'katori'], ['Cabbage poriyal', 1, 'katori'], ['Curd', 0.5, 'katori']], 'dairy', 'hgi'),
    M('lunch', 'veg', 'in', 'Curd rice & poriyal', [460, 13, 74, 12],
      [['Curd rice', 1.5, 'cup'], ['Carrot–beans poriyal', 1, 'katori']], 'dairy', 'hgi'),
    M('lunch', 'vegan', 'in', 'Avial with matta rice', [480, 12, 80, 13],
      [['Kerala matta (red) rice', 1, 'cup'], ['Avial', 1, 'katori'], ['Sambar', 1, 'katori']]),
    M('lunch', 'vegan', 'in', 'Bisi bele bath', [460, 14, 76, 11],
      [['Bisi bele bath', 1.5, 'cup'], ['Cucumber salad', 1, 'bowl', true]], '', 'hgi'),
    M('lunch', 'vegan', 'in', 'Jowar bhakri & pithla', [480, 18, 72, 13],
      [['Jowar bhakri', 2, 'pc'], ['Pithla (besan curry)', 1, 'katori'], ['Green salad', 1, 'bowl', true]]),
    M('lunch', 'vegan', 'in', 'Bengali dal-bhaat & shukto', [480, 15, 82, 9],
      [['Steamed rice', 1, 'cup'], ['Masoor dal', 1, 'katori'], ['Shukto (mixed vegetables)', 1, 'katori']], '', 'hgi'),
    M('lunch', 'vegan', 'in', 'Soya chunk curry & phulka', [480, 30, 54, 14],
      [['Soya chunk curry', 1, 'katori'], ['Phulka', 2, 'pc'], ['Green salad', 1, 'bowl', true]], 'soy gluten'),
    M('lunch', 'egg', 'in', 'Egg curry & phulka', [480, 22, 44, 22],
      [['Egg curry (2 eggs)', 1, 'katori'], ['Phulka', 2, 'pc'], ['Green salad', 1, 'bowl', true]], 'egg gluten'),
    M('lunch', 'egg', 'in', 'Egg curry & brown rice', [490, 20, 60, 18],
      [['Egg curry (2 eggs)', 1, 'katori'], ['Brown rice', 1, 'cup'], ['Green salad', 1, 'bowl', true]], 'egg'),
    M('lunch', 'nonveg', 'in', 'Chicken curry & phulka', [520, 36, 44, 20],
      [['Chicken curry (100 g chicken)', 1, 'katori'], ['Phulka', 2, 'pc'], ['Green salad', 1, 'bowl', true]], 'gluten'),
    M('lunch', 'nonveg', 'in', 'Chicken biryani & raita', [560, 30, 70, 17],
      [['Chicken biryani', 1.5, 'cup'], ['Raita', 0.5, 'katori'], ['Onion–cucumber salad', 1, 'bowl', true]], 'dairy', 'hgi'),
    M('lunch', 'nonveg', 'in', 'Fish curry & rice', [500, 32, 54, 15],
      [['Fish curry (120 g fish)', 1, 'katori'], ['Steamed rice', 1, 'cup'], ['Green salad', 1, 'bowl', true]], 'fish', 'hgi'),
    M('lunch', 'nonveg', 'in', 'Bengali maacher jhol & rice', [510, 30, 60, 15],
      [['Maacher jhol (fish curry)', 1, 'katori'], ['Steamed rice', 1, 'cup'], ['Masoor dal', 0.5, 'katori']], 'fish', 'hgi'),
    M('lunch', 'nonveg', 'in', 'Prawn curry & rice', [480, 28, 58, 13],
      [['Prawn curry', 1, 'katori'], ['Steamed rice', 1, 'cup'], ['Green salad', 1, 'bowl', true]], 'fish', 'hgi'),
    M('lunch', 'nonveg', 'in', 'Lean mutton curry & phulka', [540, 32, 44, 25],
      [['Mutton curry (80 g lean mutton)', 1, 'katori'], ['Phulka', 2, 'pc'], ['Green salad', 1, 'bowl', true]], 'gluten', 'hsf'),
    M('lunch', 'nonveg', 'in', 'Grilled chicken & jowar roti', [480, 38, 50, 12],
      [['Tandoori chicken (skinless)', 120, 'g'], ['Jowar roti', 2, 'pc'], ['Mint raita', 0.5, 'katori']], 'dairy'),
    M('lunch', 'nonveg', 'gl', 'Grilled chicken quinoa bowl', [480, 38, 45, 15],
      [['Grilled chicken breast', 100, 'g'], ['Cooked quinoa', 1, 'cup'], ['Roasted vegetables', 1, 'cup']]),
    M('lunch', 'vegan', 'gl', 'Chickpea buddha bowl', [500, 19, 66, 18],
      [['Roasted chickpeas & vegetables', 1.5, 'cup'], ['Brown rice', 0.5, 'cup'], ['Hummus', 2, 'tbsp']]),
    M('lunch', 'vegan', 'gl', 'Tofu stir-fry & brown rice', [480, 24, 58, 16],
      [['Tofu & vegetable stir-fry', 1.5, 'cup'], ['Brown rice', 1, 'cup']], 'soy', 'hna'),
    M('lunch', 'veg', 'gl', 'Whole-wheat veg pasta', [520, 24, 66, 17],
      [['Whole-wheat pasta with vegetables & paneer', 1.5, 'cup']], 'gluten dairy'),

    // ── Evening snack ───────────────────────────────────────────────
    M('evening', 'veg', 'in', 'Masala tea & khakhra', [150, 5, 22, 4],
      [['Masala tea (less sugar)', 1, 'cup', true], ['Multigrain khakhra', 2, 'pc']], 'dairy gluten'),
    M('evening', 'vegan', 'in', 'Sprouts salad', [130, 9, 20, 1],
      [['Mixed sprouts salad', 1, 'cup']]),
    M('evening', 'vegan', 'in', 'Roasted chana & green tea', [120, 6, 18, 2],
      [['Roasted chana', 30, 'g'], ['Green tea', 1, 'cup', true]]),
    M('evening', 'vegan', 'in', 'Vegetable soup', [90, 3, 14, 2],
      [['Clear vegetable soup', 1, 'bowl']]),
    M('evening', 'vegan', 'in', 'Tomato soup', [90, 2.5, 14, 2.5],
      [['Homemade tomato soup (no cream)', 1, 'bowl']], '', 'hk'),
    M('evening', 'vegan', 'in', 'Dal soup', [120, 7, 18, 2],
      [['Moong dal soup', 1, 'bowl']]),
    M('evening', 'vegan', 'in', 'Khaman dhokla', [140, 6, 21, 3.5],
      [['Steamed khaman dhokla', 2, 'pc'], ['Green chutney', 1, 'tbsp', true]], '', 'hna'),
    M('evening', 'vegan', 'in', 'Murmura chivda', [130, 3, 22, 4],
      [['Roasted murmura chivda (no sev)', 1, 'cup']], 'nuts', 'hgi'),
    M('evening', 'vegan', 'in', 'Corn chaat', [130, 4, 24, 2],
      [['Sweet corn chaat', 0.5, 'cup']], '', 'hgi'),
    M('evening', 'vegan', 'in', 'Fruit chaat', [100, 1.5, 24, 0.5],
      [['Fruit chaat (seasonal fruit)', 1, 'bowl']]),
    M('evening', 'vegan', 'in', 'Moong chilla', [140, 8, 18, 4],
      [['Moong dal chilla', 1, 'pc'], ['Green chutney', 1, 'tbsp', true]]),
    M('evening', 'vegan', 'in', 'Idli & chutney', [150, 5, 28, 2],
      [['Idli', 2, 'pc'], ['Tomato chutney', 1, 'tbsp', true]], '', 'hgi'),
    M('evening', 'vegan', 'in', 'Sprouts bhel', [150, 6, 26, 3],
      [['Sprouts bhel (no sev)', 1, 'cup']]),
    M('evening', 'vegan', 'in', 'Baked sprouts tikki', [160, 8, 22, 4],
      [['Baked sprouts & oats tikki', 2, 'pc'], ['Mint chutney', 1, 'tbsp', true]]),
    M('evening', 'vegan', 'in', 'Peanut chaat', [170, 7, 9, 12],
      [['Boiled peanut chaat', 0.5, 'cup']], 'nuts'),
    M('evening', 'vegan', 'in', 'Makhana & green tea', [100, 3, 18, 1],
      [['Roasted makhana', 1, 'cup'], ['Green tea', 1, 'cup', true]]),
    M('evening', 'veg', 'in', 'Paneer tikka', [200, 14, 6, 13],
      [['Paneer tikka', 80, 'g'], ['Mint chutney', 1, 'tbsp', true]], 'dairy', 'hsf'),
    M('evening', 'veg', 'in', 'Vegetable sandwich', [180, 7, 28, 5],
      [['Multigrain vegetable sandwich', 1, 'pc']], 'gluten dairy'),
    M('evening', 'egg', 'in', 'Egg chaat', [160, 12, 6, 10],
      [['Boiled egg chaat with onion & tomato', 2, 'pc']], 'egg'),
    M('evening', 'nonveg', 'in', 'Chicken tikka', [180, 26, 4, 7],
      [['Chicken tikka', 100, 'g'], ['Onion & lemon salad', 1, 'bowl', true]]),
    M('evening', 'nonveg', 'in', 'Fish tikka', [170, 24, 3, 7],
      [['Fish tikka', 100, 'g'], ['Mint chutney', 1, 'tbsp', true]], 'fish'),
    M('evening', 'vegan', 'gl', 'Hummus & veggie sticks', [140, 5, 14, 7],
      [['Hummus', 2, 'tbsp'], ['Carrot & cucumber sticks', 1, 'cup', true]]),
    M('evening', 'egg', 'gl', 'Boiled eggs', [150, 12, 1, 10],
      [['Boiled eggs with pepper', 2, 'pc']], 'egg'),
    M('evening', 'vegan', 'gl', 'Trail mix', [140, 4, 10, 10],
      [['Trail mix (nuts & seeds)', 25, 'g']], 'nuts'),

    // ── Dinner ──────────────────────────────────────────────────────
    M('dinner', 'vegan', 'in', 'Lauki sabzi, dal & phulka', [420, 16, 62, 11],
      [['Phulka', 2, 'pc'], ['Lauki (bottle gourd) sabzi', 1, 'katori'], ['Moong dal', 1, 'katori']], 'gluten'),
    M('dinner', 'vegan', 'in', 'Tinda, chana dal & phulka', [420, 17, 62, 11],
      [['Tinda sabzi', 1, 'katori'], ['Chana dal', 1, 'katori'], ['Phulka', 2, 'pc']], 'gluten'),
    M('dinner', 'vegan', 'in', 'Masoor dal, bhindi & phulka', [430, 17, 62, 12],
      [['Masoor dal', 1, 'katori'], ['Bhindi sabzi', 1, 'katori'], ['Phulka', 2, 'pc']], 'gluten'),
    M('dinner', 'vegan', 'in', 'Dal palak & jowar roti', [420, 18, 64, 10],
      [['Dal palak', 1, 'katori'], ['Jowar roti', 2, 'pc'], ['Green salad', 1, 'bowl', true]], '', 'hk'),
    M('dinner', 'vegan', 'in', 'Mixed veg & ragi roti', [410, 13, 66, 11],
      [['Mixed vegetable curry', 1, 'katori'], ['Ragi roti', 2, 'pc'], ['Moong dal', 0.5, 'katori']]),
    M('dinner', 'veg', 'in', 'Grilled paneer & veggies', [420, 24, 26, 24],
      [['Grilled paneer', 100, 'g'], ['Sautéed vegetables', 1, 'cup'], ['Phulka', 1, 'pc']], 'dairy gluten', 'hsf'),
    M('dinner', 'veg', 'in', 'Paneer tikka salad & roti', [430, 24, 34, 22],
      [['Paneer tikka', 80, 'g'], ['Green salad', 1, 'bowl'], ['Multigrain roti', 1, 'pc']], 'dairy gluten', 'hsf'),
    M('dinner', 'veg', 'in', 'Vegetable dalia khichdi', [380, 14, 60, 9],
      [['Vegetable dalia khichdi', 1.5, 'cup'], ['Curd', 0.5, 'katori']], 'gluten dairy'),
    M('dinner', 'veg', 'in', 'Oats khichdi & kadhi', [400, 15, 58, 11],
      [['Oats & moong dal khichdi', 1.5, 'cup'], ['Kadhi (no pakoda)', 0.5, 'katori']], 'dairy'),
    M('dinner', 'vegan', 'in', 'Bajra khichdi', [410, 14, 64, 11],
      [['Bajra & moong khichdi', 1.5, 'cup'], ['Green salad', 1, 'bowl', true]]),
    M('dinner', 'vegan', 'in', 'Millet roti & mixed dal', [430, 17, 66, 10],
      [['Bajra / jowar roti', 2, 'pc'], ['Mixed dal', 1, 'katori'], ['Green salad', 1, 'bowl', true]]),
    M('dinner', 'vegan', 'in', 'Soup & moong chilla', [360, 17, 48, 10],
      [['Mixed vegetable soup', 1, 'bowl'], ['Moong dal chilla', 2, 'pc']]),
    M('dinner', 'vegan', 'in', 'Idli sambar dinner', [340, 11, 60, 5],
      [['Idli', 3, 'pc'], ['Vegetable sambar', 1, 'katori']], '', 'hgi'),
    M('dinner', 'vegan', 'in', 'Palak dal & brown rice', [400, 17, 62, 9],
      [['Palak dal', 1, 'katori'], ['Brown rice', 0.5, 'cup'], ['Green salad', 1, 'bowl', true]], '', 'hk'),
    M('dinner', 'veg', 'in', 'Methi thepla & curd', [360, 12, 46, 13],
      [['Methi thepla', 2, 'pc'], ['Curd', 1, 'katori']], 'gluten dairy'),
    M('dinner', 'vegan', 'in', 'Tofu bhurji & phulka', [400, 22, 40, 17],
      [['Tofu bhurji', 1, 'katori'], ['Phulka', 2, 'pc']], 'soy gluten'),
    M('dinner', 'vegan', 'in', 'Soya keema & phulka', [410, 28, 44, 12],
      [['Soya keema with peas', 1, 'katori'], ['Phulka', 2, 'pc']], 'soy gluten'),
    M('dinner', 'egg', 'in', 'Veg omelette & soup', [380, 20, 30, 18],
      [['Vegetable omelette (2 eggs)', 1, 'pc'], ['Phulka', 1, 'pc'], ['Clear soup', 1, 'bowl']], 'egg gluten'),
    M('dinner', 'egg', 'in', 'Egg curry & phulka', [400, 19, 38, 18],
      [['Egg curry (2 eggs)', 1, 'katori'], ['Phulka', 1, 'pc'], ['Green salad', 1, 'bowl', true]], 'egg gluten'),
    M('dinner', 'nonveg', 'in', 'Chicken vegetable stew', [420, 32, 36, 15],
      [['Chicken & vegetable stew (100 g chicken)', 1, 'bowl'], ['Multigrain roti', 1, 'pc']], 'gluten'),
    M('dinner', 'nonveg', 'in', 'Chicken soup & salad', [360, 32, 24, 13],
      [['Chicken clear soup', 1, 'bowl'], ['Grilled chicken salad', 1, 'bowl']]),
    M('dinner', 'nonveg', 'in', 'Chicken tikka & roti', [420, 36, 34, 14],
      [['Chicken tikka', 120, 'g'], ['Multigrain roti', 1, 'pc'], ['Green salad', 1, 'bowl', true]], 'gluten'),
    M('dinner', 'nonveg', 'in', 'Fish curry & roti', [400, 30, 32, 16],
      [['Fish curry (120 g fish)', 1, 'katori'], ['Phulka', 1, 'pc'], ['Sautéed vegetables', 1, 'cup']], 'fish gluten'),
    M('dinner', 'nonveg', 'gl', 'Grilled fish & brown rice', [430, 36, 34, 15],
      [['Grilled fish', 150, 'g'], ['Sautéed vegetables', 1, 'cup'], ['Brown rice', 0.5, 'cup']], 'fish'),
    M('dinner', 'vegan', 'gl', 'Lentil soup & quinoa salad', [410, 19, 60, 11],
      [['Lentil soup', 1, 'bowl'], ['Quinoa vegetable salad', 1, 'cup']]),
    M('dinner', 'veg', 'gl', 'Stuffed bell peppers', [420, 22, 44, 17],
      [['Bell peppers stuffed with paneer & quinoa', 2, 'pc']], 'dairy'),

    // ── Bedtime ─────────────────────────────────────────────────────
    M('bedtime', 'veg', 'in', 'Haldi doodh', [110, 8, 12, 3],
      [['Low-fat turmeric milk (no sugar)', 1, 'cup', true]], 'dairy'),
    M('bedtime', 'veg', 'in', 'Elaichi milk', [110, 8, 12, 3],
      [['Warm toned milk with elaichi (no sugar)', 1, 'cup', true]], 'dairy'),
    M('bedtime', 'vegan', 'in', 'Dalchini tea & almonds', [50, 1.5, 2, 4],
      [['Dalchini (cinnamon) tea', 1, 'cup', true], ['Almonds', 4, 'pc', true]], 'nuts'),
    M('bedtime', 'vegan', 'gl', 'Warm soy milk', [100, 7, 8, 4],
      [['Warm soy milk with cinnamon', 1, 'cup', true]], 'soy'),
    M('bedtime', 'vegan', 'gl', 'Chamomile tea & walnuts', [55, 1, 1, 5],
      [['Chamomile tea', 1, 'cup', true], ['Walnut halves', 2, 'pc', true]], 'nuts'),
  ];

  MEALS.forEach((m, i) => { m.id = i; });

  if (typeof module !== 'undefined' && module.exports) module.exports = MEALS;
  else root.MEALS = MEALS;
})(typeof window !== 'undefined' ? window : globalThis);
