/*
 * A recipe for every food: ingredients in grams for ONE serving (the food's
 * listed quantity) plus method steps. applyRecipes() calculates each food's
 * kcal, protein, carbs and fat from these ingredients (ingredients.js), and
 * derives allergens and the diet type (veg / egg / non-veg) from them too.
 *
 * Format: 'Food name': 'method | ingredient grams, ingredient grams, …'
 */
(function (root) {
  const R = {
    // Early morning
    'Warm lemon water': 'water|lemon 10',
    'Jeera (cumin) water': 'water|spice 2',
    'Methi (fenugreek) seed water': 'water|methiseed 3',
    'Ajwain (carom) water': 'water|spice 2',
    'Dhaniya (coriander seed) water': 'water|spice 2',
    'Saunf (fennel) water': 'water|spice 2.5',
    'Dalchini (cinnamon) water': 'water|spice 1.5',
    'Amla juice in warm water': 'water|amlajuice 30',
    'Aloe vera juice in water': 'water|aloe 30',
    'Tulsi–ginger herbal tea': 'tea|ginger 5, spice 1',
    'Green tea (no sugar)': 'tea|greentea 200',
    'Wheatgrass juice': 'blend|wheatgrass 30',
    'Lemon–honey water': 'water|lemon 10, honey 12',
    'Soaked almonds': 'soak|almond 6',
    'Walnut halves': 'soak|walnut 8',
    'Soaked kishmish (raisins)': 'soak|raisin 8',
    'Soaked chia seeds': 'soak|chia 4',
    'Roasted flaxseed': 'roast|flax 3.5',
    'Pumpkin seeds': 'raw|pumpkinseed 3',
    'Sunflower seeds': 'raw|sunflower 3',
    'Soaked methi seeds': 'soak|methiseed 4',
    'Jeera–ajwain–saunf water': 'water|spice 3',
    'Kadha (herbal decoction)': 'tea|ginger 5, spice 2',
    'Lemongrass tea': 'tea|herbal 200',
    'Soaked peanuts': 'soak|peanut 7',
    'Soaked munakka': 'soak|raisin 10',

    // Bedtime
    'Haldi doodh (low-fat turmeric milk)': 'milk|milk 150, spice 1',
    'Warm toned milk with elaichi': 'milk|milk 170, spice 0.5',
    'Warm skimmed milk': 'milk|skim 200',
    'Unsweetened almond milk': 'ready|almondmilk 240',
    'Warm soy milk with cinnamon': 'milk|soymilk 200, spice 0.5',
    'Chamomile tea': 'tea|herbal 200',
    'Dalchini (cinnamon) tea': 'tea|spice 1.5',

    // Fruits
    'Apple': 'raw|apple 150',
    'Pear': 'raw|pear 150',
    'Guava': 'raw|guava 100',
    'Orange': 'raw|orange 140',
    'Mosambi (sweet lime)': 'raw|mosambi 130',
    'Banana (small)': 'raw|banana 100',
    'Papaya': 'raw|papaya 150',
    'Watermelon': 'raw|watermelon 230',
    'Muskmelon': 'raw|muskmelon 160',
    'Pomegranate seeds': 'raw|pomegranate 87',
    'Pineapple': 'raw|pineapple 165',
    'Mango slices': 'raw|mango 83',
    'Grapes': 'raw|grapes 150',
    'Chikoo (sapota)': 'raw|chikoo 100',
    'Kiwi': 'raw|kiwi 150',
    'Strawberries': 'raw|strawberry 150',
    'Blueberries': 'raw|blueberry 75',
    'Jamun': 'raw|jamun 100',
    'Plums': 'raw|plum 130',
    'Peach': 'raw|peach 150',
    'Custard apple (sitaphal)': 'raw|custardapple 100',
    'Fresh figs': 'raw|fig 100',
    'Litchi': 'raw|litchi 100',
    'Cherries': 'raw|cherry 140',
    'Dragon fruit': 'raw|dragonfruit 130',
    'Mixed fruit bowl': 'raw|apple 50, papaya 50, orange 50, pomegranate 20',
    'Amla (Indian gooseberry)': 'raw|amla 70',
    'Ripe jackfruit': 'raw|jackfruitr 165',
    'Bael fruit': 'raw|bael 70',
    'Star fruit (kamrakh)': 'raw|starfruit 90',
    'Mulberries (shahtoot)': 'raw|mulberry 140',
    'Fresh apricots': 'raw|apricot 105',
    'Kinnow (tangerine)': 'raw|kinnow 110',
    'Fresh coconut pieces': 'raw|coconut 30',
    'Dates (khajur)': 'raw|dates 16',
    'Dried figs (anjeer)': 'raw|dfig 25',
    'Prunes': 'raw|prune 25',
    'Raspberries': 'raw|raspberry 125',
    'Green apple': 'raw|apple 150',
    'Avocado (half)': 'raw|avocado 75',

    // Drinks
    'Chaas (buttermilk)': 'mixdrink|curd 75, spice 0.5',
    'Salted lassi': 'blend|curd 200, spice 0.5',
    'Nimbu pani (no sugar)': 'mixdrink|lemon 15, spice 0.5',
    'Tender coconut water': 'ready|coconutwater 240',
    'Sattu drink': 'mixdrink|sattu 25, lemon 5, spice 1',
    'Masala tea (less sugar)': 'tea|milk 80, tea 100, sugar 3, spice 0.5',
    'Black coffee': 'tea|coffee 200',
    'Filter coffee (less sugar)': 'tea|milk 100, coffee 50, sugar 4',
    'Toned milk': 'milk|milk 200',
    'Soy milk': 'milk|soymilk 220',
    'Jaljeera': 'mixdrink|lemon 10, spice 3',
    'Kokum sharbat (no sugar)': 'mixdrink|kokum 20, spice 0.5',
    'Aam panna (less sugar)': 'blend|rawmango 60, sugar 5, spice 1',
    'Fresh vegetable juice': 'blend|carrot 60, beet 40, spinach 30, lemon 5',
    'Whey protein shake (in water)': 'mixdrink|whey 30',
    'Plant protein shake': 'mixdrink|plantp 32',
    'Banana–milk smoothie (no sugar)': 'blend|banana 100, milk 150',
    'Spinach–apple green smoothie': 'blend|spinach 40, apple 150, lemon 5',
    'Mint chaas': 'mixdrink|curd 75, mint 5',
    'Sol kadhi': 'mixdrink|coconutmilk 40, kokum 10',
    'Neer mor (spiced buttermilk)': 'mixdrink|curd 65, ginger 2',
    'Ragi malt (no sugar)': 'porridge|ragi 25, milk 100',
    'Badam milk (no sugar)': 'milk|milk 200, almond 10',
    'Sweet lassi (less sugar)': 'blend|curd 200, sugar 12',
    'Cold coffee (no sugar)': 'blend|milk 200, coffee 5',
    'Beetroot–carrot juice': 'blend|beet 100, carrot 60, lemon 5',
    'Lauki (bottle gourd) juice': 'blend|lauki 150, mint 3, lemon 5',
    'Oat milk': 'ready|oatmilk 240',

    // Snacks
    'Roasted chana': 'ready|roastchana 30',
    'Roasted makhana (fox nuts)': 'roast|makhana 25, ghee 1, spice 0.5',
    'Moong sprouts chaat': 'chaat|sprouts 120, onion 15, tomato 20, lemon 5, spice 1',
    'Mixed sprouts salad': 'chaat|msprouts 110, cucumber 20, onion 10, lemon 5',
    'Kala chana chaat': 'chaat|kalachana 45, onion 15, tomato 20, lemon 5, spice 1',
    'Roasted peanuts': 'roast|peanut 20',
    'Almonds': 'raw|almond 10',
    'Mixed nuts': 'raw|mixednuts 20',
    'Roasted pumpkin seeds': 'roast|pumpkinseed 8',
    'Trail mix (nuts & seeds)': 'raw|trailmix 25',
    'Roasted murmura chivda': 'roast|murmura 25, peanut 5, oil 2, spice 1',
    'Sprouts bhel (no sev)': 'chaat|murmura 15, sprouts 60, onion 15, tomato 15, lemon 5, spice 1',
    'Multigrain khakhra': 'ready|khakhra 28',
    'Khaman dhokla': 'steamed|besan 30, curd 10, oil 2, sugar 1.5, spice 0.5',
    'Moong dal dhokla': 'steamed|moong 35, curd 10, oil 2',
    'Idli': 'idli|rice 30, urad 10',
    'Paneer tikka': 'tikka|paneer 70, curd 15, capsicum 20, onion 15, oil 2, spice 2',
    'Paneer cubes with chaat masala': 'raw|paneer 50, spice 1',
    'Tofu tikka': 'tikka|tofu 100, curd 10, oil 1, spice 2',
    'Soya chunks chaat': 'chaat|soya 25, onion 15, tomato 20, lemon 5, spice 1',
    'Sweet corn chaat': 'chaat|corn 80, butter 2, lemon 5, spice 1',
    'Fruit chaat': 'chaat|apple 50, banana 30, papaya 50, pomegranate 20, spice 1',
    'Vegetable sandwich (multigrain)': 'sandwich|mgbread 55, cucumber 30, tomato 30, onion 10, coriander 10, butter 3',
    'Paneer sandwich (multigrain)': 'sandwich|mgbread 55, paneer 30, capsicum 20, onion 10, butter 3',
    'Egg sandwich (multigrain)': 'sandwich|mgbread 55, egg 50, onion 10, tomato 20, oil 2',
    'Chicken sandwich (multigrain)': 'sandwich|mgbread 55, chicken 60, greens 20, curd 10',
    'Boiled eggs': 'egg|egg 100',
    'Boiled egg whites': 'egg|eggw 99',
    'Egg chaat': 'chaat|egg 100, onion 15, tomato 20, lemon 5, spice 1',
    'Chicken tikka (snack)': 'tikka|chicken 100, curd 15, oil 2, lemon 5, spice 2',
    'Fish tikka (snack)': 'tikka|fish 110, curd 10, oil 3, lemon 5, spice 2',
    'Grilled chicken strips': 'grill|chicken 90, oil 1, spice 1',
    'Greek yogurt': 'raw|greek 100',
    'Hung curd dip with veg sticks': 'raita|curd 120, carrot 50, cucumber 50, spice 1',
    'Hummus with veggie sticks': 'raw|hummus 50, carrot 50, cucumber 50',
    'Baked sweet potato chaat': 'chaat|spotato 100, lemon 5, spice 1',
    'Vegetable poha (small)': 'poha|poha 30, oil 3, onion 15, peas 10, spice 1',
    'Protein bar': 'ready|proteinbar 55',
    'Peanut chikki': 'ready|peanut 15, jaggery 12',
    'Dry fruit laddoo (no sugar)': 'laddoo|dates 20, almond 5, cashew 5, walnut 3',
    'Sattu laddoo': 'laddoo|sattu 22, jaggery 8, ghee 3',
    'Rice cakes': 'ready|ricecake 18',
    'Air-popped popcorn': 'roast|popcorn 16',
    'Cucumber & carrot sticks': 'raw|cucumber 100, carrot 60',
    'Sprouts tikki (baked)': 'baked|sprouts 80, oats 10, besan 8, oil 3, spice 1',
    'Oats tikki (baked)': 'baked|oats 25, carrot 20, peas 20, besan 5, oil 3, spice 1',
    'Moong dal chilla (small)': 'chilla|moong 30, onion 10, oil 2, spice 0.5',
    'Besan chilla (small)': 'chilla|besan 25, onion 10, tomato 10, oil 3',
    'Edamame (steamed)': 'raw|edamame 155',
    'Cottage cheese with pepper': 'raw|cottage 100',
    'Chana jor garam': 'ready|roastchana 30',
    'Roasted soybeans': 'ready|soybean 30',
    'Baked ragi chips': 'ready|ragichips 30',
    'Jowar puffs': 'ready|jowarpuff 22',
    'Roasted moong dal namkeen': 'ready|moongnamkeen 30',
    'Steamed corn on the cob': 'raw|corn 100',
    'Boiled chana salad': 'chaat|kalachana 40, cucumber 30, tomato 30, onion 15, lemon 5',
    'Kothimbir vadi (steamed)': 'steamed|besan 30, coriander 30, oil 4',
    'Patra (steamed)': 'steamed|besan 25, spinach 30, tamarind 3, jaggery 3, oil 4',
    'Khandvi': 'steamed|besan 25, curd 40, oil 3',
    'Chana sundal': 'south|kchana 40, coconut 8, oil 2',
    'Kuzhi paniyaram (less oil)': 'dosa|rice 35, urad 12, onion 15, oil 4',
    'Jhal muri (less oil)': 'chaat|murmura 25, peanut 8, onion 15, oil 3',
    'Date & nut energy bar': 'laddoo|dates 25, almond 7, cashew 5',
    'Greek yogurt with berries': 'raw|greek 130, berries 60',
    'Chicken salad cup': 'salad|chicken 110, cucumber 40, curd 20, greens 20',
    'Tuna cucumber bites': 'salad|tuna 90, cucumber 80, lemon 5',
    'Veg rice-paper rolls': 'wrap|ricepaper 20, mixveg 60, ricenoodle 15',
    'Chicken satay (grilled)': 'grill|chicken 130, peanut 8, soysauce 4',
    'Salsa with baked tortilla chips': 'ready|ctortilla 45, tomato 60, onion 10',
    'Bean dip with veg sticks': 'salad|bbeans 70, carrot 50, cucumber 50',
    'Small vegetable upma': 'upma|rava 30, mixveg 20, onion 10, oil 3',

    // Soups
    'Clear vegetable soup': 'soup|mixveg 120, oil 1, spice 0.5',
    'Tomato soup (no cream)': 'soup|tomato 250, onion 20, oil 2, spice 1',
    'Moong dal soup': 'soup|moong 25, onion 10, oil 1, spice 1',
    'Lauki soup': 'soup|lauki 200, oil 1, spice 1',
    'Palak soup': 'soup|spinach 150, onion 15, milk 30, oil 1',
    'Sweet corn vegetable soup': 'soup|corn 60, mixveg 50, cornflour 5, oil 1',
    'Mushroom soup (no cream)': 'soup|mushroom 120, onion 20, milk 30, oil 2',
    'Chicken clear soup': 'soup|chicken 50, mixveg 60, oil 1',
    'Rasam': 'soup|toor 8, tomato 60, tamarind 5, oil 1.5, spice 1.5',
    'Veg manchow soup (less oil)': 'soup|mixveg 100, cornflour 6, soysauce 5, oil 2',
    'Minestrone soup': 'soup|mixveg 100, pasta 12, tomato 60, bbeans 20, olive 2',
    'Lentil soup': 'soup|masoor 30, carrot 30, onion 20, tomato 30, olive 2',
    'Miso soup': 'soup|miso 15, tofu 30, greens 10',
    'Tom yum soup (veg)': 'soup|mushroom 60, tomato 40, lemon 10, oil 1, spice 2',
    'Chicken tom yum': 'soup|chicken 60, mushroom 40, tomato 30, lemon 10, kimchi 5',
    'Pumpkin soup': 'soup|pumpkin 200, onion 20, oil 3',
    'Broccoli–almond soup': 'soup|broccoli 150, almond 6, onion 20, oil 2',
    'Chicken sweet corn soup': 'soup|chicken 40, corn 50, cornflour 6, egg 15',
    'Dal shorba': 'soup|toor 25, tomato 30, ghee 2',
    'Mulligatawny soup': 'soup|masoor 25, apple 20, coconutmilk 20, onion 20',
    'Carrot–ginger soup': 'soup|carrot 150, ginger 5, oil 2',
    'Beetroot soup': 'soup|beet 130, onion 20, oil 2',
    'Cabbage soup': 'soup|cabbage 120, tomato 40, onion 20',
    'Chicken & vegetable soup': 'soup|chicken 70, mixveg 80, oil 1',
    'Egg drop soup': 'soup|egg 40, cornflour 5, soysauce 3',
    'Hot & sour soup (veg)': 'soup|mixveg 80, tofu 30, cornflour 6, soysauce 6, oil 2',
    'Gazpacho': 'blend|tomato 200, cucumber 60, capsicum 30, olive 4',

    // Indian breakfast
    'Idli (breakfast)': 'idli|rice 45, urad 15',
    'Rava idli': 'idli|rava 45, curd 30, oil 3',
    'Ragi idli': 'idli|ragi 30, urad 12, rice 10',
    'Oats idli': 'idli|oats 35, rava 8, curd 30, oil 2',
    'Plain dosa (less oil)': 'dosa|rice 45, urad 15, oil 6',
    'Masala dosa (less oil)': 'dosa|rice 30, urad 10, potato 80, onion 20, oil 6',
    'Ragi dosa': 'dosa|ragi 30, rice 15, urad 8, oil 5',
    'Oats dosa': 'dosa|oats 30, rava 15, curd 20, oil 5',
    'Neer dosa': 'dosa|rice 40, coconut 5, oil 3',
    'Pesarattu (green moong dosa)': 'dosa|wmoong 50, rice 8, ginger 3, oil 5',
    'Adai (mixed dal dosa)': 'dosa|rice 25, chanadal 15, toor 10, urad 8, oil 6',
    'Onion–tomato uttapam': 'dosa|rice 45, urad 15, onion 30, tomato 30, oil 6',
    'Appam': 'dosa|rice 45, coconut 10, oil 2',
    'Idiyappam': 'steamed|rice 45, coconut 5',
    'Puttu': 'steamed|rice 50, coconut 15',
    'Ven pongal': 'khichdi|rice 40, moong 15, ghee 6, spice 1',
    'Rava upma': 'upma|rava 40, mixveg 30, onion 15, oil 5, spice 1',
    'Vegetable oats upma': 'upma|oats 35, mixveg 40, onion 15, oil 4',
    'Semiya (vermicelli) upma': 'upma|semiya 45, mixveg 30, onion 15, oil 4',
    'Vegetable poha': 'poha|poha 45, onion 20, peas 15, peanut 5, lemon 5, oil 5',
    'Sprouts poha': 'poha|poha 40, sprouts 40, onion 15, oil 4',
    'Sabudana khichdi': 'poha|sabudana 60, peanut 15, potato 40, oil 6',
    'Multigrain thalipeeth': 'roti|mgatta 50, onion 20, oil 5',
    'Misal (no farsan)': 'curry|moth 40, onion 20, tomato 20, oil 5, spice 2',
    'Khaman dhokla (breakfast)': 'steamed|besan 60, curd 20, oil 4, sugar 3',
    'Methi thepla (breakfast)': 'paratha|atta 45, besan 10, methi 20, curd 10, oil 6',
    'Handvo': 'steamed|rice 30, chanadal 15, toor 10, lauki 40, curd 20, oil 6, sesame 2',
    'Moong dal chilla': 'chilla|moong 60, onion 15, oil 4, spice 1',
    'Besan chilla': 'chilla|besan 50, onion 15, tomato 15, oil 5',
    'Oats chilla': 'chilla|oats 45, besan 10, onion 15, oil 4',
    'Paneer-stuffed besan chilla': 'chilla|besan 45, paneer 40, onion 10, oil 5',
    'Aloo paratha (less ghee)': 'paratha|atta 50, potato 70, ghee 4, spice 1',
    'Gobhi paratha': 'paratha|atta 50, cauli 60, oil 4',
    'Paneer paratha': 'paratha|atta 50, paneer 35, oil 4',
    'Methi paratha': 'paratha|atta 50, methi 25, oil 4',
    'Mooli paratha': 'paratha|atta 50, radish 60, oil 4',
    'Missi roti (breakfast)': 'roti|atta 35, besan 30, onion 10, oil 3',
    'Savoury vegetable dalia': 'upma|dalia 40, mixveg 50, oil 3',
    'Dalia porridge with milk': 'porridge|dalia 35, milk 150, almond 3',
    'Ragi porridge with milk': 'porridge|ragi 30, milk 150',
    'Ghugni': 'curry|kalachana 45, onion 20, tomato 20, oil 4',
    'Sattu paratha': 'paratha|atta 45, sattu 25, onion 10, oil 4',
    'Chuda–dahi (poha with curd)': 'raw|poha 50, curd 100',
    'Baked litti': 'baked|atta 50, sattu 25, ghee 3',
    'Masala omelette': 'egg|egg 100, onion 20, tomato 20, oil 4',
    'Egg bhurji': 'egg|egg 100, onion 25, tomato 25, oil 5',
    'Egg white omelette': 'egg|eggw 100, onion 15, oil 1',
    'Anda paratha': 'paratha|atta 50, egg 50, oil 5',
    'Egg dosa': 'dosa|rice 45, urad 15, egg 100, oil 5',
    'Chicken keema': 'meat|ckeema 100, onion 30, tomato 30, oil 5',
    'Tofu bhurji': 'egg|tofu 110, onion 20, tomato 20, oil 3',
    'Paneer bhurji': 'egg|paneer 80, onion 20, tomato 20, oil 3',
    'Instant oats cup': 'ready|oats 45, mixveg 20, oil 1',
    'Instant poha cup': 'ready|poha 50, peanut 4, oil 3',
    'Instant upma cup': 'ready|rava 50, oil 4',
    'Rava dosa (less oil)': 'dosa|rava 35, rice 20, oil 7',
    'Set dosa': 'dosa|rice 60, urad 15, oil 4',
    'Akki roti': 'roti|rice 60, onion 15, coconut 5, oil 4',
    'Jowar upma': 'upma|jowar 45, mixveg 30, oil 4',
    'Palak paratha': 'paratha|atta 50, spinach 40, oil 4',
    'Dal paratha': 'paratha|atta 45, moong 15, oil 5',
    'Methi muthia (steamed)': 'steamed|atta 30, besan 15, methi 25, oil 4',
    'Kanchipuram idli': 'idli|rice 40, urad 15, curd 20, ghee 3, cashew 3',
    'Masala egg toast': 'egg|egg 100, wwbread 60, onion 10, oil 4',
    'Keema paratha (lean)': 'paratha|atta 50, ckeema 50, oil 5',
    'Akuri (Parsi scrambled eggs)': 'egg|egg 100, onion 25, tomato 20, milk 20, butter 4',
    'Aval upma (Kerala poha)': 'poha|poha 50, coconut 5, onion 10, oil 4',
    'Oats porridge with milk': 'porridge|oats 40, milk 150',
    'Quinoa upma': 'upma|quinoa 45, mixveg 40, oil 4',
    'Foxtail millet pongal': 'khichdi|foxtail 40, moong 15, ghee 5',

    // Breakfast sides
    'Sambar': 'dal|toor 20, mixveg 60, tamarind 3, oil 3, spice 2',
    'Coconut chutney': 'chutney|coconut 18, roastchana 4, oil 1',
    'Mint–coriander chutney': 'chutney|coriander 15, mint 10, lemon 5, chilli 3',
    'Tomato chutney': 'chutney|tomato 50, onion 10, oil 2',
    'Peanut chutney': 'chutney|peanut 12, spice 1',
    'Ginger chutney': 'chutney|ginger 10, tamarind 3, jaggery 3, oil 1',
    'Curd': 'raw|curd 75',
    'Multigrain toast': 'ready|mgbread 28',
    'Boiled egg': 'egg|egg 50',

    // Grains
    'Phulka': 'roti|atta 40',
    'Chapati (light ghee)': 'roti|atta 45, ghee 4',
    'Multigrain roti': 'roti|mgatta 50',
    'Jowar roti': 'roti|jowar 55',
    'Bajra roti': 'roti|bajra 55, ghee 2',
    'Ragi roti': 'roti|ragi 55, oil 1',
    'Makki roti': 'roti|makki 55, ghee 3',
    'Besan missi roti': 'roti|atta 35, besan 30, onion 10, oil 3',
    'Methi thepla': 'paratha|atta 45, besan 10, methi 20, curd 10, oil 6',
    'Gujarati rotli': 'roti|atta 42',
    'Jowar bhakri': 'roti|jowar 60',
    'Tandoori roti': 'roti|atta 42',
    'Naan': 'roti|maida 70, curd 10, butter 3',
    'Plain paratha': 'paratha|atta 50, oil 4',
    'Steamed rice': 'rice|rice 55',
    'Brown rice': 'rice|brice 58',
    'Jeera rice': 'rice|rice 55, ghee 3, spice 0.5',
    'Kerala matta rice': 'rice|rrice 58',
    'Foxtail millet rice': 'rice|foxtail 55',
    'Kodo millet rice': 'rice|kodo 55',
    'Cooked quinoa': 'rice|quinoa 60',
    'Vegetable pulao': 'pulao|rice 50, mixveg 50, oil 5',
    'Lemon rice': 'rice|rice 55, peanut 5, lemon 5, oil 5',
    'Curd rice': 'rice|rice 40, curd 100, oil 2',
    'Tamarind rice (puliyogare)': 'rice|rice 55, tamarind 8, peanut 5, oil 6',
    'Moong dal khichdi': 'khichdi|rice 45, moong 30, mixveg 30, ghee 4',
    'Vegetable dalia khichdi': 'khichdi|dalia 45, moong 20, mixveg 50, oil 3',
    'Bajra–moong khichdi': 'khichdi|bajra 40, moong 30, ghee 4',
    'Oats–moong khichdi': 'khichdi|oats 35, moong 25, mixveg 40, oil 3',
    'Vegetable quinoa khichdi': 'khichdi|quinoa 45, moong 25, mixveg 40, oil 3',
    'Bisi bele bath': 'khichdi|rice 45, toor 25, mixveg 60, tamarind 3, ghee 5',
    'Vegetable biryani': 'biryani|rice 65, mixveg 80, curd 20, oil 8',
    'Chicken biryani': 'biryani|rice 65, chickenc 80, curd 20, onion 20, oil 8',
    'Egg biryani': 'biryani|rice 65, egg 100, onion 20, oil 8',
    'Soya pulao': 'pulao|rice 55, soya 25, mixveg 40, oil 5',
    'Instant khichdi cup': 'ready|rice 40, moong 25, oil 3',
    'Ragi mudde': 'roti|ragi 60',
    'Barnyard (sama) millet rice': 'rice|sama 50',
    'Little millet rice': 'rice|kutki 52',
    'Red rice': 'rice|rrice 58',
    'Coconut rice': 'rice|rice 50, coconut 20, oil 4',
    'Tomato rice': 'rice|rice 55, tomato 60, oil 5',
    'Matar pulao': 'pulao|rice 55, peas 40, ghee 4',
    'Mutton biryani': 'biryani|rice 65, mutton 90, curd 20, onion 20, oil 8',
    'Fish biryani': 'biryani|rice 65, fish 100, curd 20, onion 20, oil 7',
    'Prawn pulao': 'pulao|rice 65, prawn 100, onion 20, oil 6',
    'Brown rice khichdi': 'khichdi|brice 45, moong 30, mixveg 30, ghee 3',
    'Gujarati masala khichdi': 'khichdi|rice 45, toor 25, mixveg 50, peanut 4, ghee 4',
    'Lemon quinoa': 'rice|quinoa 55, peanut 3, lemon 5, oil 3',
    'Nachni (ragi) bhakri': 'roti|ragi 60',
    'Dal dhokli': 'khichdi|atta 40, toor 25, jaggery 3, peanut 4, oil 3',
    'Rumali roti': 'roti|maida 35, atta 35',
    'Palak roti': 'roti|atta 45, spinach 30',
    'Methi roti': 'roti|atta 45, methi 20, oil 1',
    'Oats roti': 'roti|atta 30, oats 15',
    'Luchi': 'fried|maida 40, oil 12',

    // Dals & legumes
    'Dal tadka (toor)': 'dal|toor 30, onion 15, tomato 15, ghee 3, spice 1.5',
    'Moong dal': 'dal|moong 30, tomato 15, oil 2, spice 1',
    'Masoor dal': 'dal|masoor 30, onion 10, oil 3, spice 1',
    'Chana dal': 'dal|chanadal 35, onion 10, tomato 15, oil 3',
    'Panchmel (mixed) dal': 'dal|toor 8, moong 8, masoor 8, chanadal 6, urad 6, ghee 3',
    'Dal palak': 'dal|toor 25, spinach 60, garlic 3, oil 3',
    'Chana dal with lauki': 'dal|chanadal 25, lauki 80, oil 3',
    'Gujarati dal': 'dal|toor 25, tomato 20, jaggery 3, peanut 2, oil 3',
    'Dal makhani': 'curry|urad 25, rajma 5, tomato 30, butter 5, cream 10',
    'Rajma': 'curry|rajma 40, onion 25, tomato 30, oil 4',
    'Chole': 'curry|kchana 40, onion 25, tomato 30, oil 5',
    'Kala chana curry': 'curry|kalachana 40, onion 20, tomato 25, oil 4',
    'Lobia curry': 'curry|lobia 40, onion 20, tomato 25, oil 3',
    'Kadhi (no pakoda)': 'kadhi|curd 120, besan 12, oil 4',
    'Pithla': 'kadhi|besan 30, onion 20, oil 5',
    'Moong usal': 'curry|wmoong 40, onion 15, coconut 3, oil 3',
    'Matki usal': 'curry|moth 40, onion 15, coconut 3, oil 3',
    'Kadala curry': 'curry|kalachana 40, coconut 10, onion 15, oil 4',
    'Cholar dal': 'dal|chanadal 35, coconut 5, ghee 3',
    'Dalma (dal with vegetables)': 'dal|toor 25, mixveg 80, ghee 2',
    'Moong sprouts curry': 'curry|sprouts 100, onion 15, tomato 20, oil 3',
    'Horse gram (kulthi) dal': 'dal|kulthi 35, tomato 15, oil 3',
    'Dhuli urad dal': 'dal|urad 32, onion 10, ghee 3',
    'Dal fry': 'dal|toor 30, onion 20, tomato 20, oil 5',
    'Sai bhaji': 'dal|chanadal 25, spinach 60, mixveg 40, oil 4',
    'Mysore rasam with dal': 'soup|toor 15, tomato 50, tamarind 4, oil 2, spice 1.5',
    'Kootu (dal & vegetable)': 'south|moong 20, mixveg 80, coconut 8, oil 2',
    'Toor dal (plain)': 'dal|toor 30, oil 1',
    'Andhra pappu': 'dal|toor 30, tomato 20, oil 3',
    'Tomato pappu': 'dal|toor 28, tomato 60, oil 3',
    'Mor kuzhambu': 'kadhi|curd 120, coconut 8, toor 3, oil 3',
    'Vatha kuzhambu': 'curry|tamarind 15, mixveg 30, oil 6, spice 3',
    'Moth dal': 'dal|moth 35, onion 10, oil 3',
    'Varan (Maharashtrian dal)': 'dal|toor 30, ghee 1',
    'Aamti': 'dal|toor 28, tamarind 3, jaggery 3, coconut 3, oil 3',
    'Sabut masoor dal': 'dal|masoor 35, onion 10, tomato 15, oil 2',
    'Dry chana masala': 'curry|kchana 45, onion 20, tomato 20, oil 4',
    'Mixed sprouts curry': 'curry|msprouts 110, onion 15, tomato 20, oil 3',

    // Protein mains
    'Palak paneer': 'paneer|paneer 60, spinach 150, onion 20, tomato 20, cream 5, oil 4',
    'Matar paneer': 'paneer|paneer 60, peas 40, onion 25, tomato 30, oil 4',
    'Kadai paneer': 'paneer|paneer 65, capsicum 40, onion 25, tomato 30, oil 5',
    'Paneer tikka masala (light)': 'paneer|paneer 65, onion 25, tomato 40, curd 20, cream 5, oil 5',
    'Grilled paneer': 'grill|paneer 100, oil 1, spice 1',
    'Soya chunk curry': 'gravy|soya 30, onion 25, tomato 30, oil 4',
    'Soya keema with peas': 'gravy|soya 30, peas 30, onion 20, tomato 25, oil 4',
    'Tofu curry': 'paneer|tofu 100, onion 25, tomato 30, oil 4',
    'Mushroom matar': 'gravy|mushroom 100, peas 40, onion 20, tomato 25, oil 4',
    'Egg curry (2 eggs)': 'meat|egg 100, onion 30, tomato 30, oil 5',
    'Chicken curry (home-style)': 'meat|chickenc 110, onion 30, tomato 30, curd 10, oil 5',
    'Butter chicken (light)': 'meat|chickenc 110, tomato 60, butter 6, cream 10, oil 2',
    'Chicken tikka': 'tikka|chicken 130, curd 20, oil 3, spice 2',
    'Tandoori chicken (skinless)': 'tikka|chicken 160, curd 25, oil 3, spice 2',
    'Chicken keema with peas': 'meat|ckeema 90, peas 30, onion 25, tomato 25, oil 4',
    'Chettinad chicken': 'meat|chickenc 110, onion 30, coconut 5, oil 5, spice 2',
    'Kerala chicken stew': 'meat|chickenc 90, potato 40, coconutmilk 30, oil 3',
    'Fish curry': 'meat|fish 120, onion 25, tomato 30, oil 5',
    'Maacher jhol (Bengali fish curry)': 'meat|fish 120, potato 30, tomato 20, oil 4',
    'Fish tikka': 'tikka|fish 130, curd 15, oil 3, spice 2',
    'Tawa fish': 'grill|fish 130, oil 6, spice 2',
    'Goan fish curry': 'meat|fish 110, coconutmilk 40, onion 20, oil 3',
    'Prawn masala': 'meat|prawn 130, onion 30, tomato 30, oil 5',
    'Mutton curry (lean)': 'meat|mutton 110, onion 30, tomato 30, oil 6',
    'Chicken & vegetable stew': 'meat|chicken 90, mixveg 100, oil 3',
    'Paneer do pyaza': 'paneer|paneer 65, onion 50, tomato 25, oil 5',
    'Shahi paneer (light)': 'paneer|paneer 65, cashew 8, curd 20, cream 8, tomato 30, oil 3',
    'Tofu tikka masala': 'paneer|tofu 110, tomato 50, onion 20, curd 20, oil 4',
    'Grilled soya chaap': 'tikka|chaap 100, oil 2',
    'Egg white bhurji': 'egg|eggw 180, onion 20, tomato 20, oil 3',
    'Chicken saagwala': 'meat|chickenc 100, spinach 100, onion 20, oil 4',
    'Chicken do pyaza': 'meat|chickenc 110, onion 60, oil 4',
    'Air-fried chicken 65': 'tikka|chicken 140, curd 15, cornflour 8, oil 3',
    'Kadai chicken': 'meat|chickenc 110, capsicum 40, onion 25, tomato 30, oil 5',
    'Pepper chicken (dry)': 'meat|chickenc 120, onion 20, oil 5, spice 2',
    'Andhra chicken curry': 'meat|chickenc 110, onion 30, tomato 20, oil 6',
    'Chicken seekh kebab (grilled)': 'tikka|ckeema 130, onion 15, oil 2',
    'Mutton keema (lean)': 'meat|keema 90, peas 20, onion 20, tomato 20, oil 3',
    'Rogan josh (lean)': 'meat|mutton 120, curd 20, oil 7, spice 2',
    'Meen moilee': 'meat|fish 120, coconutmilk 50, onion 20, oil 3',
    'Air-fried Amritsari fish': 'tikka|fish 130, besan 10, oil 3',
    'Doi maach': 'meat|fish 120, curd 40, oil 5',
    'Kerala prawn curry': 'meat|prawn 130, coconutmilk 40, tomato 20, oil 3',
    'Chicken tikka masala (light)': 'meat|chicken 120, tomato 60, curd 20, cream 8, oil 4',

    // Sabzis
    'Bhindi masala': 'sabzi|okra 150, onion 25, tomato 15, oil 5, spice 2',
    'Lauki sabzi': 'sabzi|lauki 180, tomato 20, oil 3, spice 2',
    'Tinda sabzi': 'sabzi|tinda 170, tomato 15, oil 3, spice 2',
    'Turai sabzi': 'sabzi|turai 170, onion 15, oil 3, spice 2',
    'Karela sabzi': 'sabzi|karela 150, onion 30, oil 5, spice 2',
    'Parwal sabzi': 'sabzi|parwal 150, oil 4, spice 2',
    'Patta gobhi (cabbage) sabzi': 'sabzi|cabbage 160, peas 15, oil 4, spice 2',
    'Cabbage poriyal': 'south|cabbage 160, coconut 8, oil 4',
    'Beans poriyal': 'south|beans 150, coconut 8, oil 4',
    'Beetroot poriyal': 'south|beet 150, coconut 8, oil 4',
    'Carrot–beans poriyal': 'south|carrot 70, beans 80, coconut 8, oil 4',
    'Cabbage thoran': 'south|cabbage 150, coconut 15, oil 4',
    'Beans thoran': 'south|beans 140, coconut 15, oil 4',
    'Avial': 'south|mixveg 150, coconut 20, curd 30, oil 4',
    'Aloo gobhi': 'sabzi|potato 80, cauli 100, onion 15, oil 5, spice 2',
    'Gobhi matar': 'sabzi|cauli 120, peas 40, tomato 20, oil 4, spice 2',
    'Aloo matar': 'gravy|potato 90, peas 40, onion 20, tomato 30, oil 4',
    'Jeera aloo': 'sabzi|potato 130, oil 5, spice 2',
    'Mixed vegetable sabzi': 'sabzi|mixveg 170, onion 15, tomato 20, oil 4, spice 2',
    'Palak bhaji': 'sabzi|spinach 200, garlic 3, oil 4',
    'Methi sabzi': 'sabzi|methi 120, oil 4',
    'Sarson ka saag': 'sabzi|sarson 150, spinach 50, makki 8, ghee 5',
    'Baingan bharta': 'sabzi|brinjal 180, onion 25, tomato 25, oil 4, spice 2',
    'Bharwa baingan': 'sabzi|brinjal 150, peanut 8, besan 5, oil 5, spice 2',
    'Kaddu (pumpkin) sabzi': 'sabzi|pumpkin 180, jaggery 3, oil 3, spice 2',
    'Capsicum besan sabzi': 'sabzi|capsicum 120, besan 15, oil 5',
    'Mushroom sabzi': 'sabzi|mushroom 150, onion 20, tomato 20, oil 4, spice 2',
    'Kathal (jackfruit) sabzi': 'sabzi|jackfruitraw 150, onion 20, oil 5, spice 2',
    'Arbi sabzi': 'sabzi|arbi 100, oil 5, spice 1',
    'Shukto': 'sabzi|karela 30, rawbanana 40, brinjal 40, mixveg 40, milk 20, oil 4',
    'Chorchori (mixed veg)': 'sabzi|mixveg 150, pumpkin 40, oil 4',
    'Undhiyu (light)': 'sabzi|mixveg 80, spotato 40, beans 40, peanut 5, oil 5',
    'Tindora (kovakkai) sabzi': 'sabzi|tindora 150, oil 5, spice 1',
    'Gawar (cluster beans) sabzi': 'sabzi|gawar 150, oil 4, spice 1',
    'Drumstick curry': 'gravy|drumstick 100, onion 20, tomato 30, besan 5, oil 4',
    'Raw banana poriyal': 'south|rawbanana 100, coconut 8, oil 4',
    'Stir-fried vegetables (Indian)': 'sabzi|mixveg 170, oil 4, spice 1',
    'Ker sangri': 'sabzi|kersangri 40, curd 10, oil 6',
    'Vegetable kurma': 'gravy|mixveg 130, coconut 12, cashew 5, oil 4',
    'Lauki kofta curry (baked kofta)': 'gravy|lauki 100, besan 20, onion 20, tomato 30, oil 5',
    'Beans–carrot stir fry': 'sabzi|beans 90, carrot 60, oil 4, spice 1',
    'Cauliflower–peas dry sabzi': 'sabzi|cauli 120, peas 40, oil 4, spice 1',
    'Aloo baingan': 'sabzi|potato 70, brinjal 90, tomato 20, oil 5',
    'Aloo methi': 'sabzi|potato 90, methi 60, oil 5',
    'Gatte ki sabzi (steamed gatte)': 'gravy|besan 30, curd 60, oil 5',
    'Snake gourd kootu': 'south|snakegourd 120, moong 15, coconut 8, oil 2',
    'Ash gourd curry': 'south|ashgourd 150, coconut 8, curd 30, oil 2',
    'Vendakkai poriyal': 'south|okra 150, coconut 5, oil 4',
    'Gutti vankaya (light)': 'sabzi|brinjal 150, peanut 10, sesame 3, oil 6',
    'Mushroom pepper fry': 'sabzi|mushroom 150, onion 20, oil 5, spice 1',
    'Baby corn capsicum': 'sabzi|babycorn 100, capsicum 60, onion 20, oil 4',
    'Broccoli stir-fry (Indian)': 'sabzi|broccoli 150, garlic 3, oil 4',
    'French beans foogath': 'south|beans 140, coconut 10, oil 4',
    'Lau ghonto': 'sabzi|lauki 180, moong 8, milk 20, oil 3',
    'Air-fried begun bhaja': 'tikka|brinjal 150, oil 5, spice 1',
    'Aloo posto (light)': 'sabzi|potato 120, poppy 8, oil 5',
    'Dum aloo (light)': 'gravy|potato 120, curd 30, tomato 30, oil 5',
    'Chawli leaves bhaji': 'sabzi|amaranth 150, garlic 3, oil 4',
    'Bathua sabzi': 'sabzi|bathua 150, oil 4',
    'Suran (yam) sabzi': 'sabzi|suran 100, oil 5',
    'Raw papaya sabzi': 'sabzi|rawpapaya 150, oil 4',

    // Sides
    'Cucumber raita': 'raita|curd 70, cucumber 30',
    'Mint raita': 'raita|curd 75, mint 5',
    'Lauki raita': 'raita|curd 70, lauki 40',
    'Green salad': 'salad|cucumber 70, tomato 50, onion 20, lemon 5',
    'Kachumber salad': 'salad|cucumber 60, tomato 60, onion 30, lemon 5',
    'Beetroot–carrot salad': 'salad|beet 50, carrot 50, lemon 5',
    'Onion–cucumber salad': 'salad|onion 40, cucumber 60',
    'Roasted papad': 'roast|papad 12',
    'Pineapple raita': 'raita|curd 75, pineapple 25',
    'Beetroot raita': 'raita|curd 75, beet 25',
    'Carrot–cabbage salad': 'salad|carrot 50, cabbage 60, lemon 5',
    'Koshimbir': 'salad|cucumber 80, tomato 40, peanut 5, curd 10',
    'Sprouts kosambari': 'salad|moong 20, cucumber 40, carrot 20, coconut 3, lemon 5',
    'Low-fat curd': 'raw|lfcurd 150',

    // Worldwide breakfast
    'Overnight oats with milk & chia': 'porridge|oats 40, milk 150, chia 5',
    'Oatmeal with fruit': 'porridge|oats 40, milk 120, banana 40',
    'Greek yogurt parfait': 'raw|greek 150, apple 60, seeds 8',
    'Avocado toast': 'sandwich|wwbread 60, avocado 70, lemon 5',
    'Scrambled eggs on toast': 'egg|egg 100, wwbread 60, milk 20, butter 4',
    'Vegetable omelette': 'egg|egg 100, mixveg 40, oil 3',
    'Shakshuka': 'egg|egg 100, tomato 150, capsicum 40, onion 30, olive 5',
    'Tofu scramble': 'egg|tofu 120, mixveg 40, oil 3',
    'Peanut butter toast': 'sandwich|wwbread 60, pbutter 16',
    'Smoothie bowl': 'blend|banana 100, berries 80, oats 20, soymilk 100',
    'Whole-wheat pancakes': 'chilla|atta 40, egg 30, milk 60, oil 3',
    'Muesli with milk (no sugar)': 'porridge|muesli 45, milk 150',
    'Cottage cheese & fruit bowl': 'raw|cottage 120, apple 60, berries 40',
    'Breakfast burrito (beans & egg)': 'wrap|wtortilla 60, egg 50, bbeans 60, tomato 20, cheese 8',
    'Huevos rancheros': 'egg|ctortilla 50, egg 100, bbeans 40, tomato 50, oil 3',
    'Congee (rice porridge)': 'porridge|rice 45, ginger 5',
    'Chia pudding (almond milk)': 'soak|chia 25, almondmilk 200, berries 40',
    'Egg muffins': 'baked|egg 120, mixveg 50, cheese 10',
    'Ful medames': 'curry|favabeans 150, tomato 30, lemon 5, olive 5',
    'Labneh, veggies & pita': 'wrap|labneh 60, pita 60, cucumber 50, olive 3',
    'Quinoa porridge': 'porridge|quinoa 45, almondmilk 150, berries 40',
    'Tamagoyaki & miso soup': 'egg|egg 100, soysauce 5, miso 12, oil 3',
    'Protein pancakes': 'chilla|oats 30, eggw 60, whey 15, banana 30',
    'Berry yogurt smoothie': 'blend|curd 150, berries 80',
    'Whole-wheat French toast (light)': 'egg|wwbread 60, egg 50, milk 40, butter 4',
    'Baked chilaquiles': 'baked|ctortilla 50, egg 50, tomato 80, bbeans 40, cheese 10',
    'Menemen (Turkish eggs)': 'egg|egg 100, tomato 120, capsicum 40, olive 5',
    'Hummus & veggie toast': 'sandwich|wwbread 60, hummus 40, cucumber 30, tomato 30',
    'Hotel breakfast plate (eggs, toast, fruit)': 'plate|egg 100, wwbread 60, butter 5, apple 100',

    // Worldwide proteins
    'Grilled chicken breast': 'grill|chicken 130, oil 2',
    'Lemon herb chicken': 'grill|chicken 150, olive 4, lemon 5',
    'Chicken shawarma (no mayo)': 'grill|chickenc 140, curd 15, oil 4, spice 1',
    'Chicken teriyaki': 'stirfry|chicken 150, soysauce 10, honey 5, oil 3',
    'Thai basil chicken': 'stirfry|ckeema 120, capsicum 30, soysauce 8, oil 5',
    'Kung pao chicken (less oil)': 'stirfry|chicken 130, peanut 10, capsicum 30, soysauce 8, oil 6',
    'Chicken fajita strips': 'stirfry|chicken 140, capsicum 40, onion 30, oil 4',
    'Baked herb fish': 'grill|fish 170, olive 4',
    'Grilled salmon': 'grill|salmon 130',
    'Steamed fish with ginger & soy': 'grill|fish 170, soysauce 8, ginger 5, oil 2',
    'Garlic prawns': 'stirfry|prawn 150, garlic 5, olive 5',
    'Tuna salad (no mayo)': 'salad|tuna 110, greens 40, cucumber 30, olive 3, lemon 5',
    'Vegetable frittata': 'baked|egg 100, mixveg 50, cheese 8, oil 2',
    'Grilled tofu': 'grill|tofu 130, soysauce 5, oil 2',
    'Mapo tofu (light)': 'stirfry|tofu 120, mushroom 30, soysauce 8, cornflour 4, oil 5',
    'Tempeh stir-fry': 'stirfry|tempeh 90, mixveg 40, soysauce 5, oil 3',
    'Baked falafel': 'baked|kchana 50, onion 10, oil 4, spice 1',
    'Black bean chili': 'curry|bbeans 150, tomato 60, onion 20, oil 3',
    'Refried beans (no lard)': 'curry|bbeans 90, oil 2',
    'Lentil stew': 'curry|masoor 45, carrot 30, tomato 40, olive 2',
    'Chickpea stew': 'curry|chickpea 140, tomato 60, spinach 20, olive 4',
    'Grilled halloumi': 'grill|halloumi 60',
    'Chicken souvlaki': 'grill|chicken 150, curd 10, olive 4, lemon 5',
    'Paneer steak': 'grill|paneer 100, oil 2',
    'Hummus': 'ready|hummus 50',
    'Grilled prawns': 'grill|prawn 150, olive 3',
    'Chickpea patties': 'baked|chickpea 110, besan 10, onion 15, oil 3',
    'Tofu teriyaki': 'stirfry|tofu 130, soysauce 10, honey 5, oil 2',
    'Moroccan spiced chicken': 'grill|chicken 150, olive 4, spice 2',
    'Lentil patties': 'baked|masoor 45, oats 10, onion 15, oil 3',

    // Worldwide carbs
    'Whole-wheat pasta': 'pasta|pasta 50',
    'Whole-wheat couscous': 'rice|couscous 45',
    'Bulgur wheat': 'rice|bulgur 45',
    'Whole-wheat pita': 'ready|pita 60',
    'Whole-wheat tortilla wrap': 'ready|wtortilla 45',
    'Corn tortillas': 'ready|ctortilla 52',
    'Soba noodles': 'noodles|soba 35',
    'Rice noodles': 'noodles|ricenoodle 50',
    'Jasmine rice': 'rice|rice 55',
    'Baked potato': 'baked|potato 200',
    'Baked sweet potato': 'baked|spotato 130',
    'Sourdough bread': 'ready|sourdough 66',
    'Multigrain bread': 'ready|mgbread 54',
    'Mexican rice': 'rice|rice 55, tomato 40, oil 5',
    'Pearl barley': 'rice|barley 50',
    'Polenta': 'porridge|cornmeal 38',
    'Cauliflower rice': 'stirfry|cauli 150, oil 1',
    'Zucchini noodles': 'stirfry|zucchini 150, oil 1',
    'Brown rice noodles': 'noodles|brnoodle 50',
    'Wild rice': 'rice|wildrice 45',
    'Farro': 'rice|farro 55',
    'Herb roasted potatoes': 'baked|potato 150, olive 5',
    'Whole-wheat garlic bread (light)': 'sandwich|wwbread 60, butter 6, garlic 4',

    // Worldwide vegetables
    'Roasted vegetables': 'baked|mixveg 150, olive 4',
    'Steamed broccoli': 'raw|broccoli 150',
    'Sautéed spinach': 'stirfry|spinach 180, garlic 3, olive 4',
    'Greek salad (light feta)': 'salad|cucumber 80, tomato 80, onion 20, feta 25, olive 5',
    'Garden salad with vinaigrette': 'salad|greens 80, cucumber 40, tomato 40, olive 4, lemon 5',
    'Tabbouleh': 'salad|bulgur 15, coriander 40, tomato 60, olive 5, lemon 5',
    'Fattoush (baked pita)': 'salad|greens 60, cucumber 40, tomato 40, pita 15, olive 5',
    'Stir-fried bok choy': 'stirfry|bokchoy 200, soysauce 4, oil 4',
    'Asian stir-fry vegetables': 'stirfry|mixveg 150, soysauce 5, oil 4',
    'Kimchi': 'ready|kimchi 75',
    'Cucumber sesame salad': 'salad|cucumber 150, sesame 3, soysauce 3, oil 2',
    'Pico de gallo': 'salad|tomato 70, onion 15, coriander 5, lemon 5',
    'Guacamole': 'salad|avocado 45, onion 5, lemon 5',
    'Grilled zucchini & peppers': 'grill|zucchini 100, capsicum 60, olive 4',
    'Ratatouille': 'baked|brinjal 60, zucchini 50, capsicum 40, tomato 60, olive 5',
    'Light coleslaw': 'salad|cabbage 60, carrot 20, curd 25, oil 2',
    'Green beans with almonds': 'stirfry|beans 140, almond 8, olive 3',
    'Caprese salad (light)': 'salad|tomato 120, mozz 45, olive 4',
    'Baba ganoush': 'chutney|brinjal 60, sesame 5, olive 3, lemon 5',
    'Roasted cauliflower': 'baked|cauli 180, olive 4',
    'Roasted beetroot salad': 'salad|beet 150, greens 30, feta 10, olive 3',
    'Kale salad': 'salad|kale 100, sesame 3, olive 4, lemon 5',
    'Mushroom stir-fry': 'stirfry|mushroom 180, soysauce 5, oil 3',
    'Sautéed green beans': 'stirfry|beans 150, olive 3',
    'Quinoa salad': 'salad|quinoa 30, cucumber 50, tomato 50, olive 4, lemon 5',
    'Corn & bean salad': 'salad|corn 60, bbeans 70, tomato 40, onion 15, lemon 5',
    'Tzatziki': 'raita|greek 40, cucumber 20, garlic 1',

    // Worldwide mains
    'Chicken burrito bowl': 'bowl|rice 55, chicken 110, bbeans 60, corn 30, tomato 40, onion 10, oil 3',
    'Bean burrito bowl': 'bowl|rice 60, bbeans 120, corn 40, tomato 50, onion 15, avocado 20, oil 3',
    'Chicken shawarma bowl': 'bowl|rice 45, chickenc 110, greens 40, cucumber 40, tomato 40, curd 30, oil 4',
    'Falafel wrap': 'wrap|wtortilla 60, kchana 40, greens 40, tomato 30, hummus 20, oil 4',
    'Mediterranean chickpea salad': 'salad|chickpea 150, cucumber 60, tomato 60, onion 20, feta 15, olive 5',
    'Greek chicken salad': 'salad|chicken 120, greens 60, cucumber 60, tomato 60, feta 20, olive 6',
    'Grilled chicken Caesar (light)': 'salad|chicken 120, greens 100, wwbread 15, cheese 8, curd 20, egg 10, olive 4',
    'Tuna Niçoise salad': 'salad|tuna 90, egg 50, potato 80, beans 60, greens 40, olive 6',
    'Salmon quinoa bowl': 'bowl|salmon 110, quinoa 45, greens 40, cucumber 40, avocado 25',
    'Tuna poke bowl': 'bowl|tuna 100, rice 60, cucumber 40, edamame 30, soysauce 8, sesame 3',
    'Tofu poke bowl': 'bowl|tofu 120, rice 60, cucumber 40, edamame 30, soysauce 8, sesame 3',
    'Vegetable sushi rolls': 'bowl|rice 70, cucumber 30, avocado 20, carrot 20, soysauce 5',
    'Salmon sushi rolls': 'bowl|rice 70, salmon 40, cucumber 20, soysauce 5',
    'Chicken pho': 'noodles|ricenoodle 60, chicken 100, onion 20, greens 20, kimchi 5',
    'Vegetable ramen (light)': 'noodles|wheatnoodle 70, mixveg 100, tofu 50, soysauce 10, oil 3',
    'Pad thai (light)': 'noodles|ricenoodle 65, egg 30, tofu 40, peanut 10, sprouts 30, tamarind 5, sugar 5, kimchi 5, oil 6',
    'Thai green curry (chicken) & rice': 'bowl|rice 55, chicken 100, coconutmilk 60, mixveg 60, kimchi 5, oil 3',
    'Thai green curry (tofu) & rice': 'bowl|rice 55, tofu 100, coconutmilk 60, mixveg 60, oil 3',
    'Chicken stir-fry with brown rice': 'stirfry|brice 55, chicken 110, mixveg 80, soysauce 8, oil 5',
    'Egg fried rice (less oil)': 'stirfry|rice 65, egg 60, mixveg 50, soysauce 6, oil 7',
    'Veg hakka noodles (less oil)': 'noodles|wheatnoodle 70, mixveg 100, soysauce 6, oil 7',
    'Bibimbap': 'bowl|rice 70, egg 50, tofu 40, spinach 50, carrot 30, sprouts 30, soysauce 5, oil 5',
    'Japanese chicken curry & rice': 'bowl|rice 65, chickenc 90, potato 50, carrot 30, maida 10, oil 6',
    'Whole-wheat pasta primavera': 'pasta|pasta 75, mixveg 100, cheese 10, olive 5',
    'Whole-wheat pasta arrabbiata': 'pasta|pasta 80, tomato 120, garlic 4, olive 6',
    'Chicken tomato pasta (whole-wheat)': 'pasta|pasta 75, chicken 100, tomato 100, olive 5',
    'Grilled fish with mash & greens': 'plate|fish 150, potato 150, milk 30, butter 5, greens 60',
    'Chicken stew with bread': 'plate|chicken 100, mixveg 120, wwbread 55, oil 4',
    'Lentil shepherd\'s pie': 'baked|masoor 45, mixveg 80, potato 150, milk 30, butter 4',
    'Stuffed bell peppers (quinoa & paneer)': 'baked|capsicum 150, quinoa 30, paneer 40, tomato 40, oil 3',
    'Chicken tacos (corn)': 'wrap|ctortilla 78, chicken 100, onion 20, tomato 40, avocado 20, oil 3',
    'Bean enchiladas (light)': 'baked|wtortilla 70, bbeans 120, cheese 15, tomato 60, oil 3',
    'Vegetable quesadilla (whole-wheat)': 'wrap|wtortilla 60, cheese 30, bbeans 40, capsicum 40, onion 20, oil 2',
    'Moroccan chickpea tagine & couscous': 'bowl|couscous 50, chickpea 120, mixveg 80, tomato 50, olive 5',
    'Mujadara (lentils & rice)': 'khichdi|rice 45, masoor 40, onion 40, olive 5',
    'Chicken souvlaki plate': 'plate|chicken 130, pita 60, curd 40, cucumber 50, tomato 50, olive 4',
    'Buddha bowl': 'bowl|quinoa 40, chickpea 80, spotato 80, greens 40, hummus 25, olive 3',
    'Grilled chicken wrap': 'wrap|wtortilla 60, chicken 100, greens 40, curd 20, oil 3',
    'Paneer kathi roll (whole-wheat)': 'wrap|atta 50, paneer 60, onion 30, capsicum 30, oil 5',
    'Egg roll (whole-wheat, less oil)': 'wrap|atta 50, egg 100, onion 30, oil 5',
    'Light vegetable lasagna': 'baked|pasta 60, mixveg 120, tomato 80, cheese 25, milk 40',
    'Chicken fried rice (less oil)': 'stirfry|rice 65, chicken 80, egg 30, mixveg 40, soysauce 6, oil 6',
    'Teriyaki salmon bowl': 'bowl|salmon 110, rice 60, mixveg 60, soysauce 8, honey 4',
    'Korean tofu stew': 'soup|tofu 150, egg 50, mushroom 40, soysauce 6, oil 3',
    'Vietnamese chicken salad': 'salad|chicken 120, cabbage 80, carrot 40, peanut 5, lemon 10, kimchi 5',
    'Green papaya salad (som tam)': 'salad|rawpapaya 150, tomato 30, peanut 10, lemon 10, kimchi 5',
    'Pasta e fagioli': 'soup|pasta 50, bbeans 100, tomato 80, olive 5',
    'Chicken quinoa salad': 'salad|chicken 110, quinoa 40, greens 40, cucumber 40, olive 5',
    'Mexican quinoa bowl': 'bowl|quinoa 50, bbeans 100, corn 40, tomato 40, avocado 25',
    'Hummus chicken wrap': 'wrap|wtortilla 60, chicken 100, hummus 30, greens 30',
    'Thai red curry (tofu, light) & rice': 'bowl|rice 55, tofu 100, coconutmilk 50, mixveg 60, oil 3',
    'Light mushroom risotto': 'rice|rice 70, mushroom 80, onion 20, cheese 12, butter 5',
    'Grilled chicken with sweet potato': 'plate|chicken 140, spotato 150, broccoli 60, olive 4',
    'Baked fish tacos': 'wrap|ctortilla 78, fish 110, cabbage 40, curd 20, oil 3',
    'Lentil bolognese pasta': 'pasta|pasta 75, masoor 35, tomato 100, olive 4',

    // Travel
    'Veg thali (railway / dhaba)': 'plate|atta 60, rice 45, toor 25, mixveg 120, curd 60, oil 10',
    'Dal, 2 tandoori roti & salad (dhaba)': 'plate|atta 85, toor 30, onion 20, tomato 20, cucumber 60, ghee 5',
    'Rajma chawal (dhaba)': 'plate|rice 70, rajma 40, onion 25, tomato 30, oil 6',
    'Idli–sambar plate (station)': 'plate|rice 45, urad 15, toor 20, mixveg 50, coconut 10, oil 3',
    'Grilled sandwich (airport)': 'sandwich|wwbread 70, cheese 20, mixveg 50, butter 5',
    'Hotel salad bar plate with grilled chicken': 'salad|chicken 130, greens 100, cucumber 50, tomato 50, chickpea 40, olive 8',
    'Hotel salad bar plate with paneer': 'salad|paneer 70, greens 100, cucumber 50, tomato 50, chickpea 40, olive 6',
    'Non-veg thali (railway / dhaba)': 'plate|atta 60, rice 45, chickenc 100, mixveg 80, curd 50, oil 10',
    'Thepla & curd (packed)': 'plate|atta 45, besan 10, methi 20, curd 100, oil 6',
    'Airport salad bowl': 'salad|greens 80, chickpea 60, cucumber 40, tomato 40, feta 15, olive 5',
    'Veg sub (6-inch, whole-wheat)': 'sandwich|wwbread 80, mixveg 60, cheese 15, curd 10',
    'Chicken sub (6-inch, whole-wheat)': 'sandwich|wwbread 80, chicken 80, greens 30, curd 10',
    'Dhaba paneer & roti': 'plate|atta 70, paneer 80, tomato 40, onion 30, butter 5, oil 8',
    'Dhaba chicken & roti': 'plate|atta 70, chickenc 140, tomato 40, onion 30, oil 8',
    'Khichdi & curd (dhaba)': 'plate|rice 55, moong 35, curd 100, ghee 5',
  };

  // ── Method steps ({main} = key ingredients, {aro} = onion/tomato/ginger/garlic)
  const STEPS = {
    water: ['Soak or boil {main} in 1 glass of water (overnight or 5 minutes).', 'Strain, warm lightly and sip slowly on an empty stomach.'],
    raw: ['Wash well.', 'Peel, cut or portion {main} and serve fresh.'],
    soak: ['Soak {main} in water overnight (or 4–6 hours).', 'Drain, peel if needed and eat in the morning.'],
    roast: ['Dry-roast {main} in a heavy pan on low heat for 5–8 minutes, stirring (use only the oil/ghee listed).', 'Season with salt, pepper or chaat masala; cool and store airtight.'],
    ready: ['Ready to eat: {main}.', 'Choose plain, unsweetened, low-salt varieties and check the label.'],
    tea: ['Boil 1 cup of water with {main} for 3–5 minutes.', 'Strain and serve warm, without extra sugar.'],
    milk: ['Heat {main} in a pan until it just boils.', 'Simmer 1–2 minutes with the flavouring; serve warm without sugar.'],
    blend: ['Add {main} to a blender with a little water or ice.', 'Blend until smooth and serve immediately (no added sugar).'],
    mixdrink: ['Whisk {main} into 1 glass of chilled water.', 'Add a pinch of salt, roasted cumin and a squeeze of lemon; serve.'],
    roti: ['Knead {main} with water and a pinch of salt into a soft dough; rest 15 minutes.', 'Divide into balls and roll out thin (pat by hand for millet flours).', 'Cook on a hot tawa on both sides; puff over the flame.', 'Brush with ghee/oil only if it is listed.'],
    paratha: ['Knead the flour with water into a soft dough; rest 15 minutes.', 'Prepare the filling or mix-in: {main} with salt and spices.', 'Stuff or mix, roll gently and cook on a tawa using only the listed oil/ghee until golden on both sides.'],
    fried: ['Knead {main} into a stiff dough and roll small discs.', 'Deep-fry in hot oil until puffed; drain well on paper (the oil listed is what is absorbed).'],
    rice: ['Wash {main} 2–3 times and soak 15 minutes (30 minutes for brown/red rice and millets).', 'Cook with 2–2½ parts water until soft; add the other listed ingredients as the dish needs.', 'Fluff with a fork and serve hot.'],
    pulao: ['Wash and soak the rice for 15 minutes.', 'Heat the oil/ghee, add whole spices, then {main}; sauté 3–4 minutes.', 'Add the rice, salt and 2 parts water; cover and cook until done.'],
    khichdi: ['Wash {main} together and soak 15 minutes.', 'Heat the fat, add cumin and the vegetables.', 'Add the soaked mix, turmeric, salt and 4 parts water; pressure-cook 3–4 whistles.', 'Serve hot with a squeeze of lemon.'],
    biryani: ['Marinate {main} with curd, ginger-garlic and biryani masala for 30 minutes.', 'Par-boil the rice with whole spices until 70% cooked.', 'Layer the masala and rice, cover tightly and cook on low heat (dum) for 20 minutes.'],
    dal: ['Wash {main} and pressure-cook with 3 cups water, turmeric and salt (3 whistles).', 'Heat the fat, crackle cumin/mustard and hing, then add {aro}; cook until soft.', 'Add the cooked dal, simmer 5 minutes and garnish with coriander.'],
    curry: ['Soak {main} overnight (if dry) and pressure-cook until soft.', 'Cook {aro} in the oil with spices until the oil separates.', 'Add the cooked beans with some of their water; simmer 10 minutes to thicken.'],
    kadhi: ['Whisk {main} with 2 cups water until smooth and lump-free.', 'Bring to a boil, stirring, then simmer 15–20 minutes.', 'Temper with the oil, cumin, curry leaves and chilli; pour over and serve.'],
    sabzi: ['Wash and chop {main}.', 'Heat the fat, add cumin, then {aro}; sauté 2 minutes.', 'Add {main}, turmeric, coriander powder and salt; cover and cook on low heat until tender (10–15 minutes).', 'Garnish with fresh coriander.'],
    south: ['Chop {main} finely.', 'Heat the oil, splutter mustard seeds, urad dal and curry leaves.', 'Add the vegetables and salt; cover and cook until just tender.', 'Finish with the grated coconut.'],
    gravy: ['Prepare {main} (chop, soak or shape as needed).', 'Cook {aro} in the oil with spices into a thick masala.', 'Add {main} with a little water; simmer until cooked through.', 'Garnish with coriander.'],
    paneer: ['Cut {main} into cubes.', 'Cook {aro} in the oil with spices into a smooth masala.', 'Add the cubes and any cream/curd listed; simmer 3–4 minutes and serve.'],
    tikka: ['Marinate {main} with hung curd, lemon, ginger-garlic and tikka spices for 30 minutes.', 'Grill, air-fry or bake at 220 °C for 12–15 minutes, turning once.', 'Serve with lemon wedges and onion rings.'],
    meat: ['Clean and cut {main}.', 'Cook {aro} in the oil with whole and ground spices.', 'Add {main} and salt; cover and cook until tender (fish 10 min, chicken 20 min, mutton 4–5 pressure-cooker whistles).', 'Adjust water for the gravy and garnish.'],
    egg: ['Prepare {main} (beat the eggs / crumble the paneer or tofu).', 'Cook {aro} briefly in the fat.', 'Add the main ingredient and cook until just set; season lightly and serve.'],
    chilla: ['Make a thin batter of {main} with water, salt and spices (soak whole dal 4 hours and grind).', 'Spread a ladle on a hot non-stick tawa and drizzle a few drops of the listed oil.', 'Cook both sides until golden.'],
    dosa: ['Soak {main} for 5–6 hours, grind to a batter and ferment overnight.', 'Spread thin on a hot tawa, drizzle the listed oil and cook until crisp.', 'Serve hot.'],
    idli: ['Soak and grind {main}; ferment overnight (for rava/oats versions, mix with curd and rest 20 minutes).', 'Pour into greased idli moulds.', 'Steam 10–12 minutes and rest 2 minutes before removing.'],
    steamed: ['Mix {main} with water, salt and spices into a batter or dough.', 'Steam in a greased plate or rolls for 15–20 minutes.', 'Temper with the oil, mustard seeds and curry leaves; cut and serve.'],
    upma: ['Dry-roast {main} until aromatic.', 'Heat the oil, splutter mustard seeds, add curry leaves, {aro} and vegetables.', 'Add 2–2½ parts hot water and salt, stir in the roasted grain and cook covered 3–5 minutes.'],
    poha: ['Rinse {main}, drain and rest 5 minutes to soften.', 'Heat the oil, splutter mustard seeds, add curry leaves, {aro} and vegetables.', 'Add the main ingredient, turmeric and salt; mix gently, steam 2 minutes and finish with lemon and coriander.'],
    porridge: ['Cook {main} in water or milk for 8–10 minutes, stirring often.', 'Add the fruit, nuts or seeds listed.', 'Serve warm, without sugar.'],
    salad: ['Wash and chop {main}.', 'Toss with lemon juice, salt, pepper and herbs (and the dressing listed).', 'Serve fresh.'],
    raita: ['Whisk the curd / yogurt until smooth.', 'Stir in {main}, roasted cumin powder and salt.', 'Chill and serve.'],
    chutney: ['Grind {main} with a little water and salt to a smooth paste.', 'Temper with the listed oil and mustard seeds if you like.'],
    soup: ['Chop {main}.', 'Cook in 2 cups water with salt and pepper until soft (10–15 minutes).', 'Blend or keep chunky; add the listed fat only.', 'Serve hot.'],
    chaat: ['Boil or steam {main} if needed.', 'Mix with the chopped vegetables, coriander, lemon, chaat masala and salt.', 'Serve immediately.'],
    laddoo: ['Chop or grind {main}.', 'Mix well (warm the jaggery/ghee if listed) and shape into laddoos or bars.', 'Store airtight in the fridge.'],
    sandwich: ['Prepare the filling: {main}.', 'Spread between the bread slices.', 'Grill or toast until golden.'],
    wrap: ['Warm the wrap / roti.', 'Fill with {main}.', 'Roll up tightly and serve.'],
    bowl: ['Cook {main} as needed.', 'Arrange in a bowl with the vegetables.', 'Dress with lemon, herbs or the sauce listed.'],
    grill: ['Season {main} with salt, pepper, herbs and lemon (or the marinade listed).', 'Grill, pan-sear or bake until cooked through.', 'Rest 2 minutes and serve.'],
    stirfry: ['Cut {main} into bite-size pieces.', 'Stir-fry in the listed oil on high heat with garlic and ginger.', 'Add the sauce listed, toss and serve hot.'],
    pasta: ['Boil the pasta in salted water until al dente; drain.', 'Cook {main} in the oil with garlic and herbs.', 'Toss together and serve.'],
    noodles: ['Cook the noodles as per the pack; rinse.', 'Stir-fry {main} in the oil with garlic.', 'Toss with the noodles and the sauce listed.'],
    baked: ['Prepare {main} with spices and salt (mash, shape or slice as needed).', 'Bake at 200 °C for 20–25 minutes or air-fry, turning once.', 'Serve hot.'],
    plate: ['Serve: {main}.', 'Ask for less oil and butter; eat the salad and protein first.'],
  };

  let ING = root.INGREDIENTS || null;
  const DIET_RANK = { vegan: 0, veg: 1, egg: 2, nonveg: 3 };

  function parse(spec) {
    const [tpl, list] = spec.split('|');
    const ing = list.split(',').map((s) => s.trim()).filter(Boolean).map((s) => {
      const m = s.match(/^(\w+)\s+([\d.]+)$/);
      if (!m) throw new Error('Bad recipe item: ' + s);
      return [m[1], Number(m[2])];
    });
    return { tpl: tpl.trim(), ing };
  }

  /** Nutrition, allergens and diet of a list of [ingredientKey, grams]. */
  function analyse(ing, ingredients) {
    const db = ingredients || ING;
    let kcal = 0, p = 0, c = 0, f = 0;
    const tags = new Set();
    let diet = 'vegan';
    ing.forEach(([key, g]) => {
      const x = db[key];
      if (!x) throw new Error('Unknown ingredient: ' + key);
      kcal += (x.kcal * g) / 100; p += (x.p * g) / 100; c += (x.c * g) / 100; f += (x.f * g) / 100;
      x.tags.forEach((t) => tags.add(t));
      const d = x.tags.includes('chicken') || x.tags.includes('mutton') || x.tags.includes('fish') ? 'nonveg'
        : x.tags.includes('egg') ? 'egg' : x.tags.includes('dairy') || key === 'honey' ? 'veg' : 'vegan';
      if (DIET_RANK[d] > DIET_RANK[diet]) diet = d;
    });
    const allergens = ['gluten', 'dairy', 'nuts', 'soy', 'egg', 'fish'].filter((a) => tags.has(a));
    const meats = ['chicken', 'mutton', 'fish'].filter((m) => tags.has(m));
    return { kcal: Math.round(kcal), p: Math.round(p * 10) / 10, c: Math.round(c * 10) / 10, f: Math.round(f * 10) / 10, allergens, diet, meats };
  }

  const titleCase = (s) => s.replace(/\s*\(.*?\)/g, '').toLowerCase();

  /** Steps with ingredient names filled in. */
  function steps(recipe, ingredients) {
    const db = ingredients || ING;
    const names = recipe.ing.map(([k]) => db[k]);
    let main = names.filter((x) => !x.tags.includes('staple') && x.cat !== 'spice' && x.cat !== 'fat').map((x) => titleCase(x.name));
    if (!main.length) main = names.filter((x) => x.cat !== 'spice').map((x) => titleCase(x.name));
    const aro = names.filter((x) => ['onion', 'tomato', 'ginger', 'garlic', 'chilli'].includes(x.key)).map((x) => x.name.toLowerCase());
    const join = (l) => (l.length > 1 ? l.slice(0, -1).join(', ') + ' and ' + l[l.length - 1] : l[0] || 'the ingredients');
    return (STEPS[recipe.tpl] || STEPS.plate).map((s) => s.replace('{main}', join(main)).replace('{aro}', aro.length ? join(aro) : 'the spices'));
  }

  /**
   * Attach recipes to foods and recalculate their nutrition from ingredients.
   * The recipe's diet and allergens are merged in (never loosened).
   */
  const VEGAN_SWAP = { ghee: 'oil', butter: 'oil', honey: 'jaggery' };

  function applyRecipes(foods, ingredients) {
    if (ingredients) ING = ingredients;
    const missing = [];
    foods.forEach((f) => {
      const spec = R[f.name];
      if (!spec) { missing.push(f.name); return; }
      const recipe = parse(spec);
      // A dish listed as vegan keeps a vegan recipe: oil for ghee/butter, jaggery for honey.
      if (f.diet === 'vegan') recipe.ing = recipe.ing.map(([k, g]) => [VEGAN_SWAP[k] || k, g]);
      const n = analyse(recipe.ing);
      f.recipe = recipe;
      f.kcal = n.kcal; f.p = n.p; f.c = n.c; f.f = n.f;
      n.allergens.forEach((a) => { if (!f.allergens.includes(a)) f.allergens.push(a); });
      if (DIET_RANK[n.diet] > DIET_RANK[f.diet]) f.diet = n.diet;
      if (f.diet === 'nonveg') f.meats = n.meats.length ? n.meats : ['chicken'];
    });
    return missing;
  }

  const api = { RECIPES: R, STEPS, parse, analyse, steps, applyRecipes };
  if (typeof module !== 'undefined' && module.exports) {
    ING = require('./ingredients.js');
    module.exports = api;
  } else root.RECIPES = api;
})(typeof window !== 'undefined' ? window : globalThis);
