"""Volume 2 - salads, raitas, soups, chutneys and dips."""
import core
from fam_sides import salad, raita, soup, chutney, LD

core.VOLUME = 2

for name, base, dressing, desc, kw in [
    ('Chickpea Avocado Salad', 'chickpea 100 boiled; avocado 100 diced; onion 40; tomato 60; coriander 6', 'lemon 15; pepper 0.5; jeerapowder 1; salt',
     'A creamy, protein-rich salad of chickpeas and avocado.', {'cooked': 'Soak the chickpeas overnight and pressure-cook until soft; cool.'}),
    ('Avocado Corn Salad', 'avocado 100 diced; corn 100 boiled; onion 30; tomato 50; coriander 6', 'lemon 15; chilliflakes 0.5; salt', 'Avocado and sweet corn salad with lemon.', {}),
    ('Paneer Sprouts Salad', 'paneer 100 cubed; sprouts 120; cucumber 60; tomato 50', LD, 'Paneer and sprouts salad, high in protein.', {}),
    ('Moong Avocado Salad', 'sprouts 150; avocado 80 diced; onion 30; pomegranate 30', LD, 'Moong sprouts with avocado and pomegranate.', {}),
    ('Beetroot Chickpea Salad', 'beet 120 steamed, diced; chickpea 80 boiled; onion 30; mint 4', LD, 'Beetroot and chickpea salad.', {}),
    ('Carrot Raisin Salad', 'carrot 250 grated; raisin 18; peanut 15 roasted', 'lemon 15; salt; pepper 0.3', 'Sweet grated carrot salad with raisins.', {}),
    ('Cucumber Tomato Mint Salad', 'cucumber 200; tomato 120; mint 6; onion 40', 'lemon 15; blacksalt; jeerapowder 0.5', 'A cooling cucumber-tomato-mint salad.', {}),
    ('Paneer Vegetable Salad (Greek Style)', 'paneer 100 cubed; cucumber 100; tomato 80; onion 40; capsicum 50', 'lemon 15; oliveoil 8; oregano 1; pepper 0.5; salt',
     'A Greek-style salad with paneer instead of feta.', {}),
    ('Grilled Vegetable Salad', 'zucchini 120; capsicum 100; redcapsicum 80; onion 60; mushroom 100', 'lemon 15; oliveoil 8; garlic 2; oregano 0.5; salt',
     'Warm salad of grilled vegetables.', {'cooked': 'Grill the vegetables on a grill pan until charred.'}),
    ('Mushroom Salad', 'mushroom 200 sautéed; lettuce 60; onion 30; capsicum 50', 'lemon 10; pepper 1; oliveoil 5; salt', 'A warm mushroom salad.',
     {'cooked': 'Sauté the mushrooms with garlic for 4 minutes.'}),
    ('Broccoli Peanut Salad', 'broccoli 200 blanched; peanut 25 roasted; carrot 60; capsicum 50', 'lemon 15; soysauce 5; honey 5; chilliflakes 0.5',
     'Crunchy broccoli with peanuts.', {'cooked': 'Blanch the broccoli for 2 minutes and plunge into cold water.'}),
    ('Cabbage Peanut Salad', 'cabbage 200 shredded; peanut 25 roasted, crushed; carrot 60; coriander 6', 'lemon 15; salt; gchilli 3', 'A crunchy cabbage and peanut salad.', {}),
    ('Apple Cabbage Slaw', 'cabbage 150 shredded; apple 120 julienned; carrot 60', 'hungcurd 50; lemon 10; pepper 0.5; honey 5; salt', 'A creamy slaw with apple.', {}),
    ('Raw Papaya Salad', 'papaya 250 raw, julienned; carrot 60; peanut 20; coriander 6', 'lemon 20; jaggery 5; gchilli 3; salt', 'A tangy, crunchy raw papaya salad.', {}),
    ('Raw Mango Salad', 'rawmango 150 julienned; onion 40; peanut 20; coriander 6', 'jaggery 5; chilli 0.5; salt', 'Tangy raw mango salad, a summer treat.', {}),
    ('Guava Salad', 'guava 250 diced; cucumber 80; onion 30; mint 4', 'lemon 10; chaat 1.5; chilli 0.3', 'Guava salad with chaat masala.', {}),
    ('Orange Beetroot Salad', 'orange 200 segments; beet 120 steamed; lettuce 40; walnut 15', 'lemon 10; oliveoil 5; pepper 0.3; salt', 'Orange and beetroot salad with walnuts.', {}),
    ('Pomegranate Cucumber Salad', 'cucumber 200; pomegranate 80; mint 4', 'lemon 10; blacksalt; jeerapowder 0.5', 'Cucumber salad with pomegranate.', {}),
    ('Matki Sprouts Salad', 'mixsprouts 200; onion 40; tomato 60; coriander 8', LD, 'Moth bean sprouts salad.', {}),
    ('Quinoa Chickpea Salad', 'quinoa 70; chickpea 80 boiled; cucumber 80; tomato 60; mint 6', 'lemon 20; oliveoil 8; salt; pepper 0.5', 'A filling quinoa and chickpea salad.',
     {'cooked': 'Cook the quinoa in 1 cup water for 15 minutes; cool.'}),
    ('Foxtail Millet Salad', 'foxtail 70; cucumber 80; tomato 60; carrot 50; coriander 8', 'lemon 20; oliveoil 8; salt', 'A wholesome millet salad.',
     {'cooked': 'Cook the millet in 1¼ cups water for 15 minutes; fluff and cool.'}),
    ('Brown Rice Salad', 'brice 70; corn 60; capsicum 60; cucumber 60; coriander 8', 'lemon 20; oliveoil 8; pepper 0.5; salt', 'A brown rice salad with vegetables.',
     {'cooked': 'Cook the brown rice until tender; drain and cool.'}),
    ('Chicken Tikka Salad', 'chicken 200 grilled tikka; lettuce 60; cucumber 80; onion 40; tomato 60', 'hungcurd 40; mint 4; lemon 10; salt', 'Grilled chicken tikka over salad greens.',
     {'cooked': 'Grill the marinated chicken tikka until cooked.'}),
    ('Prawn Salad', 'prawn 200 cooked; lettuce 60; cucumber 80; onion 30; tomato 50', 'lemon 15; pepper 1; oliveoil 5; garlic 2; salt', 'A light prawn salad.',
     {'cooked': 'Sauté the prawns with garlic for 3 minutes; cool.'}),
    ('Fish Salad', 'fish 200 grilled, flaked; lettuce 60; cucumber 80; onion 30', 'lemon 15; pepper 1; oliveoil 5; salt', 'Grilled fish salad.', {'cooked': 'Grill the fish and flake it.'}),
    ('Egg Spinach Salad', 'egg 150 hard-boiled; spinach 60 baby leaves; tomato 60; onion 30', 'lemon 10; oliveoil 5; pepper 0.5; salt', 'Boiled eggs on fresh spinach.',
     {'cooked': 'Hard-boil the eggs for 10 minutes; peel and quarter.'}),
    ('Tofu Sprouts Salad', 'tofu 150 seared; sprouts 120; cucumber 60', 'lemon 10; soysauce 5; sesame 5', 'A vegan protein salad.', {}),
    ('Peanut Sprouts Salad', 'sprouts 150; peanut 25 roasted; onion 30; tomato 50', LD, 'Sprouts and peanuts with lemon.', {}),
    ('Sweet Corn Pomegranate Salad', 'corn 200; pomegranate 60; onion 30; mint 4', 'lemon 15; chaat 1; salt', 'Sweet corn with pomegranate.', {}),
    ('Watermelon Cucumber Salad', 'watermelon 300; cucumber 150; mint 5', 'lemon 10; blacksalt; pepper 0.3', 'A hydrating summer salad.', {}),
    ('Mixed Fruit Salad with Seeds', 'apple 100; papaya 100; pomegranate 40; banana 80; pumpkinseed 10; sunseed 10', 'lemon 10; honey 7', 'Fruit salad topped with seeds.', {}),
    ('Lettuce Cucumber Salad', 'lettuce 100; cucumber 150; onion 30', 'lemon 15; oliveoil 5; pepper 0.5; salt', 'A simple crunchy green salad.', {}),
]:
    salad(name, base, dressing, desc, **kw)

for name, add, desc, kw in [
    ('Spinach Corn Raita', 'spinach 60 blanched, chopped; corn 60 boiled', 'Raita with spinach and corn.', {}),
    ('Carrot Cucumber Raita', 'carrot 60 grated; cucumber 80 grated', 'Raita with carrot and cucumber.', {}),
    ('Banana Raita', 'banana 100 sliced', 'Mildly sweet banana raita.', {'spice': 'elaichipowder 0.3; blacksalt'}),
    ('Apple Walnut Raita', 'apple 100 chopped; walnut 15', 'Apple and walnut raita.', {'spice': 'jeerapowder 0.5; blacksalt'}),
    ('Mango Raita', 'mango 120 chopped', 'Sweet mango raita.', {'spice': 'jeerapowder 0.5; blacksalt'}),
    ('Grapes Raita', 'grapes 120 halved', 'A refreshing grapes raita.', {'spice': 'jeerapowder 0.5; blacksalt'}),
    ('Garlic Raita', 'garlic 6 grated; coriander 6', 'A punchy garlic raita for kebabs.', {}),
    ('Baingan Raita', 'brinjal 200 roasted, mashed; garlic 2', 'Smoky roasted brinjal raita.', {}),
    ('Peanut Cucumber Raita', 'cucumber 120 chopped; peanut 20 roasted, crushed', 'Cucumber raita with crushed peanuts.', {}),
    ('Mooli Raita', 'mooli 100 grated, squeezed', 'Radish raita, light and digestive.', {}),
    ('Capsicum Raita', 'capsicum 80 finely chopped; onion 30', 'Crunchy capsicum raita.', {}),
    ('Tomato Raita', 'tomato 120 finely chopped; coriander 6', 'A simple tomato raita.', {}),
    ('Zucchini Raita', 'zucchini 120 grated, sautéed', 'Raita with sautéed zucchini.', {}),
]:
    raita(name, add, desc, **kw)

for name, veg, desc, kw in [
    ('Spinach Lentil Soup', 'masoor 60; spinach 150; tomato 60', 'A hearty lentil soup with spinach.', {'pc': True, 'spice': 'jeera 1; pepper 1; haldi 0.3; salt'}),
    ('Tomato Lentil Soup', 'masoor 50; tomato 300', 'Tomato and red lentil soup.', {'pc': True}),
    ('Masoor Dal Soup', 'masoor 80; carrot 50', 'A simple, protein-rich masoor soup.', {'pc': True, 'spice': 'jeera 1; pepper 1; haldi 0.3; salt'}),
    ('Chickpea Soup', 'chickpea 80 soaked; tomato 100; carrot 50', 'A thick chickpea and vegetable soup.', {'pc': True, 'spice': 'jeerapowder 1; pepper 1; salt'}),
    ('Rajma Soup', 'rajma 70 soaked; tomato 100; onion 40', 'A hearty kidney bean soup.', {'pc': True, 'spice': 'jeerapowder 1; chilli 0.5; salt'}),
    ('Green Peas Soup', 'peas 300; potato 50', 'A smooth green pea soup with mint.', {'finish': 'mint 3; lemon 5'}),
    ('Corn Spinach Soup', 'corn 150; spinach 120; milk 100', 'A creamy corn and spinach soup.', {}),
    ('Carrot Beetroot Soup', 'carrot 250; beet 150', 'A vivid carrot and beetroot soup.', {}),
    ('Carrot Tomato Soup', 'carrot 200; tomato 300', 'A sweet-tangy carrot tomato soup.', {}),
    ('Pumpkin Lentil Soup', 'pumpkin 300; masoor 40', 'Pumpkin soup with red lentils.', {'pc': True}),
    ('Zucchini Soup', 'zucchini 400; potato 50; milk 100', 'A light zucchini soup.', {}),
    ('Mushroom Spinach Soup', 'mushroom 200; spinach 100; milk 120', 'Mushroom and spinach soup.', {}),
    ('Roasted Red Pepper Tomato Soup', 'redcapsicum 200 roasted; tomato 300', 'A smoky red pepper and tomato soup.', {}),
    ('Cabbage Carrot Clear Soup', 'cabbage 150; carrot 80; springonion 20', 'A light clear soup.', {'blend': False, 'mins': 8}),
    ('Ginger Garlic Clear Soup', 'carrot 50; cabbage 50; beans 40; ginger 15; springonion 20', 'A warming clear soup for colds.', {'blend': False, 'mins': 8}),
    ('Tofu Clear Soup', 'tofu 120 cubed; carrot 50; cabbage 50; springonion 20', 'A protein-rich clear soup with tofu.', {'blend': False, 'mins': 8, 'spice': 'pepper 1; soysauce 5; salt'}),
    ('Paneer Vegetable Soup', 'paneer 80 cubed; carrot 50; beans 40; peas 40; tomato 60', 'A vegetable soup with paneer cubes.', {'blend': False, 'mins': 10}),
    ('Quinoa Vegetable Soup', 'quinoa 40; carrot 50; beans 40; peas 40; tomato 80', 'A filling quinoa vegetable soup.', {'blend': False, 'mins': 15}),
    ('Millet Vegetable Soup', 'foxtail 40; carrot 50; beans 40; peas 40; tomato 80', 'A wholesome millet soup.', {'blend': False, 'mins': 18}),
    ('Chicken Lemon Coriander Soup', 'chicken 150 shredded; carrot 40; coriander 15; springonion 20', 'A zesty chicken soup.', {'blend': False, 'finish': 'lemon 20; coriander 6', 'mins': 10}),
    ('Chicken Spinach Soup', 'chicken 150 shredded; spinach 120; garlic 6', 'Chicken soup with spinach.', {'blend': False, 'mins': 10}),
    ('Chicken Hot and Sour Soup', 'chicken 120 shredded; cabbage 50; carrot 40; mushroom 40', 'Spicy, tangy chicken soup.',
     {'blend': False, 'spice': 'soysauce 8; vinegar 8; pepper 2; chilliflakes 1; cornflour 8; salt', 'mins': 8}),
    ('Chicken Manchow Soup (Lighter)', 'chicken 120 minced; cabbage 50; carrot 40; capsicum 30; springonion 20', 'Garlicky chicken manchow without fried noodles.',
     {'blend': False, 'spice': 'soysauce 8; vinegar 5; pepper 1.5; cornflour 8; salt', 'mins': 8}),
    ('Egg Vegetable Soup', 'egg 100 beaten; carrot 40; cabbage 40; peas 30', 'Vegetable soup with egg ribbons.', {'blend': False, 'mins': 8}),
    ('Prawn Clear Soup', 'prawn 150; carrot 40; springonion 20; ginger 8', 'A light prawn broth.', {'blend': False, 'mins': 6}),
    ('Sweet Corn Tomato Soup', 'corn 150; tomato 300', 'A sweet-tangy corn tomato soup.', {}),
    ('Beetroot Ginger Soup', 'beet 300; ginger 10; carrot 60', 'A warming beetroot soup.', {}),
    ('Ash Gourd Soup', 'ashgourd 400; moong 20', 'A cooling ash gourd soup.', {'pc': True}),
    ('Radish Soup', 'mooli 300; potato 50', 'A peppery radish soup.', {}),
    ('Turnip Soup', 'turnip 300; potato 50; milk 80', 'A creamy turnip soup.', {}),
    ('Chicken Corn Clear Soup', 'chicken 120 shredded; corn 100; springonion 20', 'A light chicken and corn clear soup.', {'blend': False, 'mins': 8}),
]:
    soup(name, veg, desc, **kw)

for name, items, desc, kw in [
    ('Onion Chutney', 'onion 200; redchilli 4; tamarind 5; garlic 4; salt; oil 6', 'A sweet-spicy onion chutney.', {'cooked': 'Sauté onion and red chillies in oil until golden.'}),
    ('Tomato Garlic Chutney', 'tomato 250; garlic 15; redchilli 4; salt; oil 6', 'A garlicky tomato chutney.', {'cooked': 'Sauté garlic and chillies, add tomatoes and cook until mushy.'}),
    ('Mint Peanut Chutney', 'mint 30; coriander 20; peanut 30 roasted; gchilli 6; lemon 10; salt; water 40', 'Green chutney with peanuts.', {}),
    ('Coconut Mint Chutney', 'coconut 80; mint 15; gchilli 6; ginger 5; salt; water 60', 'Coconut chutney with mint.', {'temper': 'oil 4; mustard 2; curryleaf 1'}),
    ('Coconut Tomato Chutney', 'coconut 60; tomato 150; redchilli 3; garlic 3; salt; oil 5', 'A red coconut-tomato chutney.', {'cooked': 'Sauté tomato and chillies until soft.'}),
    ('Ridge Gourd Chutney', 'tori 200; gchilli 6; tamarind 5; urad_t 6; garlic 4; salt; oil 6', 'Andhra-style ridge gourd chutney.', {'cooked': 'Sauté the ridge gourd with dal and chillies until soft.'}),
    ('Brinjal Chutney (Vankaya Pachadi)', 'brinjal 250 roasted; tomato 80; gchilli 6; garlic 4; tamarind 5; salt', 'Smoky roasted brinjal chutney.', {'cooked': 'Roast the brinjal on the flame and peel.'}),
    ('Capsicum Chutney', 'capsicum 200; redchilli 3; urad_t 6; tamarind 5; garlic 4; salt; oil 6', 'A tangy capsicum chutney.', {'cooked': 'Sauté capsicum with dal and chillies until soft.'}),
    ('Cabbage Chutney', 'cabbage 200; urad_t 6; redchilli 3; tamarind 5; coconut 20; salt; oil 6', 'A mild cabbage chutney.', {'cooked': 'Sauté the cabbage with dal and chillies until soft.'}),
    ('Radish Chutney', 'mooli 200 grated; urad_t 6; redchilli 3; tamarind 5; salt; oil 6', 'A peppery radish chutney.', {'cooked': 'Sauté the radish with dal and chillies.'}),
    ('Gongura Chutney', 'gongura 100; redchilli 6; garlic 8; salt; oil 8', 'Andhra’s tangy sorrel leaf chutney.', {'cooked': 'Sauté the gongura leaves until mushy; roast the chillies separately.'}),
    ('Moringa Leaf Chutney', 'moringaleaf 40; coconut 40; gchilli 6; tamarind 5; salt', 'A nutrient-dense moringa leaf chutney.', {'cooked': 'Sauté the moringa leaves for 2 minutes.'}),
    ('Spinach Chutney', 'spinach 150; coriander 15; gchilli 6; garlic 3; lemon 10; salt', 'A green spinach chutney.', {'cooked': 'Blanch the spinach for 1 minute.'}),
    ('Methi Chutney', 'methi 60; coconut 30; gchilli 6; tamarind 5; salt; oil 4', 'A slightly bitter fenugreek chutney.', {'cooked': 'Sauté the methi for 2 minutes.'}),
    ('Sesame Peanut Chutney Powder', 'sesame 50; peanut 50; redchilli 6; garlic 6; salt', 'A dry chutney powder of sesame and peanuts.',
     {'cooked': 'Dry-roast the sesame and peanuts separately.', 'store': 'keeps in an airtight jar for 3 weeks.'}),
    ('Curry Leaf Podi', 'curryleaf 15; urad 30; chanadal 30; redchilli 6; hing; salt', 'A dry curry leaf chutney powder.',
     {'cooked': 'Dry-roast the dals, chillies and curry leaves until crisp.', 'store': 'keeps in an airtight jar for 1 month.'}),
    ('Shengdana Chutney (Peanut Powder)', 'peanut 120 roasted; garlic 6; chilli 3; salt', 'Maharashtrian dry peanut chutney.',
     {'cooked': 'Dry-roast the peanuts and remove the skins.', 'store': 'keeps in an airtight jar for 2 weeks.'}),
    ('Coconut Chutney Powder', 'coconut 100 dry; urad 20; redchilli 5; tamarind 5; salt', 'A dry coconut chutney powder.',
     {'cooked': 'Dry-roast the coconut until golden and the dal and chillies separately.', 'store': 'keeps in an airtight jar in the fridge for 2 weeks.'}),
    ('Moringa Podi', 'moringaleaf 40 dried; urad 30; sesame 15; redchilli 5; salt', 'A dry moringa leaf chutney powder.',
     {'cooked': 'Dry the moringa leaves in the shade and roast lightly; roast the dal and sesame.', 'store': 'keeps in an airtight jar for 1 month.'}),
    ('Pumpkin Seed Chutney', 'pumpkinseed 50 roasted; coriander 20; gchilli 6; lemon 10; salt; water 40', 'A green chutney with roasted pumpkin seeds.', {}),
    ('Avocado Mint Dip', 'avocado 150; mint 8; lemon 15; gchilli 3; garlic 2; salt', 'A creamy avocado-mint dip.', {'sub': 'Dip'}),
    ('Beetroot Hummus', 'chickpea 100 boiled; beet 80 roasted; sesame 15; garlic 4; lemon 20; oliveoil 8; salt; water 30', 'Pink hummus with roasted beetroot.',
     {'sub': 'Dip', 'cooked': 'Pressure-cook the soaked chickpeas until very soft and roast the beetroot.'}),
    ('Roasted Pepper Hummus', 'chickpea 100 boiled; redcapsicum 100 roasted; sesame 15; garlic 4; lemon 20; oliveoil 8; salt; water 30', 'Smoky red pepper hummus.',
     {'sub': 'Dip', 'cooked': 'Pressure-cook the soaked chickpeas and roast the red pepper.'}),
    ('Curd Garlic Dip', 'hungcurd 200; garlic 6; pepper 0.5; coriander 6; salt', 'A garlicky hung curd dip.', {'sub': 'Dip'}),
    ('Cucumber Hung Curd Dip (Indian Tzatziki)', 'hungcurd 200; cucumber 100 grated, squeezed; mint 4; garlic 2; jeerapowder 0.5; salt', 'A cooling cucumber-curd dip.', {'sub': 'Dip'}),
    ('Peanut Curd Dip', 'hungcurd 150; peanut 30 roasted, ground; gchilli 3; coriander 6; salt', 'A creamy peanut and curd dip.', {'sub': 'Dip'}),
    ('Tomato Salsa (Indian Style)', 'tomato 250 finely chopped; onion 60; gchilli 3; coriander 10; lemon 15; jeerapowder 0.5; salt', 'A fresh, chunky tomato salsa.',
     {'sub': 'Dip'}),
    ('Mango Salsa', 'mango 200 diced; onion 40; capsicum 40; gchilli 3; coriander 8; lemon 15; salt', 'A sweet-spicy mango salsa.', {'sub': 'Dip'}),
    ('Green Apple Chutney', 'apple 200; mint 15; gchilli 3; lemon 10; jeerapowder 0.5; salt', 'A tangy apple-mint chutney.', {}),
    ('Dates Tamarind Dip', 'dates 80; tamarind 20; jeerapowder 1; dryginger 0.5; blacksalt; water 120', 'A sweet-sour dip sweetened only with dates.',
     {'cooked': 'Simmer the dates and tamarind in water for 8 minutes.', 'store': 'keeps in the fridge for 2 weeks.'}),
]:
    chutney(name, items, desc, **kw)
