"""Volume 2 - dry sabzis and paneer / vegetable curries."""
import core
from fam_sabzi import sabzi, stuffed_veg
from fam_gravy import curry, BASE

core.VOLUME = 2

# ---- Poriyal (Tamil coconut stir-fries)
for name, veg, desc, mins, extra in [
    ('Broccoli Poriyal', 'broccoli 400 small florets', 'Broccoli stir-fried with coconut and urad dal.', 6, ''),
    ('Zucchini Poriyal', 'zucchini 450 diced', 'Zucchini poriyal with coconut.', 6, ''),
    ('Capsicum Poriyal', 'capsicum 400 diced', 'Capsicum stir-fried South Indian style.', 6, ''),
    ('Mixed Vegetable Poriyal', 'carrot 120; beans 120; cabbage 120; peas 60', 'A colourful mixed vegetable poriyal.', 10, ''),
    ('Sweet Potato Poriyal', 'sweetpotato 400 cubed', 'Sweet potato stir-fried with coconut and chilli.', 12, 'chilli 0.5'),
    ('Pumpkin Poriyal', 'pumpkin 450 cubed', 'Yellow pumpkin poriyal, mildly sweet.', 10, ''),
    ('Brinjal Poriyal', 'brinjal 400 cubed', 'Brinjal poriyal with coconut and sambar powder.', 12, 'sambar 3'),
    ('Radish Poriyal', 'mooli 400 grated', 'White radish poriyal with coconut.', 8, ''),
    ('Ridge Gourd Poriyal', 'tori 450 peeled, cubed', 'Ridge gourd poriyal, light and hydrating.', 8, ''),
    ('Cluster Beans Poriyal', 'gwar 350 chopped', 'Kothavarangai poriyal with coconut.', 12, ''),
    ('Keerai Poriyal (Spinach)', 'spinach 400 chopped', 'Tamil-style spinach stir-fry with coconut.', 5, ''),
    ('Amaranth Keerai Poriyal', 'amaranth 400 chopped', 'Amaranth leaves poriyal, rich in calcium.', 6, ''),
    ('Murungai Keerai Poriyal', 'moringaleaf 120; onion 60', 'Moringa leaf poriyal, a nutrient-dense side.', 6, ''),
    ('Corn Poriyal', 'corn 300; capsicum 80', 'Sweet corn poriyal.', 6, ''),
    ('Peas Carrot Poriyal', 'peas 200; carrot 200 diced', 'Carrot and peas poriyal.', 8, ''),
    ('Lauki Poriyal', 'lauki 450 cubed', 'Bottle gourd poriyal with moong dal.', 8, 'moong 20 soaked'),
    ('Cauliflower Poriyal', 'cauliflower 400 small florets', 'Cauliflower poriyal with coconut.', 10, ''),
    ('Cabbage Carrot Poriyal', 'cabbage 300 shredded; carrot 100 grated', 'Cabbage and carrot poriyal.', 8, ''),
    ('Beans Carrot Poriyal', 'beans 250 chopped; carrot 150 chopped', 'Beans and carrot poriyal.', 10, ''),
    ('Mushroom Poriyal', 'mushroom 350 sliced; onion 60', 'Mushroom poriyal with coconut.', 8, 'pepper 1'),
]:
    sabzi(name, veg, desc, style='poriyal', mins=mins, extra_sp=extra, sub='Poriyal')

# ---- Thoran (Kerala)
for name, veg, desc, mins in [
    ('Broccoli Thoran', 'broccoli 400 finely chopped', 'Kerala-style broccoli thoran.', 6),
    ('Cauliflower Thoran', 'cauliflower 400 finely chopped', 'Cauliflower thoran with coconut.', 8),
    ('Zucchini Thoran', 'zucchini 450 finely chopped', 'Zucchini thoran.', 6),
    ('Snake Gourd Thoran', 'snakegourd 450 finely chopped', 'Padavalanga thoran.', 8),
    ('Cheera Thoran (Amaranth)', 'amaranth 400 chopped', 'Red amaranth thoran.', 5),
    ('Muringa Ila Thoran (Moringa)', 'moringaleaf 120; shallot 30', 'Moringa leaf thoran, a Kerala favourite.', 6),
    ('Raw Banana Thoran', 'rawbanana 300 finely chopped', 'Vazhakka thoran with coconut.', 12),
    ('Pumpkin Thoran', 'pumpkin 450 finely chopped', 'Mathanga thoran.', 10),
    ('Ivy Gourd Thoran', 'kundru 400 finely chopped', 'Kovakka thoran.', 12),
    ('Mushroom Thoran', 'mushroom 350 chopped', 'Koon thoran with coconut.', 8),
    ('Okra Thoran', 'bhindi 350 finely chopped', 'Vendakka thoran.', 12),
    ('Flat Beans Thoran', 'sem 350 finely chopped', 'Flat beans thoran.', 10),
    ('Cluster Beans Thoran', 'gwar 350 finely chopped', 'Cluster beans thoran.', 12),
    ('Bitter Gourd Thoran', 'karela 300 finely chopped', 'Pavakka thoran; coconut balances the bitterness.', 12),
    ('Drumstick Leaves Egg Thoran', 'moringaleaf 100; egg 100 beaten', 'Moringa leaves scrambled with egg and coconut.', 5),
]:
    sabzi(name, veg, desc, style='thoran', mins=mins, sub='Thoran')

# ---- Aloo combinations (jeera style)
for name, veg, desc, mins in [
    ('Aloo Kundru', 'kundru 300 sliced; potato 150 cubed', 'Ivy gourd with potato.', 15),
    ('Aloo Tinda', 'tinda 300 cubed; potato 150 cubed', 'Round gourd with potato.', 15),
    ('Aloo Parwal', 'parwal 300 halved; potato 150 cubed', 'Pointed gourd with potato.', 15),
    ('Aloo Lauki', 'lauki 350 cubed; potato 150 cubed', 'Bottle gourd and potato.', 12),
    ('Aloo Karela', 'karela 250 sliced; potato 200 cubed', 'Bitter gourd with potato; the potato mellows the bitterness.', 15),
    ('Aloo Bhindi', 'bhindi 300 cut in 1-inch pieces; potato 150 cubed', 'Okra with potato.', 15),
    ('Aloo Mooli', 'mooli 300 cubed; potato 150 cubed', 'Radish with potato.', 12),
    ('Aloo Shalgam', 'turnip 300 cubed; potato 150 cubed', 'Turnip with potato.', 15),
    ('Aloo Gajar', 'carrot 300 cubed; potato 150 cubed', 'Carrot and potato.', 12),
    ('Aloo Sem', 'sem 300 chopped; potato 150 cubed', 'Flat beans with potato.', 15),
    ('Aloo Gwar', 'gwar 300 chopped; potato 150 cubed', 'Cluster beans with potato.', 15),
    ('Kaddu Aloo', 'pumpkin 350 cubed; potato 150 cubed', 'Pumpkin and potato, sweet and tangy.', 12),
    ('Patta Gobhi Aloo', 'cabbage 350 shredded; potato 150 cubed', 'Cabbage with potato.', 12),
    ('Aloo Mushroom', 'mushroom 250 quartered; potato 200 cubed', 'Mushrooms with potato.', 12),
    ('Aloo Matar (Dry)', 'potato 300 cubed; peas 150', 'Dry potato and peas.', 12),
    ('Shakarkandi Sabzi', 'sweetpotato 450 cubed', 'Sweet potato cooked with cumin and spices.', 12),
    ('Methi Gobi', 'cauliflower 350 florets; methi 100 chopped', 'Cauliflower with fresh methi.', 12),
    ('Palak Gobi (Dry)', 'cauliflower 350 florets; spinach 200 chopped', 'Cauliflower with spinach.', 12),
    ('Gajar Matar Methi', 'carrot 200 diced; peas 120; methi 80 chopped', 'Carrot, peas and methi, a winter sabzi.', 12),
    ('Beans Matar', 'beans 300 chopped; peas 120', 'French beans with peas.', 12),
]:
    sabzi(name, veg, desc, style='jeera', mins=mins)

# ---- Onion / tomato / garlic / achari / Bengali styles
for name, veg, desc, style, mins, unc in [
    ('Capsicum Onion Sabzi', 'capsicum 350 strips; onion 100 petals', 'Capsicum and onion stir-fry.', 'onion', 8, True),
    ('Mushroom Capsicum Dry', 'mushroom 300 sliced; capsicum 150 diced', 'Mushrooms and capsicum, dry.', 'onion', 8, True),
    ('Baby Corn Mushroom Dry', 'babycorn 200 sliced; mushroom 200 sliced', 'Baby corn and mushroom stir-fry.', 'onion', 8, True),
    ('Tofu Capsicum Stir-fry', 'tofu 250 cubed; capsicum 150; onion 60', 'Tofu and capsicum with Indian spices.', 'onion', 6, True),
    ('Paneer Capsicum Dry', 'paneer 200 cubed; capsicum 150; onion 60', 'Paneer and capsicum tossed in spices.', 'onion', 5, True),
    ('Soya Capsicum Dry', 'soya 80 boiled, squeezed; capsicum 150; onion 60', 'Soya chunks and capsicum, dry.', 'onion', 8, True),
    ('Pyaz Baingan', 'brinjal 350 cubed; onion 150 sliced', 'Brinjal with plenty of onion.', 'onion', 12, False),
    ('Spring Onion Besan Sabzi', 'springonion 250 chopped; besan 30 roasted', 'Spring onion greens with roasted besan, Maharashtrian style.', 'jeera', 6, True),
    ('Spring Onion Aloo', 'springonion 200 chopped; potato 200 cubed', 'Spring onions with potato.', 'jeera', 10, False),
    ('Cabbage Capsicum Sabzi', 'cabbage 300 shredded; capsicum 150', 'Cabbage and capsicum.', 'onion', 8, False),
    ('Bhindi Tamatar', 'bhindi 350 chopped', 'Okra cooked with tomatoes.', 'tomato', 12, True),
    ('Gobi Tamatar', 'cauliflower 400 florets', 'Cauliflower in a tomato masala.', 'tomato', 12, False),
    ('Baingan Tamatar', 'brinjal 400 cubed', 'Brinjal and tomato.', 'tomato', 12, False),
    ('Arbi Tamatar', 'arbi 350 boiled, sliced', 'Colocasia with tomato.', 'tomato', 8, False),
    ('Mushroom Tamatar (Dry)', 'mushroom 350 quartered', 'Mushrooms in a dry tomato masala.', 'tomato', 8, True),
    ('Kaddu Tamatar', 'pumpkin 450 cubed', 'Pumpkin with tomato.', 'tomato', 12, False),
    ('Lahsuni Palak', 'spinach 500 chopped', 'Spinach with a bold garlic tempering.', 'garlic', 6, True),
    ('Garlic Beans', 'beans 400 chopped', 'French beans with garlic.', 'garlic', 10, False),
    ('Garlic Mushroom', 'mushroom 400 sliced', 'Mushrooms sautéed with garlic.', 'garlic', 6, True),
    ('Lahsuni Gobi', 'cauliflower 400 florets', 'Cauliflower with garlic.', 'garlic', 12, False),
    ('Garlic Zucchini', 'zucchini 450 sliced', 'Zucchini with garlic and chilli.', 'garlic', 5, True),
    ('Lahsuni Methi', 'methi 300 chopped; potato 100 cubed', 'Methi greens with garlic.', 'garlic', 8, False),
    ('Achari Gobi', 'cauliflower 400 florets', 'Cauliflower with pickle spices.', 'achari', 12, False),
    ('Achari Aloo', 'potato 400 boiled, cubed', 'Potatoes with tangy pickle spices.', 'achari', 6, True),
    ('Achari Baingan', 'brinjal 400 cubed', 'Brinjal with pickle spices.', 'achari', 12, False),
    ('Achari Karela', 'karela 350 sliced', 'Bitter gourd with pickle spices.', 'achari', 15, True),
    ('Achari Mushroom', 'mushroom 350 halved', 'Mushrooms with pickle spices.', 'achari', 8, True),
    ('Achari Tinda', 'tinda 400 quartered', 'Round gourd with pickle spices.', 'achari', 15, False),
    ('Achari Kundru', 'kundru 400 sliced', 'Ivy gourd with pickle spices.', 'achari', 15, True),
    ('Achari Mixed Vegetables', 'carrot 100; cauliflower 120; beans 100; potato 100; peas 60', 'Mixed vegetables with pickle spices.', 'achari', 12, False),
    ('Bandhakopi (Bengali Cabbage)', 'cabbage 400 shredded; potato 100 cubed; peas 60', 'Bengali cabbage with potato and peas.', 'bengali', 12, False),
    ('Bengali Beans Aloo', 'beans 300 chopped; potato 150 cubed', 'Beans and potato with kalonji.', 'bengali', 12, False),
    ('Lau Ghonto (Bengali Lauki)', 'lauki 500 grated; moong 30 roasted', 'Bengali bottle gourd with roasted moong dal.', 'bengali', 15, False),
    ('Kumro Chokka', 'pumpkin 350 cubed; potato 120 cubed; chickpea 40 soaked, boiled', 'Bengali pumpkin and potato with chickpeas.', 'bengali', 15, False),
    ('Jhinge Aloo Posto', 'tori 350 cubed; potato 120; poppy 25 ground', 'Ridge gourd and potato in poppy seed paste.', 'bengali', 12, False),
    ('Bengali Mula (Radish)', 'mooli 400 cubed', 'Bengali radish stir-fry.', 'bengali', 12, False),
    ('Dherosh Bhaja (Bengali Okra)', 'bhindi 400 slit', 'Bengali-style okra.', 'bengali', 12, True),
    ('Bengali Potol Aloo Posto', 'parwal 300 halved; potato 120; poppy 25 ground', 'Pointed gourd in poppy paste.', 'bengali', 15, False),
    ('Tofu Methi Stir-fry', 'tofu 250 cubed; methi 80 chopped', 'Tofu with fresh methi.', 'garlic', 5, True),
    ('Soya Methi Dry', 'soya 80 boiled, squeezed; methi 80 chopped', 'Soya chunks with methi.', 'onion', 8, True),
]:
    sabzi(name, veg, desc, style=style, mins=mins, uncovered=unc)

stuffed_veg('Stuffed Mushrooms (Pan-cooked)', 'mushroom 300 large, stems removed', 'Large mushrooms stuffed with spiced paneer and cooked in a pan.',
            'Wipe the mushrooms clean and remove the stems.', stuffing='paneer 100 crumbled; onion 30 finely chopped; garlic 4; chilli 0.5; garam 0.5; coriander 6; salt', mins=10)
stuffed_veg('Soya Stuffed Capsicum', 'capsicum 400 small', 'Capsicums stuffed with spicy soya keema.', 'Cut the tops off and deseed.',
            stuffing='soyagran 60 soaked, squeezed; onion 40; tomato 40; garam 1; chilli 1; salt', mins=15)
stuffed_veg('Bharwa Lauki Rings', 'lauki 400 thick rings, centres scooped', 'Lauki rings stuffed with paneer and peas.', 'Peel the lauki, cut into thick rings and scoop out the seeds.',
            stuffing='paneer 100 crumbled; peas 60 mashed; garam 1; chilli 0.5; salt', mins=15)
stuffed_veg('Bharwa Kundru', 'kundru 350', 'Ivy gourds stuffed with a peanut-besan masala.', 'Slit each kundru lengthwise without cutting through.',
            stuffing='besan 25 roasted; peanut 20 crushed; dhania 3; chilli 1; amchur 2; salt', mins=18)

# ---- Curries: main x gravy base
P = 'paneer 200 cubed'
PADD = 'Add the paneer and simmer only 3–4 minutes so it stays soft.'
for name, main, desc, base, simmer, add_txt in [
    ('Paneer Chettinad', P, 'Paneer in a fiery, peppery Chettinad masala.', 'chettinad', 4, PADD),
    ('Paneer Masala', P, 'Paneer in a homestyle onion-tomato masala.', 'masala', 4, PADD),
    ('Paneer Mushroom Masala', 'paneer 120 cubed; mushroom 150 quartered', 'Paneer and mushrooms in a spiced gravy.', 'masala', 6, ''),
    ('Kadai Paneer Mushroom', 'paneer 120 cubed; mushroom 150 halved', 'Paneer and mushrooms in kadai masala.', 'kadai', 5, ''),
    ('Paneer Capsicum Masala', 'paneer 160 cubed; capsicum 120 diced', 'Paneer and capsicum in a tomato gravy.', 'masala', 5, ''),
    ('Tofu Korma', 'tofu 250 cubed', 'Tofu in a mild cashew-curd korma.', 'korma', 4, ''),
    ('Tofu Coconut Curry', 'tofu 250 cubed', 'Tofu simmered in a spiced coconut milk gravy.', 'coconut', 5, ''),
    ('Tofu Tikka Masala', 'tofu 250 cubed', 'Grilled tofu tikka in a smoky tomato gravy.', 'tikka', 4, ''),
    ('Tofu Kolhapuri', 'tofu 250 cubed', 'Tofu in a fiery Kolhapuri masala.', 'kolhapuri', 5, ''),
    ('Tofu Chettinad', 'tofu 250 cubed', 'Tofu in a peppery Chettinad masala.', 'chettinad', 5, ''),
    ('Achari Tofu', 'tofu 250 cubed', 'Tofu in a tangy pickle-spice gravy.', 'achari', 5, ''),
    ('Tofu Methi Malai', 'tofu 250 cubed', 'Tofu in a mild methi gravy.', 'methi_malai', 4, ''),
    ('Tofu Do Pyaza', 'tofu 250 cubed', 'Tofu with onions cooked two ways.', 'dopyaza', 4, ''),
    ('Mushroom Coconut Curry', 'mushroom 300 halved', 'Mushrooms in a coconut milk curry.', 'coconut', 8, ''),
    ('Mushroom Kolhapuri', 'mushroom 300 halved', 'Mushrooms in a fiery Kolhapuri masala.', 'kolhapuri', 8, ''),
    ('Achari Mushroom Curry', 'mushroom 300 halved', 'Mushrooms in a pickle-spice gravy.', 'achari', 8, ''),
    ('Mushroom Methi Malai', 'mushroom 300 sliced', 'Mushrooms in a creamy methi gravy.', 'methi_malai', 6, ''),
    ('Mushroom Tikka Masala', 'mushroom 300 whole', 'Grilled mushroom tikka in a spiced tomato gravy.', 'tikka', 5, ''),
    ('Mushroom Stew', 'mushroom 250; potato 120; carrot 80', 'Mushrooms in a mild Kerala coconut stew.', 'stew', 10, ''),
    ('Vegetable Makhanwala (Lighter)', 'carrot 80; beans 80; peas 80; cauliflower 100; paneer 60', 'Mixed vegetables in a silky tomato-cashew gravy.', 'makhani', 10, ''),
    ('Mixed Vegetable Methi Malai', 'carrot 80; beans 80; peas 80; corn 60', 'Mixed vegetables in a creamy methi gravy.', 'methi_malai', 10, ''),
    ('Achari Mixed Vegetable Curry', 'carrot 80; beans 80; cauliflower 100; potato 100', 'Mixed vegetables in a pickle-spice gravy.', 'achari', 12, ''),
    ('Vegetable Do Pyaza', 'carrot 80; beans 80; cauliflower 100; capsicum 80', 'Mixed vegetables with plenty of onions.', 'dopyaza', 10, ''),
    ('Vegetable Tikka Masala', 'cauliflower 120; capsicum 80; paneer 80; babycorn 80', 'Grilled vegetables in a tikka masala gravy.', 'tikka', 6, ''),
    ('Aloo Palak Curry', 'potato 300 cubed', 'Potatoes in a spinach gravy.', 'palak', 10, ''),
    ('Aloo Korma', 'potato 350 cubed', 'Potatoes in a mild korma gravy.', 'korma', 12, ''),
    ('Potato Kurma (South Indian)', 'potato 300 cubed; peas 60', 'Potatoes in a coconut kurma, perfect with puri.', 'coconut', 12, ''),
    ('Aloo Do Pyaza', 'potato 350 cubed', 'Potatoes with onions cooked two ways.', 'dopyaza', 12, ''),
    ('Aloo Chettinad', 'potato 350 cubed', 'Potatoes in a peppery Chettinad masala.', 'chettinad', 12, ''),
    ('Matar Masala', 'peas 300', 'Green peas in a spiced onion-tomato gravy.', 'masala', 8, ''),
    ('Matar Korma', 'peas 250; potato 80', 'Peas in a mild korma.', 'korma', 8, ''),
    ('Corn Masala', 'corn 300', 'Sweet corn in a spiced tomato gravy.', 'masala', 6, ''),
    ('Corn Methi Malai', 'corn 250', 'Sweet corn in a creamy fenugreek gravy.', 'methi_malai', 5, ''),
    ('Kadai Corn Capsicum', 'corn 200; capsicum 150', 'Sweet corn and capsicum in kadai masala.', 'kadai', 5, ''),
    ('Corn Korma', 'corn 250; peas 60', 'Sweet corn in a mild korma.', 'korma', 6, ''),
    ('Gobi Korma', 'cauliflower 400 florets', 'Cauliflower in a mild white korma.', 'korma', 10, ''),
    ('Kadai Gobi', 'cauliflower 400 florets', 'Cauliflower in kadai masala.', 'kadai', 10, ''),
    ('Palak Gobi Curry', 'cauliflower 350 florets', 'Cauliflower in a spinach gravy.', 'palak', 10, ''),
    ('Gobi Coconut Curry', 'cauliflower 350 florets; peas 60', 'Cauliflower in a coconut gravy.', 'coconut', 10, ''),
    ('Gobi Chettinad', 'cauliflower 400 florets', 'Cauliflower in Chettinad masala.', 'chettinad', 10, ''),
    ('Baingan Kolhapuri', 'brinjal 400 cubed', 'Brinjal in a fiery Kolhapuri masala.', 'kolhapuri', 12, ''),
    ('Baingan Coconut Curry', 'brinjal 400 cubed', 'Brinjal in a coconut gravy.', 'coconut', 12, ''),
    ('Achari Baingan Curry', 'brinjal 400 small, slit', 'Small brinjals in a pickle-spice gravy.', 'achari', 12, ''),
    ('Soya Kadai', 'soya 100 boiled, squeezed; capsicum 100', 'Soya chunks in kadai masala.', 'kadai', 8, ''),
    ('Soya Makhani', 'soya 100 boiled, squeezed', 'Soya chunks in a makhani gravy.', 'makhani', 8, ''),
    ('Soya Palak', 'soya 90 boiled, squeezed', 'Soya chunks in a spinach gravy.', 'palak', 6, ''),
    ('Soya Kolhapuri', 'soya 100 boiled, squeezed', 'Soya chunks in Kolhapuri masala.', 'kolhapuri', 8, ''),
    ('Soya Chettinad', 'soya 100 boiled, squeezed', 'Soya chunks in Chettinad masala.', 'chettinad', 8, ''),
    ('Sweet Potato Coconut Curry', 'sweetpotato 350 cubed', 'Sweet potato in a coconut curry.', 'coconut', 12, ''),
    ('Sweet Potato Masala Curry', 'sweetpotato 350 cubed', 'Sweet potato in a spiced tomato gravy.', 'masala', 12, ''),
    ('Kaddu Masala Curry', 'pumpkin 450 cubed', 'Pumpkin in a tangy masala gravy.', 'masala', 10, ''),
    ('Lauki Masala Curry', 'lauki 450 cubed', 'Bottle gourd in a homestyle gravy.', 'masala', 12, ''),
    ('Lauki Coconut Curry', 'lauki 450 cubed', 'Bottle gourd in a coconut gravy.', 'coconut', 12, ''),
    ('Lauki Korma', 'lauki 400 cubed; peas 60', 'Bottle gourd in a mild korma.', 'korma', 12, ''),
    ('Tinda Masala Curry', 'tinda 400 quartered', 'Round gourd in a spiced gravy.', 'masala', 12, ''),
    ('Kathal Kolhapuri', 'jackfruit 400 cubed, boiled', 'Raw jackfruit in Kolhapuri masala.', 'kolhapuri', 12, ''),
    ('Raw Banana Masala Curry', 'rawbanana 300 cubed', 'Raw banana in a North Indian gravy.', 'masala', 12, ''),
    ('Drumstick Coconut Curry', 'drumstick 300 cut in 3-inch pieces', 'Drumsticks in a coconut gravy.', 'coconut', 12, ''),
    ('Drumstick Masala Curry', 'drumstick 300 cut in 3-inch pieces; potato 100', 'Drumsticks in a tomato masala.', 'masala', 12, ''),
    ('Shimla Mirch Masala Curry', 'capsicum 350 diced', 'Capsicum in a spiced gravy.', 'masala', 6, ''),
    ('Baby Corn Masala', 'babycorn 300 sliced', 'Baby corn in a spiced gravy.', 'masala', 6, ''),
    ('Baby Corn Makhani', 'babycorn 300 sliced; capsicum 60', 'Baby corn in a makhani gravy.', 'makhani', 6, ''),
    ('Kadai Baby Corn', 'babycorn 250 sliced; capsicum 100', 'Baby corn in kadai masala.', 'kadai', 5, ''),
    ('Paneer Peas Coconut Curry', 'paneer 150 cubed; peas 100', 'Paneer and peas in a coconut curry.', 'coconut', 5, ''),
    ('Methi Paneer Masala', 'paneer 180 cubed; methi 60 chopped', 'Paneer with fresh methi in a tomato gravy.', 'masala', 4, ''),
    ('Palak Mushroom Paneer', 'mushroom 150; paneer 100 cubed', 'Mushroom and paneer in spinach gravy.', 'palak', 5, ''),
    ('Kerala Paneer Stew', 'paneer 180 cubed; potato 100', 'Paneer and potato in a mild coconut stew.', 'stew', 6, ''),
    ('Chickpea Korma', 'chickpea 150 soaked, boiled', 'Chickpeas in a mild korma gravy.', 'korma', 8, ''),
    ('Rajma Makhani', 'rajma 150 soaked, boiled', 'Rajma in a silky makhani gravy.', 'makhani', 10, ''),
    ('Kadai Chole', 'chickpea 160 soaked, boiled; capsicum 80', 'Chickpeas in kadai masala.', 'kadai', 8, ''),
    ('Chana Palak Masala', 'chickpea 150 soaked, boiled', 'Chickpeas in a spinach gravy.', 'palak', 8, ''),
]:
    curry(name, main, desc, base=base, simmer=simmer, add_txt=add_txt)
